<?php
declare(strict_types=1);

function bbs_designer_catalog(): array {
    return [
        'templateKinds'=>['Personal','Department'],'sides'=>['Front','Back'],
        'elementTypes'=>['DynamicText','StaticText','DynamicImage','StaticImage','QR','Shape'],
        'dataSources'=>[
            'Personal'=>['employee.full_name','employee.id','employee.department','employee.safety_unit','employee.position','employee.bbs_level','employee.photo','card.personal_qr','card.issue_date','template.name','organization.name','organization.logo'],
            'Department'=>['department.name','department.community_qr','template.name','organization.name','organization.logo'],
        ],
        'styleKeys'=>['fontFamily','fontSizePt','fontWeight','fontStyle','textAlign','verticalAlign','color','backgroundColor','borderColor','borderWidthPt','borderRadiusBP','lineHeight','letterSpacingPt','objectFit','objectPositionXBP','objectPositionYBP','opacity','shapeType'],
        'geometry'=>['unit'=>'basis-points','min'=>0,'max'=>10000],'versionStatuses'=>['Draft','Active','Archived'],
    ];
}
function bbs_designer_clean($value,int $max=255): string { return mb_substr(trim((string)($value??'')),0,$max); }
function bbs_designer_int($value,int $min,int $max,string $label): int { if(filter_var($value,FILTER_VALIDATE_INT)===false||(int)$value<$min||(int)$value>$max)throw new InvalidArgumentException("$label must be an integer from $min to $max.");return(int)$value; }
function bbs_designer_decimal($value,float $min,float $max,string $label): float { if(!is_numeric($value)||(float)$value<$min||(float)$value>$max)throw new InvalidArgumentException("$label must be from $min to $max.");return round((float)$value,2); }
function bbs_designer_kind($value): string { $value=strtolower(bbs_designer_clean($value,20));if($value==='personal')return'Personal';if($value==='department')return'Department';throw new InvalidArgumentException('Template kind must be Personal or Department.'); }
function bbs_designer_fields(string $kind): array { return bbs_designer_catalog()['dataSources'][$kind]; }
function bbs_designer_style($value): array { $input=is_array($value)?$value:[];$allowed=bbs_designer_catalog()['styleKeys'];$out=[];foreach($input as$key=>$item){if(!in_array($key,$allowed,true))throw new InvalidArgumentException("Style property $key is not allowed.");if(!is_string($item)&&!is_numeric($item)&&!is_bool($item))throw new InvalidArgumentException("Style property $key has an invalid value.");$out[$key]=is_string($item)?mb_substr($item,0,120):$item;}return$out; }
function bbs_designer_side(array $value): array {
    $side=bbs_designer_clean($value['side']??'',10);if(!in_array($side,['Front','Back'],true))throw new InvalidArgumentException('Side must be Front or Back.');
    $storage=bbs_designer_clean($value['storageClass']??'',40);if(!in_array($storage,['PersonalTemplate','DepartmentTemplate','DesignerAsset'],true))throw new InvalidArgumentException("Storage class is invalid for $side.");
    $stored=bbs_designer_clean($value['backgroundStoredName']??'',255);if($stored===''||basename($stored)!==$stored)throw new InvalidArgumentException("Background stored name is invalid for $side.");
    $mime=strtolower(bbs_designer_clean($value['backgroundMimeType']??'',80));if(!in_array($mime,['image/jpeg','image/png','image/webp'],true))throw new InvalidArgumentException("Background MIME type is invalid for $side.");
    $fit=bbs_designer_clean($value['backgroundFit']??'Cover',20);if(!in_array($fit,['Contain','Cover','Stretch'],true))throw new InvalidArgumentException("Background fit is invalid for $side.");
    return['side'=>$side,'storageClass'=>$storage,'backgroundAssetId'=>array_key_exists('backgroundAssetId',$value)&&$value['backgroundAssetId']!==null?bbs_designer_int($value['backgroundAssetId'],1,PHP_INT_MAX,'Background asset'):null,'backgroundStoredName'=>$stored,'backgroundOriginalName'=>bbs_designer_clean($value['backgroundOriginalName']??$stored,255),'backgroundMimeType'=>$mime,'backgroundFileSize'=>bbs_designer_int($value['backgroundFileSize']??0,0,100*1024*1024,'Background file size'),'pixelWidth'=>array_key_exists('pixelWidth',$value)&&$value['pixelWidth']!==null?bbs_designer_int($value['pixelWidth'],1,100000,'Pixel width'):null,'pixelHeight'=>array_key_exists('pixelHeight',$value)&&$value['pixelHeight']!==null?bbs_designer_int($value['pixelHeight'],1,100000,'Pixel height'):null,'backgroundFit'=>$fit,'backgroundPositionXBP'=>bbs_designer_int($value['backgroundPositionXBP']??5000,0,10000,'Background X position'),'backgroundPositionYBP'=>bbs_designer_int($value['backgroundPositionYBP']??5000,0,10000,'Background Y position'),'bleedMM'=>bbs_designer_decimal($value['bleedMM']??0,0,20,'Bleed'),'safeMarginMM'=>bbs_designer_decimal($value['safeMarginMM']??3,0,50,'Safe margin')];
}
function bbs_designer_element(array $value,string $kind): array {
    $key=bbs_designer_clean($value['elementKey']??'',80);if(!preg_match('/^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$/',$key))throw new InvalidArgumentException('Element key is invalid.');
    $side=bbs_designer_clean($value['side']??'',10);$type=bbs_designer_clean($value['elementType']??'',30);if(!in_array($side,['Front','Back'],true))throw new InvalidArgumentException("Element $key has an invalid side.");if(!in_array($type,['DynamicText','StaticText','DynamicImage','StaticImage','QR','Shape'],true))throw new InvalidArgumentException("Element $key has an invalid type.");
    $source=bbs_designer_clean($value['dataSourceKey']??'',80)?:null;$dynamic=in_array($type,['DynamicText','DynamicImage','QR'],true);if($dynamic&&(!$source||!in_array($source,bbs_designer_fields($kind),true)))throw new InvalidArgumentException("Element $key uses a data source that is not allowed for $kind.");if(!$dynamic&&$source)throw new InvalidArgumentException("Element $key cannot use a dynamic data source.");if($type==='QR'&&!str_ends_with((string)$source,'_qr'))throw new InvalidArgumentException("Element $key must use an approved QR data source.");
    $x=bbs_designer_int($value['xBP']??null,0,9999,"$key X");$y=bbs_designer_int($value['yBP']??null,0,9999,"$key Y");$w=bbs_designer_int($value['widthBP']??null,1,10000,"$key width");$h=bbs_designer_int($value['heightBP']??null,1,10000,"$key height");if($x+$w>10000||$y+$h>10000)throw new InvalidArgumentException("Element $key must remain inside the card.");
    return['elementKey'=>$key,'side'=>$side,'elementType'=>$type,'dataSourceKey'=>$source,'staticText'=>$type==='StaticText'?bbs_designer_clean($value['staticText']??'',5000):null,'assetId'=>array_key_exists('assetId',$value)&&$value['assetId']!==null?bbs_designer_int($value['assetId'],1,PHP_INT_MAX,"$key asset"):null,'xBP'=>$x,'yBP'=>$y,'widthBP'=>$w,'heightBP'=>$h,'rotationDeg'=>bbs_designer_decimal($value['rotationDeg']??0,-360,360,"$key rotation"),'zIndex'=>bbs_designer_int($value['zIndex']??0,-10000,10000,"$key layer"),'visible'=>($value['visible']??true)===false?0:1,'locked'=>($value['locked']??false)===true?1:0,'required'=>($value['required']??false)===true?1:0,'style'=>bbs_designer_style($value['style']??[])];
}
function bbs_designer_normalize(array $payload,string $expectedKind): array {
    $kind=bbs_designer_kind($expectedKind);$width=bbs_designer_decimal($payload['widthMM']??null,20,500,'Card width');$height=bbs_designer_decimal($payload['heightMM']??null,20,500,'Card height');$dpi=bbs_designer_int($payload['dpi']??300,72,1200,'DPI');$flip=bbs_designer_clean($payload['duplexFlip']??'LongEdge',20);if(!in_array($flip,['LongEdge','ShortEdge'],true))throw new InvalidArgumentException('Duplex flip must be LongEdge or ShortEdge.');$rotation=bbs_designer_int($payload['backRotation']??0,0,180,'Back rotation');if(!in_array($rotation,[0,180],true))throw new InvalidArgumentException('Back rotation must be 0 or 180.');
    $sides=array_map('bbs_designer_side',is_array($payload['sides']??null)?$payload['sides']:[]);$sideNames=array_column($sides,'side');if(count($sides)<1||count($sides)>2||count(array_unique($sideNames))!==count($sides)||!in_array('Front',$sideNames,true))throw new InvalidArgumentException('A layout requires one Front side and may have one Back side.');
    $elements=[];foreach(is_array($payload['elements']??null)?$payload['elements']:[] as$item)$elements[]=bbs_designer_element((array)$item,$kind);if(count($elements)>200||count(array_unique(array_column($elements,'elementKey')))!==count($elements))throw new InvalidArgumentException('A layout may contain up to 200 uniquely keyed elements.');foreach($elements as$item)if(!in_array($item['side'],$sideNames,true))throw new InvalidArgumentException('Every element must belong to an available side.');
    return['templateKind'=>$kind,'widthMM'=>$width,'heightMM'=>$height,'dpi'=>$dpi,'duplexFlip'=>$flip,'backRotation'=>$rotation,'sides'=>$sides,'elements'=>$elements];
}
function bbs_designer_readiness(array $layout): array { $items=[];if(!in_array('Back',array_column($layout['sides'],'side'),true))$items[]=['severity'=>'Warning','code'=>'BACK_SIDE_MISSING','message'=>'Back side is not configured.'];if((int)$layout['dpi']<200)$items[]=['severity'=>'Warning','code'=>'DPI_LOW','message'=>'Print DPI is below the recommended 200 DPI.'];foreach($layout['sides'] as$side){$name=(string)$side['side'];if((float)($side['bleedMM']??0)<1)$items[]=['severity'=>'Warning','code'=>'BLEED_LOW_'.strtoupper($name),'message'=>"$name bleed is below the recommended 1 mm."];if((float)($side['safeMarginMM']??0)<2)$items[]=['severity'=>'Warning','code'=>'SAFE_MARGIN_LOW_'.strtoupper($name),'message'=>"$name safe margin is below the recommended 2 mm."];if(!empty($side['pixelWidth'])&&!empty($side['pixelHeight'])){$requiredWidth=((float)$layout['widthMM']/25.4)*(int)$layout['dpi'];$requiredHeight=((float)$layout['heightMM']/25.4)*(int)$layout['dpi'];if((int)$side['pixelWidth']<$requiredWidth||(int)$side['pixelHeight']<$requiredHeight)$items[]=['severity'=>'Warning','code'=>'BACKGROUND_RESOLUTION_LOW_'.strtoupper($name),'message'=>"$name background may be below the selected print DPI."];}}$expected=$layout['templateKind']==='Personal'?'card.personal_qr':'department.community_qr';$qr=array_values(array_filter($layout['elements'],fn($e)=>!empty($e['visible'])&&$e['elementType']==='QR'&&$e['dataSourceKey']===$expected));if(!$qr)$items[]=['severity'=>'Blocked','code'=>'QR_MISSING','message'=>'An approved BBS QR element is required.'];foreach($qr as$item)if(min($item['widthBP'],$item['heightBP'])<1200){$items[]=['severity'=>'Blocked','code'=>'QR_TOO_SMALL','message'=>'QR size must be at least 12% of the card on both axes.'];break;}$blocked=(bool)array_filter($items,fn($i)=>$i['severity']==='Blocked');$warning=(bool)array_filter($items,fn($i)=>$i['severity']==='Warning');return['status'=>$blocked?'Blocked':($warning?'Warning':'Ready'),'items'=>$items]; }
