<?php
declare(strict_types=1);

const BBS_CARD_ARTWORK_ROLE_GLOBAL_BACK = 'GlobalBack';
const BBS_CARD_ARTWORK_ROLE_SCOPED_FRONT = 'ScopedFront';

function bbs_card_artwork_positive_int($value): ?int { $number=filter_var($value,FILTER_VALIDATE_INT);return$number!==false&&$number>0?(int)$number:null; }
function bbs_card_artwork_kind($value): string { $kind=ucfirst(strtolower(trim((string)$value)));if(!in_array($kind,['Personal','Department'],true))throw new InvalidArgumentException('Card artwork kind must be Personal or Department.');return$kind; }
function bbs_card_artwork_global_back_key(): string { return'BACK:GLOBAL'; }
function bbs_card_artwork_scoped_front_key($kindValue,$departmentValue,$unitValue=null): string { $kind=bbs_card_artwork_kind($kindValue);$departmentId=bbs_card_artwork_positive_int($departmentValue);$unitId=bbs_card_artwork_positive_int($unitValue);if(!$departmentId)throw new InvalidArgumentException('Scoped Front Artwork requires a Department.');return'FRONT:'.$kind.':D'.$departmentId.($unitId?':U'.$unitId:''); }
function bbs_card_artwork_candidate_keys(array $context): array { $departmentId=bbs_card_artwork_positive_int($context['departmentId']??null);$unitId=bbs_card_artwork_positive_int($context['safetyUnitId']??null);if(!$departmentId)throw new InvalidArgumentException('Card artwork resolution requires a Department.');$front=[];if($unitId)$front[]=bbs_card_artwork_scoped_front_key($context['kind']??'',$departmentId,$unitId);$front[]=bbs_card_artwork_scoped_front_key($context['kind']??'',$departmentId);return['front'=>$front,'back'=>[bbs_card_artwork_global_back_key()]]; }
function bbs_card_artwork_select(array $rows,array $context): array { $candidates=bbs_card_artwork_candidate_keys($context);$byKey=[];foreach($rows as$row)if((string)($row['Status']??$row['status']??'')==='Active')$byKey[(string)($row['SlotKey']??$row['slotKey']??'')]=$row;$front=null;foreach($candidates['front']as$key)if(isset($byKey[$key])){$front=$byKey[$key];break;}$back=$byKey[$candidates['back'][0]]??null;$missing=[];if(!$front)$missing[]='Front';if(!$back)$missing[]='Back';return['front'=>$front,'back'=>$back,'candidates'=>$candidates,'missing'=>$missing]; }
function bbs_card_artwork_validate_unit_department(PDO $pdo,$departmentValue,$unitValue): array { $departmentId=bbs_card_artwork_positive_int($departmentValue);$unitId=bbs_card_artwork_positive_int($unitValue);if(!$departmentId)throw new InvalidArgumentException('Department is required.');$stmt=$pdo->prepare("SELECT id FROM master_departments WHERE id=? AND Status='Active'");$stmt->execute([$departmentId]);if(!$stmt->fetch())throw new InvalidArgumentException('Selected Department is not active.');if(!$unitId)return['departmentId'=>$departmentId,'safetyUnitId'=>null];$stmt=$pdo->prepare('SELECT id FROM master_safetyunits WHERE id=? AND department_id=?');$stmt->execute([$unitId,$departmentId]);if(!$stmt->fetch())throw new InvalidArgumentException('Safety Unit does not belong to the selected Department.');return['departmentId'=>$departmentId,'safetyUnitId'=>$unitId]; }
function bbs_card_artwork_resolve(PDO $pdo,array $context,bool $lock=false): array { $keys=bbs_card_artwork_candidate_keys($context);$all=array_merge($keys['front'],$keys['back']);$marks=implode(',',array_fill(0,count($all),'?'));$sql="SELECT s.id ArtworkSlotID,s.SlotKey,s.ArtworkRole,s.TemplateKind,s.DepartmentID,s.SafetyUnitID,v.id ArtworkVersionID,v.VersionNo,v.StoredName,v.OriginalName,v.MimeType,v.FileSize,v.PixelWidth,v.PixelHeight,v.Status FROM BBS_Card_Artwork_Slots s JOIN BBS_Card_Artwork_Versions v ON v.ArtworkSlotID=s.id AND v.Status='Active' WHERE s.IsActive=1 AND s.SlotKey IN ($marks)".($lock?' FOR UPDATE':'');$stmt=$pdo->prepare($sql);$stmt->execute($all);return bbs_card_artwork_select($stmt->fetchAll(),$context); }
function bbs_card_artwork_materialize_legacy(PDO $pdo,array $context,string $targetDir): array { $resolved=bbs_card_artwork_resolve($pdo,$context);$kind=bbs_card_artwork_kind($context['kind']??'');if(!$resolved['front'])throw new InvalidArgumentException("Active $kind Scoped Front Artwork is required when no Legacy fallback file is uploaded.");$artwork=$resolved['front'];$mime=(string)($artwork['MimeType']??'');$extensions=['image/jpeg'=>'.jpg','image/png'=>'.png','image/webp'=>'.webp'];if(!isset($extensions[$mime]))throw new InvalidArgumentException('Resolved Scoped Front Artwork is not a supported image.');$sourceDir=dirname(__DIR__,2).'/backend/private-uploads/bbs-card-master-artwork';$source=$sourceDir.'/'.basename((string)($artwork['StoredName']??''));if(!is_file($source)||bbs_card_file_mime($source)!==$mime)throw new InvalidArgumentException('Resolved Scoped Front Artwork file is unavailable or invalid.');if(!is_dir($targetDir)&&!mkdir($targetDir,0770,true)&&!is_dir($targetDir))throw new RuntimeException('Unable to prepare Legacy fallback storage.');$stored=time().'-'.bin2hex(random_bytes(18)).$extensions[$mime];$target=rtrim($targetDir,'/\\').'/'.$stored;if(!copy($source,$target))throw new RuntimeException('Unable to create Legacy fallback from Scoped Front Artwork.');return['stored'=>$stored,'target'=>$target,'name'=>mb_substr((string)($artwork['OriginalName']??'Scoped Front Artwork'),0,255),'mime'=>$mime,'size'=>(int)($artwork['FileSize']??filesize($target)),'source'=>'CardArtwork','artworkVersionId'=>(int)$artwork['ArtworkVersionID']]; }
