<?php
declare(strict_types=1);

const SVPL_CONTRACT = '2026-10-10-safety-vote-ux-phase9b-r1';
const SVPL_REVIEW_CONTRACT = '2026-10-10-safety-vote-admin-review-r1';

function svpl_clean($value, int $max=255):string {
    $text=preg_replace('/[\x00-\x1F\x7F]/u',' ',(string)($value??''));
    $text=preg_replace('/\s+/u',' ',$text??'');
    return mb_substr(trim($text),0,$max);
}
function svpl_int($value):?int {$number=(int)$value;return $number>0?$number:null;}
function svpl_hash($value):string {return hash('sha256',is_string($value)?$value:json_encode($value,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));}
function svpl_saved_view(array $input):array {
    $name=svpl_clean($input['name']??$input['ViewName']??'',100);$allowed=['search','status','campaignType','owner','sort','month'];$sorts=['updated_desc','title_asc','status_asc','open_asc'];$filters=[];
    foreach(is_array($input['filters']??null)?$input['filters']:[]as$key=>$value){if(!in_array($key,$allowed,true))continue;if($key==='sort')$filters[$key]=in_array((string)$value,$sorts,true)?(string)$value:'updated_desc';elseif($key==='status'){$values=is_array($value)?$value:[$value];$filters[$key]=array_slice(array_values(array_filter(array_map(fn($x)=>svpl_clean($x,32),$values))),0,10);}else$filters[$key]=svpl_clean($value,$key==='search'?120:50);}
    return['ok'=>$name!=='','errors'=>$name!==''?[]:[['field'=>'name','code'=>'REQUIRED']],'value'=>['name'=>$name,'filters'=>$filters,'isDefault'=>($input['isDefault']??false)===true]];
}
function svpl_template_name(array $input):array {$name=svpl_clean($input['name']??$input['TemplateName']??'',120);return['ok'=>$name!=='','errors'=>$name!==''?[]:[['field'=>'name','code'=>'REQUIRED']],'value'=>['name'=>$name]];}
function svpl_safe_template(array $raw):array {
    $v=is_array($raw['version']??null)?$raw['version']:[];$questions=[];$rules=[];
    foreach(array_slice(is_array($raw['questions']??null)?$raw['questions']:[],0,50)as$qi=>$q){$options=[];foreach(array_slice(is_array($q['options']??null)?$q['options']:[],0,200)as$oi=>$o)$options[]=['optionCode'=>svpl_clean($o['optionCode']??'O'.($oi+1),50),'label'=>svpl_clean($o['label']??'',300),'description'=>svpl_clean($o['description']??'',2000)?:null,'scoreValue'=>isset($o['scoreValue'])?(float)$o['scoreValue']:null,'isAbstain'=>(bool)($o['isAbstain']??false),'fileId'=>null,'media'=>[],'sortOrder'=>$oi+1];$questions[]=['questionCode'=>svpl_clean($q['questionCode']??'Q'.($qi+1),50),'questionType'=>svpl_clean($q['questionType']??'single_choice',32),'title'=>svpl_clean($q['title']??'',300),'helpText'=>svpl_clean($q['helpText']??'',1000)?:null,'isRequired'=>(bool)($q['isRequired']??false),'minSelections'=>max(0,(int)($q['minSelections']??0)),'maxSelections'=>max(0,(int)($q['maxSelections']??0)),'randomizeOptions'=>(bool)($q['randomizeOptions']??false),'allowComment'=>(bool)($q['allowComment']??false),'validation'=>is_array($q['validation']??null)?$q['validation']:[],'displayCondition'=>is_array($q['displayCondition']??null)?$q['displayCondition']:null,'resultVisibility'=>svpl_clean($q['resultVisibility']??'aggregate',30),'sortOrder'=>$qi+1,'options'=>$options];}
    foreach(array_slice(is_array($raw['rules']??null)?$raw['rules']:[],0,100)as$rule){$attribute=strtolower((string)($rule['attributeKey']??''));if(in_array($attribute,['employee','employee_id','employeeid'],true))continue;$rules[]=['ruleGroup'=>max(1,(int)($rule['ruleGroup']??1)),'ruleOrder'=>count($rules)+1,'effect'=>svpl_clean($rule['effect']??'include',12),'attributeKey'=>svpl_clean($rule['attributeKey']??'',40),'operator'=>svpl_clean($rule['operator']??'IN',20),'values'=>array_slice(array_map(fn($x)=>svpl_clean($x,100),is_array($rule['values']??null)?$rule['values']:[]),0,100),'reason'=>svpl_clean($rule['reason']??'',255)?:null];}
    return['version'=>['campaignType'=>svpl_clean($v['campaignType']??'',40),'privacyMode'=>svpl_clean($v['privacyMode']??'',24),'titleTh'=>svpl_clean($v['titleTh']??'',200),'titleEn'=>svpl_clean($v['titleEn']??'',200)?:null,'summary'=>svpl_clean($v['summary']??'',500)?:null,'description'=>svpl_clean($v['description']??'',10000)?:null,'rulesText'=>svpl_clean($v['rulesText']??'',10000)?:null,'timeZone'=>svpl_clean($v['timeZone']??'Asia/Bangkok',50),'resultVisibility'=>svpl_clean($v['resultVisibility']??'hidden_until_close',24),'editPolicy'=>svpl_clean($v['editPolicy']??'none',24),'scoringMethod'=>svpl_clean($v['scoringMethod']??'raw_count',40),'privacyThreshold'=>max(2,min(100,(int)($v['privacyThreshold']??5))),'allowAbstain'=>(bool)($v['allowAbstain']??false),'randomizeOptions'=>(bool)($v['randomizeOptions']??false),'discoveryMode'=>svpl_clean($v['discoveryMode']??'eligible_only',24)],'questions'=>$questions,'rules'=>$rules];
}
function svpl_notification_preview(array $input):array {
    $campaign=svpl_int($input['campaignId']??null);$audience=in_array($input['audience']??'', ['eligible','nonparticipants'],true)?(string)$input['audience']:null;$channel=in_array($input['channel']??'', ['in_app','email'],true)?(string)$input['channel']:null;$event=svpl_clean($input['eventType']??'announcement',50);$template=svpl_clean($input['templateKey']??'admin_composer',80);$title=svpl_clean($input['title']??'',160);$message=svpl_clean($input['message']??'',300);$scheduled=svpl_clean($input['scheduledAt']??'',32);$matched=preg_match('/^(\d{4}-\d{2}-\d{2})[T ](\d{2}):(\d{2})/',$scheduled,$m)===1;$hour=$matched?(int)$m[2]:null;$errors=[];if(!$campaign)$errors[]=['field'=>'campaignId','code'=>'REQUIRED'];if(!$audience)$errors[]=['field'=>'audience','code'=>'INVALID_ENUM'];if(!$channel)$errors[]=['field'=>'channel','code'=>'INVALID_ENUM'];if(!$matched)$errors[]=['field'=>'scheduledAt','code'=>'INVALID_DATE'];if($title==='')$errors[]=['field'=>'title','code'=>'REQUIRED'];if($message==='')$errors[]=['field'=>'message','code'=>'REQUIRED'];return['ok'=>count($errors)===0,'errors'=>$errors,'value'=>['campaignId'=>$campaign,'audience'=>$audience,'channel'=>$channel,'eventType'=>$event,'templateKey'=>$template,'title'=>$title,'message'=>$message,'scheduledAt'=>$scheduled,'quietHoursBlocked'=>$hour!==null&&($hour>=21||$hour<7),'windowKey'=>$matched?$m[1]:null]];
}

function svpl_review_note(array $input):array {
    $allowed=['general','readiness','schedule','content','governance'];$forbidden=null;
    foreach(array_keys($input)as$key)if(preg_match('/ballot|answer|choice|candidate|voter|receipt|jury.?score|response.?identity/i',(string)$key)){$forbidden=(string)$key;break;}
    $note=svpl_clean($input['note']??'',800);$category=in_array((string)($input['category']??'general'),$allowed,true)?(string)($input['category']??'general'):null;$errors=[];
    if($note==='')$errors[]=['field'=>'note','code'=>'REQUIRED'];if($category===null)$errors[]=['field'=>'category','code'=>'INVALID_ENUM'];
    if($forbidden!==null||preg_match('/ballot\s*id|voter.{0,20}choice|jury\s*score|receipt\s*id|รหัสบัตรลงคะแนน|คำตอบของผู้ใช้|ตัวเลือกที่ลงคะแนน|คะแนนกรรมการรายบุคคล/iu',$note))$errors[]=['field'=>$forbidden??'note','code'=>'BALLOT_DATA_NOT_ALLOWED'];
    return['ok'=>count($errors)===0,'errors'=>$errors,'value'=>['note'=>$note,'category'=>$category]];
}
function svpl_review_readiness(array $row):array {
    $open=!empty($row['ScheduledOpenAt'])?strtotime((string)$row['ScheduledOpenAt']):false;$close=!empty($row['ScheduledCloseAt'])?strtotime((string)$row['ScheduledCloseAt']):false;
    $checks=[['key'=>'owner','label'=>'ระบุผู้รับผิดชอบ','passed'=>svpl_clean($row['OwnerEmployeeID']??'',20)!==''],['key'=>'content','label'=>'มีคำถามหรือเนื้อหาที่ใช้งาน','passed'=>(int)($row['QuestionCount']??0)>0],['key'=>'eligibility','label'=>'มีกฎผู้มีสิทธิ์','passed'=>(int)($row['EligibilityRuleCount']??0)>0],['key'=>'schedule','label'=>'กำหนดเวลาเปิดและปิดถูกต้อง','passed'=>$open!==false&&$close!==false&&$close>$open]];
    $passed=count(array_filter($checks,fn($x)=>$x['passed']));return['passed'=>$passed,'total'=>count($checks),'percent'=>(int)round($passed/count($checks)*100),'blockers'=>array_values(array_filter($checks,fn($x)=>!$x['passed'])),'authoritative'=>false];
}
function svpl_schedule_conflicts(array $rows):array {$groups=[];$result=[];foreach($rows as$row){$key=(int)$row['CampaignID'].':'.svpl_clean($row['Channel']??'',30);$groups[$key][]=$row;}foreach($groups as$group){usort($group,fn($a,$b)=>strtotime((string)$a['ScheduledAt'])<=>strtotime((string)$b['ScheduledAt']));for($i=1;$i<count($group);$i++){if(abs(strtotime((string)$group[$i]['ScheduledAt'])-strtotime((string)$group[$i-1]['ScheduledAt']))<=1800){$id=(int)$group[$i]['CampaignID'];$result[$id]=($result[$id]??0)+1;}}}return$result;}
