<?php
declare(strict_types=1);
const SAFETY_VOTE_PHASE2_CONTRACT='2026-10-08-safety-vote-phase2-r1';
const SV2_QUESTION_TYPES=['single_choice','multiple_choice'];
function sv2_text($v,int$n=300):string{$v=preg_replace('/[\x00-\x1F\x7F]/u',' ',(string)($v??''));return mb_substr(preg_replace('/\s+/u',' ',trim((string)$v)),0,$n);}
function sv2_int($v):?int{$n=filter_var($v,FILTER_VALIDATE_INT);return$n!==false&&$n>0?(int)$n:null;}
function sv2_question(array$in,int$i=0):array{$type=strtolower(sv2_text($in['questionType']??$in['QuestionType']??'',32));$title=sv2_text($in['title']??$in['Title']??'',300);$min=(int)($in['minSelections']??$in['MinSelections']??1);$max=(int)($in['maxSelections']??$in['MaxSelections']??1);$errors=[];if(!in_array($type,SV2_QUESTION_TYPES,true))$errors[]='INVALID_TYPE';if($title==='')$errors[]='TITLE_REQUIRED';if($min<0||$max<1||$min>$max||($type==='single_choice'&&($min>1||$max!==1)))$errors[]='INVALID_SELECTION_LIMIT';return['ok'=>!$errors,'errors'=>$errors,'value'=>['id'=>sv2_int($in['id']??null),'questionCode'=>strtoupper(sv2_text($in['questionCode']??$in['QuestionCode']??'Q'.($i+1),50)),'questionType'=>$type,'title'=>$title,'helpText'=>sv2_text($in['helpText']??$in['HelpText']??'',1000)?:null,'isRequired'=>(bool)($in['isRequired']??$in['IsRequired']??true),'minSelections'=>$min,'maxSelections'=>$max,'sortOrder'=>sv2_int($in['sortOrder']??$in['SortOrder']??null)??$i+1,'options'=>is_array($in['options']??null)?$in['options']:[]]];}
function sv2_builder($input):array{if(!is_array($input)||!$input||count($input)>20)return['ok'=>false,'errors'=>[['index'=>-1,'codes'=>['QUESTION_ARRAY_REQUIRED']]],'questions'=>[]];$questions=[];$errors=[];foreach(array_values($input)as$i=>$raw){$q=sv2_question(is_array($raw)?$raw:[],$i);if(!$q['ok'])$errors[]=['index'=>$i,'codes'=>$q['errors']];$opts=[];foreach(array_values($q['value']['options'])as$j=>$o)$opts[]=['id'=>sv2_int($o['id']??null),'optionCode'=>strtoupper(sv2_text($o['optionCode']??$o['OptionCode']??'O'.($j+1),50)),'label'=>sv2_text($o['label']??$o['Label']??'',300),'description'=>sv2_text($o['description']??$o['Description']??'',2000)?:null,'fileId'=>sv2_int($o['fileId']??$o['FileID']??null),'sortOrder'=>sv2_int($o['sortOrder']??$o['SortOrder']??null)??$j+1];if(count($opts)<2||count($opts)>100||array_filter($opts,fn($o)=>$o['label']===''))$errors[]=['index'=>$i,'codes'=>['OPTIONS_INVALID']];$q['value']['options']=$opts;$questions[]=$q['value'];}return['ok'=>!$errors,'errors'=>$errors,'questions'=>$questions];}
function sv2_answers(array$questions,$answers):array{if(!is_array($answers))return['ok'=>false,'errors'=>['ANSWERS_REQUIRED'],'answers'=>[]];$by=[];foreach($questions as$q)$by[(int)$q['id']]=$q;$seen=[];$out=[];$errors=[];foreach($answers as$raw){$qid=sv2_int($raw['questionId']??null);if(!$qid||!isset($by[$qid])||isset($seen[$qid])){$errors[]='QUESTION_INVALID';continue;}$seen[$qid]=true;$q=$by[$qid];$ids=array_values(array_unique(array_filter(array_map('sv2_int',is_array($raw['optionIds']??null)?$raw['optionIds']:[]))));$allowed=array_map(fn($o)=>(int)$o['id'],$q['options']);if(array_diff($ids,$allowed)||count($ids)<(int)$q['minSelections']||count($ids)>(int)$q['maxSelections'])$errors[]='SELECTION_INVALID';else$out[]=['questionId'=>$qid,'optionIds'=>$ids];}foreach($questions as$q)if($q['isRequired']&&!isset($seen[(int)$q['id']]))$errors[]='REQUIRED_ANSWER_MISSING';return['ok'=>!$errors,'errors'=>array_values(array_unique($errors)),'answers'=>$out];}
function sv2_sort($v){if(!is_array($v))return$v;if(array_keys($v)!==range(0,count($v)-1))ksort($v);foreach($v as$k=>$x)$v[$k]=sv2_sort($x);return$v;}
function sv2_hash($v):string{return hash('sha256',json_encode(sv2_sort($v),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));}
function sv2_rows_hash(array$rows):string{$out=[];foreach($rows as$r)$out[]=['employeeId'=>(string)$r['employeeId'],'departmentId'=>$r['departmentId']??null,'safetyUnitId'=>$r['safetyUnitId']??null,'positionId'=>$r['positionId']??null,'role'=>$r['role']??'','team'=>$r['team']??'','accountReady'=>(bool)$r['accountReady']];usort($out,fn($a,$b)=>strcmp($a['employeeId'],$b['employeeId']));return sv2_hash($out);}
function sv2_transition(string$from,string$to):bool{$map=['Draft'=>['Open'],'Open'=>['Closed'],'Closed'=>['Published'],'Published'=>[]];return in_array($to,$map[$from]??[],true);}
