<?php
declare(strict_types=1);
const SV6_CONTRACT='2026-10-08-safety-vote-phase6-r1';
function sv6_hash($v):string{return hash('sha256',json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));}
function sv6_int($v,int$d=0):int{return is_numeric($v)&&(int)$v==(float)$v?(int)$v:$d;}
function sv6_config($raw):array{$raw=is_array($raw)?$raw:[];$errors=[];$seen=[];$questions=[];$out=[];foreach(array_values(is_array($raw['positions']??null)?$raw['positions']:[])as$i=>$p){$code=strtoupper(substr(trim((string)($p['positionCode']??'')),0,50));$qid=sv6_int($p['questionId']??0);$seats=max(1,min(100,sv6_int($p['seatCount']??null,1)));$max=max(1,min(100,sv6_int($p['maxSelections']??null,$seats)));$ids=array_values(array_unique(array_map('intval',array_filter($p['candidateIds']??[],fn($x)=>is_numeric($x)))));sort($ids);$tie=in_array($p['tieRule']??'',['unresolved','candidate_id'],true)?$p['tieRule']:'unresolved';if(!$code||!$qid||isset($seen[$code])||isset($questions[$qid])||!trim((string)($p['title']??''))||$max>$seats||count($ids)<$seats)$errors[]='POSITION_INVALID';$seen[$code]=1;$questions[$qid]=1;$out[]=['positionCode'=>$code,'questionId'=>$qid,'title'=>substr(trim((string)($p['title']??'')),0,300),'seatCount'=>$seats,'maxSelections'=>$max,'allowAbstain'=>($p['allowAbstain']??true)!==false,'tieRule'=>$tie,'sortOrder'=>sv6_int($p['sortOrder']??null,$i+1),'candidateIds'=>$ids];}usort($out,fn($a,$b)=>$a['sortOrder']<=>$b['sortOrder']?:strcmp($a['positionCode'],$b['positionCode']));if(!$out)$errors[]='POSITIONS_REQUIRED';return['ok'=>!$errors,'errors'=>array_values(array_unique($errors)),'positions'=>$out,'configHash'=>sv6_hash($out)];}
function sv6_receipt($code):array{return['receipt'=>(string)$code,'receiptHash'=>sv6_hash((string)$code),'proof'=>'accepted_only','canLocateBallot'=>false];}
function sv6_calculate(array$in):array{$cfg=sv6_config(['positions'=>$in['positions']??[]]);$counts=[];foreach($in['counts']??[]as$x)$counts[($x['positionCode']??'').':'.((int)($x['candidateId']??0)).':'.(!empty($x['abstain'])?1:0)]=max(0,sv6_int($x['count']??0));$eligible=max(0,sv6_int($in['eligibleCount']??0));$participation=max(0,sv6_int($in['participationCount']??0));$accepted=max(0,sv6_int($in['acceptedBallotCount']??0));$errors=$cfg['errors'];if($participation>$eligible||$accepted!==$participation)$errors[]='RECONCILIATION_FAILED';$rows=[];$ties=[];foreach($cfg['positions']as$p){$ranked=[];foreach($p['candidateIds']as$id)$ranked[]=['positionCode'=>$p['positionCode'],'candidateId'=>$id,'count'=>$counts[$p['positionCode'].':'.$id.':0']??0];usort($ranked,fn($a,$b)=>$b['count']<=>$a['count']?:$a['candidateId']<=>$b['candidateId']);$cut=$ranked[$p['seatCount']-1]['count']??null;$same=$cut===null?0:count(array_filter($ranked,fn($x)=>$x['count']===$cut));$outside=false;foreach($ranked as$i=>$x)if($i>=$p['seatCount']&&$x['count']===$cut)$outside=true;$tied=$same>1&&$outside;if($tied&&$p['tieRule']==='unresolved')$ties[]=$p['positionCode'];foreach($ranked as$i=>$x)$rows[]=$x+['rank'=>$i+1,'resultState'=>$tied&&$p['tieRule']==='unresolved'&&$x['count']===$cut?'tied':($i<$p['seatCount']?'elected':'not_elected')];$rows[]=['positionCode'=>$p['positionCode'],'candidateId'=>null,'count'=>$counts[$p['positionCode'].':0:1']??0,'rank'=>null,'resultState'=>'abstain'];}$tie=$ties?'unresolved':'none';$recon=$errors?'failed':'balanced';$abstain=0;foreach($rows as$x)if($x['resultState']==='abstain')$abstain+=(int)$x['count'];$payload=['contract'=>SV6_CONTRACT,'configHash'=>$cfg['configHash'],'eligibleCount'=>$eligible,'participationCount'=>$participation,'acceptedBallotCount'=>$accepted,'abstainCount'=>$abstain,'reconciliationState'=>$recon,'tieState'=>$tie,'tiedPositions'=>$ties,'rows'=>$rows];$sorted=$counts;ksort($sorted);return['ok'=>!$errors&&$tie==='none','errors'=>array_values(array_unique($errors))]+$payload+['inputHash'=>sv6_hash(['positions'=>$cfg['positions'],'counts'=>$sorted]),'resultHash'=>sv6_hash($payload)];}
function sv6_certification(array$in):array{$required=max(2,sv6_int($in['required']??2,2));$people=[];foreach($in['certifications']??[]as$x)if(($x['decision']??'')==='certified'&&empty($x['revokedAt'])&&($x['resultHash']??'')===($in['resultHash']??''))$people[(string)$x['employeeId']]=1;return['required'=>$required,'activeCount'=>count($people),'ready'=>count($people)>=$required,'resultHash'=>$in['resultHash']??''];}
function sv6_audit_metadata($raw):array{$out=[];foreach(['resultHash','inputHash','snapshotNo','actionType','reasonCode','reportId','contentSha256']as$k)if(isset($raw[$k])&&(is_string($raw[$k])||is_numeric($raw[$k])))$out[$k]=$raw[$k];return$out;}
