<?php
declare(strict_types=1);
const SV5_CONTRACT='2026-10-08-safety-vote-phase5-r1';
function sv5_hash($v):string{return hash('sha256',is_string($v)?$v:json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));}
function sv5_suppress($value,$threshold,string$mode='identified',$dimension=null):array{$count=max(0,(int)$value);$limit=max(1,(int)$threshold);$private=in_array($mode,['anonymous','secret_ballot','confidential'],true);if($mode==='secret_ballot'&&$dimension)return['visible'=>false,'suppressed'=>true,'reason'=>'SECRET_DIMENSION_FORBIDDEN','value'=>null];if($private&&$count<$limit)return['visible'=>false,'suppressed'=>true,'reason'=>'PRIVACY_THRESHOLD','value'=>null];return['visible'=>true,'suppressed'=>false,'reason'=>null,'value'=>$count];}
function sv5_metric(string$key,int$value,int$base,int$threshold,string$mode):array{return['key'=>$key]+sv5_suppress($value,$threshold,$mode)+['percentage'=>$base>0?round($value/$base*100,2):null];}
function sv5_funnel(array$i):array{$e=max(0,(int)($i['eligible']??0));$s=max(0,(int)($i['started']??0));$u=max(0,(int)($i['submitted']??0));$a=max(0,(int)($i['accepted']??0));$t=$i['threshold']??5;$m=(string)($i['privacyMode']??'identified');return['contract'=>SV5_CONTRACT,'eligible'=>sv5_metric('eligible',$e,$e,$t,$m),'started'=>sv5_metric('started',$s,$e,$t,$m),'submitted'=>sv5_metric('submitted',$u,$e,$t,$m),'accepted'=>sv5_metric('accepted',$a,$e,$t,$m),'reconciliation'=>$a<=$u&&$u<=max($e,$u)?'balanced':'mismatch'];}
function sv5_schedule(array$i):string{$t=strtotime((string)$i['now']);$o=!empty($i['openAt'])?strtotime((string)$i['openAt']):false;$c=!empty($i['closeAt'])?strtotime((string)$i['closeAt']):false;if($i['status']==='Draft'&&$o!==false&&$t>=$o&&($c===false||$t<$c))return'open';if($i['status']==='Open'&&$c!==false&&$t>=$c)return'close';return'none';}
function sv5_notification_key(array$i):string{return sv5_hash([(int)$i['campaignId'],!empty($i['stageId'])?(int)$i['stageId']:null,(string)$i['eventType'],(string)$i['channel'],(string)$i['recipientEmployeeId'],(string)($i['windowKey']??'')]);}
function sv5_safe_metadata($raw):array{$out=[];foreach(is_array($raw)?$raw:[]as$k=>$v)if(!preg_match('/answer|choice|selection|free.?text|token|password|secret|ballot.?id/i',(string)$k)&&(is_string($v)||is_numeric($v)||is_bool($v)))$out[substr((string)$k,0,60)]=is_string($v)?substr($v,0,300):$v;return$out;}
function sv5_report_model(array$i):array{$rows=[];foreach($i['rows']??[]as$x)$rows[]=['rank'=>isset($x['rank'])?(int)$x['rank']:null,'label'=>(string)($x['label']??''),'metric'=>(string)($x['metric']??''),'value'=>isset($x['value'])?(float)$x['value']:null,'state'=>(string)($x['state']??'normal')];$m=['contract'=>SV5_CONTRACT,'reportId'=>(string)$i['reportId'],'campaignCode'=>(string)$i['campaignCode'],'title'=>(string)$i['title'],'snapshotNo'=>(int)$i['snapshotNo'],'resultHash'=>(string)$i['resultHash'],'generatedAt'=>(string)$i['generatedAt'],'rows'=>$rows];return['model'=>$m,'canonical'=>json_encode($m,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'modelHash'=>sv5_hash($m)];}
function sv5_retention(array$rows,int$days=2555,string$now='now'):array{$cut=(new DateTimeImmutable($now))->modify('-'.max(30,$days).' days');$ids=[];foreach($rows as$x)if(new DateTimeImmutable($x['createdAt'])<$cut&&!in_array((string)$x['status'],['Published','Certified','Ready'],true))$ids[]=(int)$x['id'];sort($ids);return['mode'=>'dry-run','cutoff'=>$cut->format('Y-m-d\TH:i:s.000\Z'),'candidateIds'=>$ids,'count'=>count($ids),'requiresApply'=>true,'confirmation'=>'SAFETY_VOTE_RETENTION_APPLY'];}
