<?php
declare(strict_types=1);
const SV7_CONTRACT='2026-10-08-safety-vote-phase7-r1';
const SV7_GOVERNANCE_CONTRACT='2026-10-08-safety-vote-phase8.1-she-governance-r1';
const SV7_TARGETS=['committee','hiyari','ky','bbs','patrol','training','policy','dashboard','johnny','calendar','notification'];
const SV7_ACCEPTANCE=['she_owner'];
function sv7_canonical($v){if(!is_array($v))return$v;if(array_keys($v)===range(0,count($v)-1))return array_map('sv7_canonical',$v);ksort($v);foreach($v as$k=>$x)$v[$k]=sv7_canonical($x);return$v;}
function sv7_hash($v):string{return hash('sha256',json_encode(sv7_canonical($v),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));}
function sv7_catalog():array{return array_map(fn($k)=>['key'=>$k,'mode'=>'read_only','explicitConfirmation'=>$k==='calendar'||$k==='notification'||$k!=='johnny','automaticMutation'=>false,'canVote'=>false,'canCertify'=>false,'canReadHiddenResults'=>false],SV7_TARGETS);}
function sv7_preview(array$in):array{$errors=[];$target=strtolower((string)($in['targetAdapter']??''));if(!in_array($target,SV7_TARGETS,true))$errors[]='TARGET_INVALID';if(!in_array($in['resultStatus']??'',['Certified','Published'],true))$errors[]='CERTIFIED_RESULT_REQUIRED';if(!preg_match('/^[a-f0-9]{64}$/i',(string)($in['resultHash']??'')))$errors[]='RESULT_HASH_INVALID';if(!empty($in['reportSha256'])&&!preg_match('/^[a-f0-9]{64}$/i',(string)$in['reportSha256']))$errors[]='REPORT_HASH_INVALID';$payload=['contract'=>SV7_CONTRACT,'targetAdapter'=>$target,'campaignCode'=>substr((string)($in['campaignCode']??''),0,80),'resultSnapshotId'=>(int)($in['resultSnapshotId']??0),'resultHash'=>(string)($in['resultHash']??''),'reportId'=>(string)($in['reportId']??''),'reportSha256'=>(string)($in['reportSha256']??''),'classification'=>'certified_aggregate','containsVoterIdentity'=>false,'containsBallotChoice'=>false,'externalMutation'=>false];$hash=sv7_hash($payload);return['ok'=>!$errors,'errors'=>$errors,'payload'=>$payload,'previewHash'=>$hash,'confirmation'=>'CONFIRM CERTIFIED HANDOFF '.strtoupper(substr($payload['resultHash'],0,12))];}
function sv7_confirm(array$in):array{$p=sv7_preview($in);$errors=$p['errors'];if(trim((string)($in['confirmation']??''))!==$p['confirmation'])$errors[]='CONFIRMATION_REQUIRED';if((string)($in['previewHash']??'')!==$p['previewHash'])$errors[]='PREVIEW_HASH_MISMATCH';$p['ok']=!$errors;$p['errors']=$errors;return$p;}
function sv7_verify(array$in):array{$checks=[];foreach($in as$k=>$x)$checks[]=['key'=>$k,'storedHash'=>(string)($x['storedHash']??''),'calculatedHash'=>(string)($x['calculatedHash']??''),'state'=>!empty($x['storedHash'])&&$x['storedHash']===$x['calculatedHash']?'pass':'fail'];$ready=!empty($checks)&&!array_filter($checks,fn($x)=>$x['state']!=='pass');return['checks'=>$checks,'ready'=>$ready,'verificationHash'=>sv7_hash($checks)];}
function sv7_preflight(array$in):array{$privacyMode=(string)($in['privacyMode']??'');$certifiedElection=(string)($in['campaignType']??'')==='secret_election'||$privacyMode==='secret_ballot';$separatedPrivacy=in_array($privacyMode,['anonymous','secret','secret_ballot'],true);$raw=[['schema',$in['schemaReady']??false,true],['adapter_mode',$in['fixtureOnly']??false,true],['identity_separation',!$separatedPrivacy||(int)($in['identityMappings']??0)===0,$separatedPrivacy],['dual_certification',!$certifiedElection||(int)($in['activeCertifiers']??0)>=2,$certifiedElection],['result_hash',$in['resultHashVerified']??false,true],['report_hash',$in['reportHashVerified']??false,true],['backup_restore',$in['backupRestorePassed']??false,true],['accessibility',$in['accessibilityPassed']??false,true],['performance',$in['performancePassed']??false,true],['load',$in['loadPassed']??false,true],['permission_matrix',$in['permissionMatrixReviewed']??false,true],['immutable_source',$in['immutableSource']??false,true]];$checks=array_map(fn($x)=>['key'=>$x[0],'state'=>$x[1]?'pass':'block','required'=>$x[2]],$raw);$accepted=array_map('strval',$in['acceptanceAreas']??[]);$missing=array_values(array_filter(SV7_ACCEPTANCE,fn($x)=>!in_array($x,$accepted,true)));$ready=!$missing&&!array_filter($checks,fn($x)=>$x['state']!=='pass');return['governanceContract'=>SV7_GOVERNANCE_CONTRACT,'governanceOwner'=>'SHE','certifiedElection'=>$certifiedElection,'separatedPrivacy'=>$separatedPrivacy,'requiredAcceptance'=>SV7_ACCEPTANCE,'checks'=>$checks,'missingAcceptance'=>$missing,'ready'=>$ready,'decision'=>$ready?'READY_FOR_SEPARATE_PRODUCTION_PREFLIGHT':'HOLD','preflightHash'=>sv7_hash(['governanceContract'=>SV7_GOVERNANCE_CONTRACT,'certifiedElection'=>$certifiedElection,'separatedPrivacy'=>$separatedPrivacy,'checks'=>$checks,'missingAcceptance'=>$missing])];}
function sv7_safe_metadata($raw):array{$out=[];foreach(['targetAdapter','previewHash','resultHash','reportId','reportSha256','providerReceipt','checkKey','evidenceHash','decision']as$k)if(isset($raw[$k])&&(is_string($raw[$k])||is_numeric($raw[$k])))$out[$k]=$raw[$k];return$out;}
