<?php
declare(strict_types=1);
const SAFETY_VOTE_PHASE104_CONTRACT='2026-10-09-safety-vote-phase10.4-r1';
function sv104_clean($value,int$max=1000):string{return mb_substr(trim((string)$value),0,$max);}
function sv104_media(array$input):array{
 $type=strtolower(sv104_clean($input['mediaType']??'',16));$scope=strtolower(sv104_clean($input['scopeType']??'',16));$title=sv104_clean($input['title']??'',200);$qc=strtoupper(sv104_clean($input['questionCode']??'',60));$oc=strtoupper(sv104_clean($input['optionCode']??'',60));$raw=sv104_clean($input['url']??'',1000);
 if(!in_array($type,['link','video'],true)||!in_array($scope,['campaign','question','option'],true))throw new InvalidArgumentException('MEDIA_TYPE_INVALID');
 if(($scope==='question'&&!$qc)||($scope==='option'&&(!$qc||!$oc)))throw new InvalidArgumentException('MEDIA_SCOPE_INVALID');
 $parts=parse_url($raw);if(!$parts||strtolower((string)($parts['scheme']??''))!=='https'||isset($parts['user'])||isset($parts['pass'])||(isset($parts['port'])&&(int)$parts['port']!==443))throw new InvalidArgumentException('MEDIA_URL_INVALID');
 $host=preg_replace('/^www\./','',strtolower((string)($parts['host']??'')));$provider='external';$embed=null;
 if($type==='video'){$vid='';$path=(string)($parts['path']??'');if($host==='youtu.be')$vid=explode('/',trim($path,'/'))[0]??'';elseif(in_array($host,['youtube.com','youtube-nocookie.com'],true)){if($path==='/watch'){parse_str((string)($parts['query']??''),$query);$vid=(string)($query['v']??'');}elseif(preg_match('#^/(?:embed|shorts)/([A-Za-z0-9_-]{11})#',$path,$m))$vid=$m[1];}if(preg_match('/^[A-Za-z0-9_-]{11}$/',$vid)){$provider='youtube';$embed='https://www.youtube-nocookie.com/embed/'.$vid;}elseif(in_array($host,['vimeo.com','player.vimeo.com'],true)&&preg_match('#(?:/video)?/(\d{6,12})(?:/|$)#',$path,$m)){$provider='vimeo';$embed='https://player.vimeo.com/video/'.$m[1];}if(!$embed)throw new InvalidArgumentException('VIDEO_PROVIDER_NOT_ALLOWED');}
 $canonical='https://'.($parts['host']??'').(isset($parts['port'])?':'.$parts['port']:'').($parts['path']??'').(isset($parts['query'])?'?'.$parts['query']:'');
 return['mediaType'=>$type,'scopeType'=>$scope,'questionCode'=>$qc?:null,'optionCode'=>$oc?:null,'title'=>$title?:null,'url'=>$canonical,'provider'=>$provider,'embedUrl'=>$embed];
}
function sv104_media_list($items):array{if(!is_array($items)||count($items)>100)return['ok'=>false,'errors'=>[['code'=>'MEDIA_LIST_INVALID']]];$rows=[];$errors=[];$seen=[];foreach($items as$i=>$item){try{$row=sv104_media(is_array($item)?$item:[]);$key=implode('|',[$row['scopeType'],$row['questionCode'],$row['optionCode'],$row['mediaType']]);if(isset($seen[$key]))throw new InvalidArgumentException('MEDIA_DUPLICATE');$seen[$key]=true;$row['sortOrder']=$i+1;$rows[]=$row;}catch(Throwable$e){$errors[]=['index'=>$i,'code'=>$e->getMessage()?:'MEDIA_INVALID'];}}return$errors?['ok'=>false,'errors'=>$errors]:['ok'=>true,'items'=>$rows];}
function sv104_policy(string$status,int$current,int$version):array{$live=$current===$version;$open=$status==='Open';return['campaignStatus'=>$status,'live'=>$live,'directEditAllowed'=>$status==='Draft'&&$live,'revisionEditAllowed'=>!$live,'createRevisionAllowed'=>!in_array($status,['Voided','Archived'],true),'activateRevisionAllowed'=>!$open&&!in_array($status,['Voided','Archived'],true),'policyCode'=>$open?'LIVE_CONTENT_IMMUTABLE_PREPARE_REVISION':($live?'DRAFT_DIRECT_EDIT':'OFFLINE_REVISION_EDIT'),'protectedWhileOpen'=>['questions','options','media','privacyMode','eligibility','schedule','scoring'],'safeOperationalMetadata'=>[]];}
