'use strict';

const express = require('express');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const multer = require('multer');
const db = require('../db');
const { createOnboardingResolver, ONBOARDING_STATUS } = require('../utils/onboarding-resolver');
const rules = require('../services/safety-vote-phase1');

const router = express.Router();
const privateDir = path.join(__dirname, '..', 'private-uploads', 'safety-vote');
fs.mkdirSync(privateDir, { recursive: true });
const REQUIRED_TABLES = ['SafetyVote_Settings','SafetyVote_Campaigns','SafetyVote_CampaignVersions','SafetyVote_Stages','SafetyVote_EligibilityRules','SafetyVote_EligibilitySnapshots','SafetyVote_EligibleVoters','SafetyVote_CampaignRoles','SafetyVote_Files','SafetyVote_AuditLogs','SafetyVote_Questions','SafetyVote_Options','SafetyVote_Candidates','SafetyVote_Participation','SafetyVote_Ballots','SafetyVote_BallotIdentities','SafetyVote_BallotAnswers','SafetyVote_RequestKeys','SafetyVote_Submissions','SafetyVote_Nominations','SafetyVote_JuryCriteria','SafetyVote_JuryAssignments','SafetyVote_JuryScores','SafetyVote_ResultSnapshots','SafetyVote_ResultRows','SafetyVote_Certifications','SafetyVote_StageAdvancements','SafetyVote_Reports','SafetyVote_ExportJobs','SafetyVote_Notifications','SafetyVote_NotificationDeliveries'];
const SCHEMA_VERSION = '2026-10-08-phase5-r1';
const PERMISSIONS = ['SAFETY_VOTE_VIEW','SAFETY_VOTE_CREATE','SAFETY_VOTE_MANAGE','SAFETY_VOTE_ELIGIBILITY_MANAGE','SAFETY_VOTE_SUBMISSION_REVIEW','SAFETY_VOTE_JURY','SAFETY_VOTE_RESULT_VIEW','SAFETY_VOTE_CERTIFY','SAFETY_VOTE_EXPORT','SAFETY_VOTE_AUDIT_VIEW','SAFETY_VOTE_ADMIN'];

const upload = multer({
    storage: multer.diskStorage({ destination: (_req,_file,cb)=>cb(null,privateDir), filename: (_req,file,cb)=>cb(null,`${Date.now()}-${crypto.randomBytes(18).toString('hex')}${({ 'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp','application/pdf':'.pdf' })[file.mimetype]||''}`) }),
    limits: { fileSize: 10*1024*1024, files: 1 },
    fileFilter: (_req,file,cb)=>cb(null,['image/jpeg','image/png','image/webp','application/pdf'].includes(file.mimetype)),
});

function actor(req){return String(req.user?.id||req.user?.EmployeeID||'').trim();}
function role(req){return String(req.user?.role||req.user?.Role||'').trim().toUpperCase();}
function removeFile(file){if(!file)return;fs.unlink(path.join(privateDir,path.basename(file)),()=>{});}
function verifiedMime(file){const head=fs.readFileSync(file).subarray(0,16),ascii=head.toString('ascii');if(head[0]===0xff&&head[1]===0xd8&&head[2]===0xff)return'image/jpeg';if(head.length>=8&&head.subarray(0,8).equals(Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a])))return'image/png';if(ascii.slice(0,4)==='RIFF'&&ascii.slice(8,12)==='WEBP')return'image/webp';if(ascii.slice(0,5)==='%PDF-')return'application/pdf';return null;}
function error(res,status,code,message,details){return res.status(status).json({success:false,code,message,...(details?{details}:{})});}

async function schemaHealth(queryable=db){
    const [rows]=await queryable.query(`SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN (${REQUIRED_TABLES.map(()=>'?').join(',')})`,REQUIRED_TABLES);
    const found=new Set(rows.map(row=>String(row.TABLE_NAME).toLowerCase()));
    const missing=REQUIRED_TABLES.filter(name=>!found.has(name.toLowerCase()));
    if(missing.length)return{ready:false,missing,contractVersion:rules.CONTRACT_VERSION,schemaVersion:null,moduleEnabled:false};
    const [settings]=await queryable.query("SELECT SettingKey,SettingValue FROM SafetyVote_Settings WHERE SettingKey IN ('contract_version','schema_version','module_enabled')");
    const map=Object.fromEntries(settings.map(row=>[row.SettingKey,String(row.SettingValue)]));
    return{ready:map.contract_version===rules.CONTRACT_VERSION&&[SCHEMA_VERSION,'2026-10-08-phase6-r1','2026-10-08-phase7-r1'].includes(map.schema_version),missing:[],contractVersion:map.contract_version||null,schemaVersion:map.schema_version||null,moduleEnabled:map.module_enabled==='1'};
}
async function requireSchema(req,res,next){try{const health=await schemaHealth();if(!health.ready)return error(res,503,'SAFETY_VOTE_SCHEMA_NOT_READY','Safety Vote schema is not ready.',health);req.safetyVoteHealth=health;next();}catch(e){return error(res,503,'SAFETY_VOTE_SCHEMA_NOT_READY','Unable to verify Safety Vote schema.');}}
async function hasPermission(req,permission){if(role(req)==='ADMIN')return true;const id=actor(req);const[[override]]=await db.query('SELECT granted FROM Admin_UserPermissions WHERE employee_id=? AND permission=? LIMIT 1',[id,permission]);if(override)return Number(override.granted)===1;const[[row]]=await db.query('SELECT granted FROM Admin_RolePermissions WHERE UPPER(role)=? AND permission=? LIMIT 1',[role(req),permission]);if(row&&Number(row.granted)===1)return true;const[[admin]]=await db.query('SELECT granted FROM Admin_UserPermissions WHERE employee_id=? AND permission=? LIMIT 1',[id,'SAFETY_VOTE_ADMIN']);return Boolean(admin&&Number(admin.granted)===1);}
function permit(permission){return async(req,res,next)=>{try{if(await hasPermission(req,permission))return next();return error(res,403,'PERMISSION_DENIED','Safety Vote permission is required.');}catch(e){return error(res,503,'PERMISSION_CHECK_UNAVAILABLE','Unable to verify Safety Vote permission.');}};}
async function audit(req,action,targetType,targetId,detail,metadata={}){try{await db.query('INSERT INTO SafetyVote_AuditLogs(CampaignID,CampaignVersionID,ActorEmployeeID,ActorRole,Action,TargetType,TargetID,StatusCode,BoundedDetail,MetadataJson,IPAddress,UserAgent) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[req.svCampaignId||null,req.svVersionId||null,actor(req),role(req),action,targetType,String(targetId||''),200,rules.clean(detail,1000)||null,JSON.stringify(metadata),req.ip||null,String(req.headers?.['user-agent']||'').slice(0,255)||null]);req.auditLogged=true;}catch(e){console.warn('[safety-vote] audit failed:',e.message);}}

async function masterProjection(queryable=db){
    const [[employees],[departments],[units],[positions]]=await Promise.all([
        queryable.query('SELECT EmployeeID,EmployeeName,Department,Unit,Team,Position,Role,Password,MustChangePassword FROM Employees ORDER BY EmployeeID'),
        queryable.query('SELECT id,Name,Status,is_safety_core FROM Master_Departments ORDER BY Name'),
        queryable.query('SELECT id,name,department_id,short_code,sort_order FROM Master_SafetyUnits ORDER BY department_id,sort_order,name'),
        queryable.query('SELECT id,Name FROM Master_Positions ORDER BY Name'),
    ]);
    const resolver=createOnboardingResolver({departments,units});
    const key=value=>String(value??'').trim().replace(/\s+/g,'').toLocaleLowerCase('en-US');
    const dept=new Map(departments.map(row=>[key(row.Name),row]));
    const unit=new Map(units.map(row=>[`${row.department_id}\0${key(row.name)}`,row]));
    const pos=new Map(positions.map(row=>[key(row.Name),row]));
    const rows=employees.map(row=>{const d=dept.get(key(row.Department))||null,u=d?unit.get(`${d.id}\0${key(row.Unit)}`)||null:null,p=pos.get(key(row.Position))||null;let onboardingStatus;try{onboardingStatus=resolver.resolve(row);}catch(e){onboardingStatus=e.code||'UNRESOLVED';}return{employeeId:String(row.EmployeeID),employeeName:row.EmployeeName||'',departmentId:d?Number(d.id):null,departmentName:row.Department||'',safetyUnitId:u?Number(u.id):null,safetyUnitName:row.Unit||'',positionId:p?Number(p.id):null,positionName:row.Position||'',role:row.Role||'',team:row.Team||'',masterPresent:true,accountReady:onboardingStatus===ONBOARDING_STATUS.READY,onboardingStatus,masterWarnings:[!d?'DEPARTMENT_UNRESOLVED':null,d&&!u&&units.some(x=>Number(x.department_id)===Number(d.id))?'SAFETY_UNIT_UNRESOLVED':null,!p?'POSITION_UNRESOLVED':null].filter(Boolean)};});
    return{employees:rows,departments,units,positions};
}
async function campaignRow(id,lock=false,queryable=db){const[rows]=await queryable.query(`SELECT c.*,v.VersionNo,v.ContractVersion,v.TemplateKey,v.CampaignType,v.PrivacyMode,v.TitleTh,v.TitleEn,v.Summary,v.Description,v.RulesText,v.TimeZone,v.OpenAt,v.CloseAt,v.ResultVisibility,v.PrivacyThreshold,v.Status VersionStatus,v.RowVersion VersionRowVersion FROM SafetyVote_Campaigns c JOIN SafetyVote_CampaignVersions v ON v.id=c.CurrentVersionID WHERE c.id=?${lock?' FOR UPDATE':''}`,[id]);return rows[0]||null;}

router.get('/admin/health',permit('SAFETY_VOTE_VIEW'),async(req,res)=>{try{const health=await schemaHealth();return res.status(health.ready?200:503).json({success:health.ready,data:health,...(!health.ready?{code:'SAFETY_VOTE_SCHEMA_NOT_READY',message:'Safety Vote schema is not ready.'}:{})});}catch(e){return error(res,503,'SAFETY_VOTE_SCHEMA_NOT_READY','Unable to verify Safety Vote schema.');}});
router.use('/admin',requireSchema);
router.get('/admin/permissions',permit('SAFETY_VOTE_VIEW'),async(req,res)=>res.json({success:true,data:{permissions:PERMISSIONS,admin:role(req)==='ADMIN'}}));
router.get('/admin/campaigns',permit('SAFETY_VOTE_MANAGE'),async(req,res)=>{try{const[rows]=await db.query('SELECT c.id,c.CampaignCode,c.Status,c.OwnerEmployeeID,c.DiscoveryMode,c.RowVersion,c.CreatedAt,c.UpdatedAt,v.VersionNo,v.CampaignType,v.PrivacyMode,v.TitleTh,v.TitleEn,v.ResultVisibility,v.RowVersion VersionRowVersion FROM SafetyVote_Campaigns c JOIN SafetyVote_CampaignVersions v ON v.id=c.CurrentVersionID ORDER BY c.UpdatedAt DESC,c.id DESC LIMIT 250');res.json({success:true,data:{rows,total:rows.length}});}catch(e){return error(res,500,'SAFETY_VOTE_READ_FAILED','Unable to load campaigns.');}});
router.post('/admin/campaigns',permit('SAFETY_VOTE_CREATE'),async(req,res)=>{const parsed=rules.normalizeCampaign(req.body||{});if(!parsed.ok)return error(res,400,'VALIDATION_FAILED','Campaign validation failed.',parsed.errors);const v=parsed.value,connection=await db.getConnection();try{await connection.beginTransaction();const[created]=await connection.query("INSERT INTO SafetyVote_Campaigns(CampaignCode,Status,OwnerEmployeeID,DiscoveryMode,ScheduledOpenAt,ScheduledCloseAt,CreatedBy,UpdatedBy) VALUES(?,'Draft',?,?,?,?,?,?)",[v.campaignCode,actor(req),v.discoveryMode,v.openAt,v.closeAt,actor(req),actor(req)]);const id=Number(created.insertId);const[version]=await connection.query("INSERT INTO SafetyVote_CampaignVersions(CampaignID,VersionNo,ContractVersion,TemplateKey,CampaignType,PrivacyMode,TitleTh,TitleEn,Summary,Description,RulesText,OpenAt,CloseAt,ResultVisibility,PrivacyThreshold,CreatedBy,UpdatedBy) VALUES(?,1,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[id,rules.CONTRACT_VERSION,v.templateKey,v.campaignType,v.privacyMode,v.titleTh,v.titleEn,v.summary,v.description,v.rulesText,v.openAt,v.closeAt,v.resultVisibility,v.privacyThreshold,actor(req),actor(req)]);await connection.query('UPDATE SafetyVote_Campaigns SET CurrentVersionID=? WHERE id=?',[version.insertId,id]);await connection.commit();req.svCampaignId=id;req.svVersionId=Number(version.insertId);await audit(req,'SAFETY_VOTE_CAMPAIGN_CREATE','SafetyVote_Campaign',id,`code=${v.campaignCode}; type=${v.campaignType}`);res.status(201).json({success:true,data:await campaignRow(id)});}catch(e){await connection.rollback().catch(()=>{});if(e.code==='ER_DUP_ENTRY')return error(res,409,'CAMPAIGN_CODE_EXISTS','Campaign code already exists.');return error(res,500,'SAFETY_VOTE_CREATE_FAILED','Unable to create campaign.');}finally{connection.release();}});
router.get('/admin/campaigns/:id',permit('SAFETY_VOTE_MANAGE'),async(req,res)=>{const id=rules.positiveInt(req.params.id);if(!id)return error(res,400,'VALIDATION_FAILED','Valid campaign ID is required.');try{const row=await campaignRow(id);if(!row)return error(res,404,'CAMPAIGN_NOT_FOUND','Campaign was not found.');const[rulesRows]=await db.query('SELECT * FROM SafetyVote_EligibilityRules WHERE CampaignVersionID=? ORDER BY RuleGroup,RuleOrder,id',[row.CurrentVersionID]);res.json({success:true,data:{campaign:row,eligibilityRules:rulesRows.map(r=>({...r,values:JSON.parse(r.ValuesJson||'[]')}))}});}catch(e){return error(res,500,'SAFETY_VOTE_READ_FAILED','Unable to load campaign.');}});
router.put('/admin/campaigns/:id',permit('SAFETY_VOTE_MANAGE'),async(req,res)=>{const id=rules.positiveInt(req.params.id),expected=rules.positiveInt(req.body?.rowVersion);if(!id||!expected)return error(res,400,'VALIDATION_FAILED','Campaign ID and rowVersion are required.');const parsed=rules.normalizeCampaign(req.body||{});if(!parsed.ok)return error(res,400,'VALIDATION_FAILED','Campaign validation failed.',parsed.errors);const v=parsed.value,connection=await db.getConnection();try{await connection.beginTransaction();const row=await campaignRow(id,true,connection);if(!row){await connection.rollback();return error(res,404,'CAMPAIGN_NOT_FOUND','Campaign was not found.');}if(row.Status!=='Draft'||row.VersionStatus!=='Draft'){await connection.rollback();return error(res,409,'CAMPAIGN_STATE_CONFLICT','Only Draft campaigns can be edited.');}if(Number(row.RowVersion)!==expected){await connection.rollback();return error(res,409,'VERSION_CONFLICT','Campaign changed. Reload before saving.');}await connection.query('UPDATE SafetyVote_Campaigns SET CampaignCode=?,DiscoveryMode=?,ScheduledOpenAt=?,ScheduledCloseAt=?,UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=?',[v.campaignCode,v.discoveryMode,v.openAt,v.closeAt,actor(req),id]);await connection.query('UPDATE SafetyVote_CampaignVersions SET TemplateKey=?,CampaignType=?,PrivacyMode=?,TitleTh=?,TitleEn=?,Summary=?,Description=?,RulesText=?,OpenAt=?,CloseAt=?,ResultVisibility=?,PrivacyThreshold=?,UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=?',[v.templateKey,v.campaignType,v.privacyMode,v.titleTh,v.titleEn,v.summary,v.description,v.rulesText,v.openAt,v.closeAt,v.resultVisibility,v.privacyThreshold,actor(req),row.CurrentVersionID]);await connection.commit();req.svCampaignId=id;req.svVersionId=row.CurrentVersionID;await audit(req,'SAFETY_VOTE_CAMPAIGN_UPDATE','SafetyVote_Campaign',id,`code=${v.campaignCode}`);res.json({success:true,data:await campaignRow(id)});}catch(e){await connection.rollback().catch(()=>{});if(e.code==='ER_DUP_ENTRY')return error(res,409,'CAMPAIGN_CODE_EXISTS','Campaign code already exists.');return error(res,500,'SAFETY_VOTE_UPDATE_FAILED','Unable to update campaign.');}finally{connection.release();}});

router.delete('/admin/campaigns/:id',permit('SAFETY_VOTE_MANAGE'),async(req,res)=>{
    const id=rules.positiveInt(req.params.id),reason=rules.clean(req.body?.reason,500);
    if(!id||!reason)return error(res,400,'VALIDATION_FAILED','Campaign ID and void reason are required.');
    const connection=await db.getConnection();
    try{
        await connection.beginTransaction();
        const row=await campaignRow(id,true,connection);
        if(!row){await connection.rollback();return error(res,404,'CAMPAIGN_NOT_FOUND','Campaign was not found.');}
        if(row.Status!=='Draft'||row.VersionStatus!=='Draft'){await connection.rollback();return error(res,409,'CAMPAIGN_STATE_CONFLICT','Only Draft campaigns can be voided.');}
        await connection.query("UPDATE SafetyVote_Campaigns SET Status='Voided',VoidedAt=NOW(),VoidedBy=?,VoidReason=?,UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=?",[actor(req),reason,actor(req),id]);
        await connection.query("UPDATE SafetyVote_CampaignVersions SET Status='Voided',UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=?",[actor(req),row.CurrentVersionID]);
        await connection.commit();req.svCampaignId=id;req.svVersionId=row.CurrentVersionID;
        await audit(req,'SAFETY_VOTE_CAMPAIGN_VOID','SafetyVote_Campaign',id,reason);
        return res.json({success:true,data:{id,status:'Voided'}});
    }catch(e){await connection.rollback().catch(()=>{});return error(res,500,'SAFETY_VOTE_VOID_FAILED','Unable to void campaign.');}finally{connection.release();}
});

router.get('/admin/master/employees',permit('SAFETY_VOTE_MANAGE'),async(req,res)=>{try{const data=await masterProjection(),q=rules.clean(req.query.q,100).toLocaleLowerCase(),departmentId=rules.positiveInt(req.query.departmentId),unitId=rules.positiveInt(req.query.safetyUnitId);let rows=data.employees;if(q)rows=rows.filter(r=>[r.employeeId,r.employeeName,r.departmentName,r.safetyUnitName,r.positionName].some(v=>String(v).toLocaleLowerCase().includes(q)));if(departmentId)rows=rows.filter(r=>r.departmentId===departmentId);if(unitId)rows=rows.filter(r=>r.safetyUnitId===unitId);const page=Math.max(1,rules.positiveInt(req.query.page)||1),pageSize=Math.min(100,Math.max(1,rules.positiveInt(req.query.pageSize)||25)),total=rows.length;res.json({success:true,data:{rows:rows.slice((page-1)*pageSize,page*pageSize),total,page,pageSize}});}catch(e){return error(res,503,'MASTER_DATA_INVALID','Employee Master is unavailable or ambiguous.');}});
router.get('/admin/master/departments',permit('SAFETY_VOTE_MANAGE'),async(req,res)=>{try{const data=await masterProjection();res.json({success:true,data:data.departments});}catch(e){return error(res,503,'MASTER_DATA_INVALID','Department Master is unavailable.');}});
router.get('/admin/master/safety-units',permit('SAFETY_VOTE_MANAGE'),async(req,res)=>{try{const data=await masterProjection();res.json({success:true,data:data.units});}catch(e){return error(res,503,'MASTER_DATA_INVALID','Safety Unit Master is unavailable.');}});
router.get('/admin/master/positions',permit('SAFETY_VOTE_MANAGE'),async(req,res)=>{try{const data=await masterProjection();res.json({success:true,data:data.positions});}catch(e){return error(res,503,'MASTER_DATA_INVALID','Position Master is unavailable.');}});

router.put('/admin/campaigns/:id/eligibility/rules',permit('SAFETY_VOTE_ELIGIBILITY_MANAGE'),async(req,res)=>{const id=rules.positiveInt(req.params.id),parsed=rules.normalizeRules(req.body?.rules);if(!id||!parsed.ok)return error(res,400,'VALIDATION_FAILED','Eligibility rules are invalid.',parsed.errors);const connection=await db.getConnection();try{await connection.beginTransaction();const row=await campaignRow(id,true,connection);if(!row){await connection.rollback();return error(res,404,'CAMPAIGN_NOT_FOUND','Campaign was not found.');}if(row.Status!=='Draft'){await connection.rollback();return error(res,409,'CAMPAIGN_STATE_CONFLICT','Eligibility rules are editable only in Draft.');}await connection.query('DELETE FROM SafetyVote_EligibilityRules WHERE CampaignVersionID=?',[row.CurrentVersionID]);for(const rule of parsed.rules)await connection.query('INSERT INTO SafetyVote_EligibilityRules(CampaignVersionID,RuleGroup,RuleOrder,Effect,AttributeKey,Operator,ValuesJson,Reason,CreatedBy,UpdatedBy) VALUES(?,?,?,?,?,?,?,?,?,?)',[row.CurrentVersionID,rule.ruleGroup,rule.ruleOrder,rule.effect,rule.attributeKey,rule.operator,JSON.stringify(rule.values),rule.reason,actor(req),actor(req)]);await connection.commit();req.svCampaignId=id;req.svVersionId=row.CurrentVersionID;await audit(req,'SAFETY_VOTE_ELIGIBILITY_RULES_UPDATE','SafetyVote_Campaign',id,`rules=${parsed.rules.length}`,{ruleCount:parsed.rules.length,ruleHash:rules.canonicalHash(parsed.rules)});res.json({success:true,data:{rules:parsed.rules,ruleHash:rules.canonicalHash(parsed.rules)}});}catch(e){await connection.rollback().catch(()=>{});return error(res,500,'SAFETY_VOTE_RULE_SAVE_FAILED','Unable to save eligibility rules.');}finally{connection.release();}});
router.post('/admin/campaigns/:id/eligibility/preview',permit('SAFETY_VOTE_ELIGIBILITY_MANAGE'),async(req,res)=>{const id=rules.positiveInt(req.params.id);if(!id)return error(res,400,'VALIDATION_FAILED','Valid campaign ID is required.');try{const row=await campaignRow(id);if(!row)return error(res,404,'CAMPAIGN_NOT_FOUND','Campaign was not found.');let parsed;if(Array.isArray(req.body?.rules))parsed=rules.normalizeRules(req.body.rules);else{const[stored]=await db.query('SELECT RuleGroup ruleGroup,RuleOrder ruleOrder,Effect effect,AttributeKey attributeKey,Operator operator,ValuesJson,Reason reason FROM SafetyVote_EligibilityRules WHERE CampaignVersionID=? AND IsActive=1 ORDER BY RuleGroup,RuleOrder,id',[row.CurrentVersionID]);parsed=rules.normalizeRules(stored.map(r=>({...r,values:JSON.parse(r.ValuesJson||'[]')})));}if(!parsed.ok)return error(res,400,'VALIDATION_FAILED','Eligibility rules are invalid.',parsed.errors);const master=await masterProjection(),eligible=rules.evaluateEligibility(parsed.rules,master.employees),warnings=eligible.reduce((sum,e)=>sum+e.masterWarnings.length,0),breakdown={};for(const e of eligible){const key=e.departmentName||'Unresolved';breakdown[key]=(breakdown[key]||0)+1;}res.json({success:true,data:{ruleHash:rules.canonicalHash(parsed.rules),eligibleCount:eligible.length,accountReadyCount:eligible.filter(e=>e.accountReady).length,warningCount:warnings,breakdown,rows:eligible.slice(0,250),truncated:eligible.length>250}});}catch(e){return error(res,503,'MASTER_DATA_INVALID','Unable to preview eligibility against Master Data.');}});

router.post('/admin/campaigns/:id/files',permit('SAFETY_VOTE_MANAGE'),(req,res)=>upload.single('file')(req,res,async uploadError=>{if(uploadError)return error(res,400,'FILE_UPLOAD_REJECTED',uploadError.code==='LIMIT_FILE_SIZE'?'File must not exceed 10 MB.':'File upload was rejected.');const id=rules.positiveInt(req.params.id),purpose=rules.clean(req.body?.filePurpose||'cover',40);let persisted=false;try{if(!id||!req.file)throw Object.assign(new Error('A valid campaign and file are required.'),{status:400});const row=await campaignRow(id);if(!row)throw Object.assign(new Error('Campaign was not found.'),{status:404});if(row.Status!=='Draft')throw Object.assign(new Error('Files can be added only to Draft campaigns.'),{status:409});const mime=verifiedMime(req.file.path);if(!mime||mime!==req.file.mimetype)throw Object.assign(new Error('File content does not match its declared type.'),{status:400});const sha=crypto.createHash('sha256').update(fs.readFileSync(req.file.path)).digest('hex');const[result]=await db.query('INSERT INTO SafetyVote_Files(CampaignID,CampaignVersionID,FilePurpose,StoredName,OriginalName,MimeType,FileSize,ContentSha256,UploadedBy) VALUES(?,?,?,?,?,?,?,?,?)',[id,row.CurrentVersionID,purpose,path.basename(req.file.filename),rules.clean(req.file.originalname,255),mime,req.file.size,sha,actor(req)]);persisted=true;req.svCampaignId=id;req.svVersionId=row.CurrentVersionID;await audit(req,'SAFETY_VOTE_FILE_UPLOAD','SafetyVote_File',result.insertId,`purpose=${purpose}; size=${req.file.size}`,{purpose,mime,size:req.file.size,sha256:sha});res.status(201).json({success:true,data:{id:Number(result.insertId),filePurpose:purpose,originalName:rules.clean(req.file.originalname,255),mimeType:mime,fileSize:req.file.size,sha256:sha}});}catch(e){if(!persisted)removeFile(req.file?.filename);return error(res,e.status||500,e.status===409?'CAMPAIGN_STATE_CONFLICT':'FILE_UPLOAD_REJECTED',e.status?e.message:'Unable to store file.');}}));
router.get('/files/:fileId',requireSchema,permit('SAFETY_VOTE_VIEW'),async(req,res)=>{const id=rules.positiveInt(req.params.fileId);if(!id)return error(res,400,'VALIDATION_FAILED','Valid file ID is required.');try{const[[file]]=await db.query("SELECT f.* FROM SafetyVote_Files f WHERE f.id=? AND f.Status='Active' LIMIT 1",[id]);if(!file)return error(res,404,'FILE_NOT_FOUND','File was not found.');if(role(req)!=='ADMIN'&&!await hasPermission(req,'SAFETY_VOTE_MANAGE')){const[[scope]]=await db.query("SELECT e.id FROM SafetyVote_EligibilitySnapshots s JOIN SafetyVote_EligibleVoters e ON e.SnapshotID=s.id JOIN SafetyVote_Campaigns c ON c.CurrentVersionID=s.CampaignVersionID WHERE c.id=? AND s.Status='frozen' AND e.EmployeeID=? LIMIT 1",[file.CampaignID,actor(req)]);if(!scope)return error(res,404,'FILE_NOT_FOUND','File was not found.');}const disk=path.join(privateDir,path.basename(file.StoredName));if(!disk.startsWith(privateDir)||!fs.existsSync(disk)||verifiedMime(disk)!==file.MimeType)return error(res,404,'FILE_NOT_FOUND','File is unavailable.');res.setHeader('Content-Type',file.MimeType);res.setHeader('Content-Disposition',`inline; filename*=UTF-8''${encodeURIComponent(file.OriginalName)}`);res.setHeader('Cache-Control','private, no-store');res.setHeader('X-Content-Type-Options','nosniff');return res.sendFile(disk);}catch(e){return error(res,500,'FILE_READ_FAILED','Unable to read file.');}});
router.delete('/admin/campaigns/:id/files/:fileId',permit('SAFETY_VOTE_MANAGE'),async(req,res)=>{const id=rules.positiveInt(req.params.id),fileId=rules.positiveInt(req.params.fileId),reason=rules.clean(req.body?.reason,255);if(!id||!fileId||!reason)return error(res,400,'VALIDATION_FAILED','Campaign, file and removal reason are required.');try{const row=await campaignRow(id);if(!row)return error(res,404,'CAMPAIGN_NOT_FOUND','Campaign was not found.');if(row.Status!=='Draft')return error(res,409,'CAMPAIGN_STATE_CONFLICT','Files can be removed only from Draft campaigns.');const[result]=await db.query("UPDATE SafetyVote_Files SET Status='Removed',RemovedBy=?,RemovedAt=NOW(),RemovalReason=? WHERE id=? AND CampaignID=? AND Status='Active'",[actor(req),reason,fileId,id]);if(!result.affectedRows)return error(res,404,'FILE_NOT_FOUND','File was not found.');req.svCampaignId=id;req.svVersionId=row.CurrentVersionID;await audit(req,'SAFETY_VOTE_FILE_REMOVE','SafetyVote_File',fileId,reason);res.json({success:true});}catch(e){return error(res,500,'FILE_REMOVE_FAILED','Unable to remove file.');}});

module.exports=router;
module.exports.schemaHealth=schemaHealth;
module.exports.masterProjection=masterProjection;
