'use strict';
const fs=require('fs');const path=require('path');const assert=require('assert');const{spawnSync}=require('child_process');const designer=require('../services/bbs-card-designer');const root=path.join(__dirname,'..','..');const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const sql=read('backend/migrations/20260902_bbs_phase10f1_visual_card_designer_foundation.sql'),rollback=read('backend/migrations/20260902_bbs_phase10f1_visual_card_designer_foundation.rollback.sql');
for(const table of ['BBS_Card_Layout_Versions','BBS_Card_Layout_Sides','BBS_Card_Layout_Elements','BBS_Card_Layout_Assets','BBS_Card_Designer_Print_Snapshots'])assert.ok(sql.includes(`CREATE TABLE IF NOT EXISTS ${table}`),`missing ${table}`);
for(const flag of ['visual_card_designer_enabled','visual_card_designer_rendering_enabled']){assert.match(sql,new RegExp(`'${flag}','0'`));assert.match(rollback,new RegExp(`'${flag}','0'`));}
assert.doesNotMatch(sql,/ALTER\s+TABLE\s+BBS_(Card_Templates|Department_Card_Templates|Cards|Department_QR_Cards|Card_Print_Logs|Department_Card_Print_Logs)/i);assert.doesNotMatch(rollback,/DROP\s+TABLE|DELETE\s+FROM/i);
const nodeRoute=read('backend/routes/bbs-card-designer.js'),phpRoute=read('api/handlers/bbs_card_designer.php'),server=read('backend/server.js'),phpIndex=read('api/index.php');
for(const marker of ['/admin/card-designer/catalog','/admin/card-designer/:kind/:templateId/versions','/admin/card-designer/versions/:id','/admin/card-designer/versions/:id/readiness']){assert.ok(nodeRoute.includes(marker),`Node missing ${marker}`);assert.ok(phpRoute.includes(`/bbs${marker}`),`PHP missing ${marker}`);}
for(const source of [nodeRoute,phpRoute]){assert.match(source,/BBS_DESIGNER_DISABLED/);assert.match(source,/IMMUTABLE_LAYOUT_VERSION/);assert.match(source,/FOR UPDATE/);assert.match(source,/RowVersion/);}
assert.match(server,/authenticateToken, bbsCardDesignerRoutes/);assert.match(phpIndex,/handle_bbs_card_designer_routes/);
const parent={WidthMM:53.98,HeightMM:85.6,BackgroundStoredName:'legacy.png',OriginalName:'legacy.png',MimeType:'image/png',FileSize:100,IncludeEmployeeID:1};const layout=designer.legacyLayout(parent,'Personal');assert.strictEqual(layout.templateKind,'Personal');assert.strictEqual(layout.sides.length,1);assert.ok(layout.elements.some(item=>item.dataSourceKey==='card.personal_qr'));assert.strictEqual(designer.assessLayout(layout).status,'Warning');
const phpExe=process.env.PHP_EXE||'C:\\xampp\\php\\php.exe',probe=path.join(__dirname,'bbs-phase10f1-php-validator-probe.php');const runPhp=input=>{const result=spawnSync(phpExe,[probe],{input:JSON.stringify(input),encoding:'utf8'});return{status:result.status,body:JSON.parse(result.stdout||'{}')};};const phpValid=runPhp({kind:'Personal',layout});assert.strictEqual(phpValid.status,0,phpValid.body.message);assert.strictEqual(phpValid.body.layout.templateKind,layout.templateKind);assert.deepStrictEqual(phpValid.body.readiness,designer.assessLayout(layout));
const invalids=[{...layout,elements:[{...layout.elements[0],dataSourceKey:'department.name'}]},{...layout,elements:[{...layout.elements[0],xBP:9000,widthBP:2000}]},{...layout,elements:[{...layout.elements[0],style:{position:'fixed'}}]}];for(const invalid of invalids){assert.throws(()=>designer.normalizeLayoutPayload(invalid,'Personal'),designer.DesignerValidationError);const result=runPhp({kind:'Personal',layout:invalid});assert.strictEqual(result.status,2);assert.strictEqual(result.body.ok,false);}
const inventory=read('backend/scripts/bbs-phase10f1-card-designer-inventory.js'),bootstrap=read('backend/scripts/bbs-phase10f1-legacy-bootstrap.js');assert.doesNotMatch(inventory,/query\(\s*['"`]\s*(INSERT|UPDATE|DELETE|REPLACE|ALTER|DROP)\b/i);assert.match(bootstrap,/--apply/);assert.match(bootstrap,/parentRowsUnchanged/);assert.doesNotMatch(bootstrap,/UPDATE\s+BBS_(Card_Templates|Department_Card_Templates)|DELETE\s+FROM\s+BBS_/i);assert.doesNotMatch(bootstrap,/rename|copyFile|unlink|rm\(/i);
console.log('BBS Phase 10F-1 migration, validator parity, Draft API and legacy safety contract: PASS');
