const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..', '..');
const read = relative => fs.readFileSync(path.join(root, relative), 'utf8');
const nodeRoute = read('backend/routes/ky.js');
const phpRoute = read('api/handlers/workflow_phase6.php');
const frontend = read('public/js/pages/ky.js');
const main = read('public/js/main.js');
const index = read('index.html');

for (const source of [nodeRoute, phpRoute]) {
    assert.match(source, /ky_activity_external_video_evidence/i, 'per-activity external video evidence table must exist in both runtimes');
    assert.match(source, /ky_activity_external_video_evidence_audit/i, 'per-activity external video audit must exist in both runtimes');
    assert.match(source, /activity-video-evidence\/declare/, 'per-activity external declaration API must exist');
    assert.match(source, /activity-video-evidence.*verify/s, 'per-activity Admin verification API must exist');
    assert.match(source, /KY_ACTIVITY_EXTERNAL_ALREADY_VERIFIED/, 'verified activity evidence replacement must fail closed');
    assert.match(source, /ky_annual_video_evidence/i, 'annual evidence table must exist in both runtimes');
    assert.match(source, /ky_annual_video_evidence_audit/i, 'immutable annual evidence audit must exist');
    assert.match(source, /annual-video-evidence/, 'annual evidence API must exist');
    assert.match(source, /ExternalBackupConfirmed/, 'external backup confirmation must be persisted');
    assert.match(source, /ExternalReference/, 'central-machine reference must be persisted');
    assert.match(source, /SHA256/, 'full-file SHA-256 metadata must be persisted');
    assert.match(source, /ADMIN_VERIFIED/, 'Admin verification must be audited');
    assert.match(source, /PRODUCTION_FILE_DELETED/, 'physical deletion must be audited');
    assert.match(source, /KY_EXTERNAL_BACKUP_REQUIRED|External backup must be confirmed/, 'unconfirmed external backup must fail closed');
    assert.match(source, /KY_ANNUAL_VIDEO_HASH_MISMATCH|failed SHA-256 verification/, 'physical deletion must fail on hash mismatch');
    assert.match(source, /RowVersion/, 'mutations must use optimistic concurrency');
    assert.match(source, /ProductionDeletedAt/, 'metadata must retain deletion state');
    assert.match(source, /KY_VIDEO_PROTECTED_BY_RETENTION/, 'legacy replacement and activity deletion paths must fail closed');
    assert.match(source, /ProductionDeletedAt=NULL/, 'a corrected replacement must reset the previous physical-deletion marker');
    assert.match(source, /activity video reference changed|Activity.*VideoUrl.*FOR UPDATE/is, 'deletion must lock and revalidate the current activity video reference');
    assert.match(source, /HasProductionVideo/, 'activity projections must identify Production video evidence');
    assert.match(source, /HasVerifiedExternalVideo/, 'activity projections must identify verified external video evidence');
    assert.match(source, /HasPendingExternalVideo/, 'activity projections must keep pending external video separate');
    assert.match(source, /videoEvidenceRate/, 'KY stats must expose the combined verified video-evidence rate');
    assert.match(source, /external_verified/, 'KY history must filter verified external evidence');
    assert.match(source, /external_pending/, 'KY history must filter pending external evidence');
    assert.match(source, /ScopeAlreadyRegistered/, 'annual candidate projection must identify an existing scope registration');
    assert.match(source, /ScopeEvidenceID/, 'annual candidate projection must link to its existing scope evidence');
    assert.match(source, /ky_video_file_inventory/i, 'Production video inventory table must exist in both runtimes');
    assert.match(source, /ky_video_file_inventory_audit/i, 'immutable Production video inventory audit must exist');
    assert.match(source, /video-inventory\/declare/, 'Production video inventory declaration API must exist');
    assert.match(source, /KY_VIDEO_INVENTORY_BACKUP_MISMATCH/, 'external backup hash mismatch must fail closed');
    assert.match(source, /AdminAttested/, 'Inventory must support the simplified Admin-attested filename registration mode');
    assert.match(source, /KY_VIDEO_INVENTORY_NOT_VERIFIED|verified matching external backup/i, 'unverified Inventory cleanup must fail closed');
    assert.match(source, /departmentSource/, 'KY stats must identify the authoritative Department source');
    assert.match(source, /configuredDepartments/, 'KY stats must return every configured Department');
    assert.match(source, /unmappedDepartments/, 'KY stats must expose unmatched activity Department diagnostics');
    assert.match(source, /ProductionOriginalFileName/, 'Inventory projection must expose the current Production video file name');
    assert.match(source, /ky_annual_unit_contest_entries/i, 'annual Unit contest entry table must exist in both runtimes');
    assert.match(source, /unit-contest-entries/, 'annual Unit contest entry API must exist in both runtimes');
    assert.match(source, /KY_CONTEST_PRODUCTION_VIDEO_REQUIRED/, 'contest entry must require a Production video');
    assert.match(source, /KY_CONTEST_ENTRY_ADMIN_REPLACE_REQUIRED/, 'only Admin may replace an existing Unit contest entry');
    assert.match(source, /KY_CONTEST_ENTRY_RETENTION_HOLD|active annual Unit contest entry/i, 'contest Production video cleanup must fail closed');
    assert.match(source, /productionRequired/, 'annual compliance must expose its Production requirement');
    assert.match(source, /externalRequired/, 'annual compliance must expose its verified External requirement');
    assert.match(source, /missingEvidenceTotal/, 'annual compliance must expose the remaining distinct-activity count');
}

assert.match(nodeRoute, /fs\.renameSync\(entry\.localPath, quarantine\)/, 'Node must quarantine files before committing deletion metadata');
assert.match(nodeRoute, /connection\.rollback/, 'Node deletion must support transaction rollback');
assert.match(nodeRoute, /fs\.renameSync\(entry\.quarantine, entry\.localPath\)/, 'Node must restore quarantine on rollback');
assert.match(phpRoute, /rename\(\$entry\['local'\],\$quarantine\)/, 'PHP must quarantine files before committing deletion metadata');
assert.match(phpRoute, /array_reverse\(\$quarantined\)/, 'PHP must restore quarantine on rollback');

assert.match(frontend, /Annual Video Evidence/, 'Admin annual evidence workspace must exist');
assert.match(frontend, /Activity External Video Evidence/, 'Admin must have a per-activity external evidence review queue');
assert.match(frontend, /data-ky-activity-external-verify/, 'Admin must be able to verify per-activity evidence');
assert.match(frontend, /data-ky-activity-external-correction/, 'Admin must be able to request correction per activity');
assert.match(frontend, /activity-video-evidence\/declare/, 'submit, History and Manage must use per-activity evidence API');
assert.match(frontend, /ky-followup-video-central/, 'History follow-up must offer central-machine evidence');
assert.match(frontend, /Annual Compliance Dashboard/, 'annual compliance dashboard must exist');
assert.match(frontend, /data-ky-annual-delete-selected/, 'bulk Production file deletion control must exist');
assert.match(frontend, /data-ky-annual-delete-one/, 'single Production file deletion control must exist');
assert.match(frontend, /data-ky-annual-download/, 'Admin download control must exist');
assert.match(frontend, /data-ky-annual-audit/, 'Admin audit viewer must exist');
assert.match(frontend, /ky-video-central-machine/, 'submit form must support central-machine evidence');
assert.match(frontend, /sha256Blob\(videoFile\)/, 'central-machine declaration must fingerprint the selected file');
assert.match(frontend, /storageMode:\s*'CentralMachine'/, 'central-machine mode must be sent explicitly');
assert.match(frontend, /storageMode:\s*'Production'/, 'Production mode must be registered explicitly');
assert.match(frontend, /ky-manage-video-central-machine/, 'Admin activity management must support central-machine evidence for closed activities');
assert.match(frontend, /selectedStatus !== 'Closed'/, 'Admin central-machine registration must be restricted to closed activities');
assert.match(frontend, /HasVerifiedExternalVideo/, 'History badges must consume verified external evidence state');
assert.match(frontend, /External video pending Admin verify/, 'pending external evidence must remain visibly uncounted');
assert.match(frontend, /data-ky-annual-focus-evidence/, 'already-registered candidates must navigate to their existing evidence row');
assert.match(frontend, /KY_ANNUAL_VIDEO_ALREADY_VERIFIED/, 'a concurrent verified-scope conflict must be handled without an unhandled rejection');
assert.match(frontend, /External Backup.*SHA-256|External Backup.*SHA/, 'UI must explain protected deletion eligibility');
assert.match(frontend, /Production Video Inventory/, 'Admin must see the separate Production Video Inventory workspace');
assert.match(frontend, /data-ky-inventory-register/, 'Inventory must support external backup registration');
assert.match(frontend, /data-ky-inventory-delete-selected/, 'Inventory must support guarded bulk cleanup');
assert.match(frontend, /max-h-\[60vh\]/, 'Inventory list must use the expanded 60vh viewport');
assert.match(frontend, /Overview.*Annual Compliance.*Activity External.*Production Inventory.*Cleanup Queue & Audit/s, 'Admin workspace must expose focused compliance, activity, inventory and cleanup views');
assert.match(frontend, /data-id="\$\{escHtml\(row\.ActivityID\)\}"[^>]*data-ky-inventory-register=/, 'Inventory registration action lock must be scoped per Activity');
assert.doesNotMatch(frontend, /function chooseKyInventoryBackupFile/, 'Simplified Inventory registration must not open a browser file picker');
assert.match(frontend, /data-activity-date="\$\{escHtml\(String\(row\.ActivityDate\|\|''\)\.slice\(0,10\)\)\}"/, 'Inventory cards must retain their authoritative Activity Date');
assert.match(frontend, /formatKyActivityMonth\(row\.ActivityDate\)/, 'Inventory cards must display the Activity month');
assert.match(frontend, /formatKyActivityDate\(row\.ActivityDate\)/, 'Inventory cards must display the exact Activity date');
assert.match(frontend, /data-ky-inventory-help/, 'Inventory workspace must explain the external-backup registration workflow');
assert.match(frontend, /ไม่ต้องเลือกหรืออัปโหลดไฟล์สำรองผ่าน Browser/, 'Inventory help must explain the simplified filename-only workflow');
assert.match(frontend, /KY_EXTERNAL_BACKUP_ROOT = '\\\\\\\\192\.168\.124\.87'/, 'Inventory registration must use the configured central-machine root');
assert.match(frontend, /buildKyInventoryBackupReference\(\{ name: fileName \}\)/, 'Inventory registration must create its central-machine reference from the entered filename');
assert.match(frontend, /ระบุชื่อไฟล์วิดีโอที่เก็บไว้ในเครื่องกลาง/, 'Inventory registration must ask only for the external filename');
assert.match(frontend, /registrationMode:\s*'AdminAttested'/, 'Inventory registration must request server-side Production fingerprinting');
assert.doesNotMatch(frontend, /window\.prompt\('ระบุพาธ \/ เลขอ้างอิงของไฟล์ที่เก็บไว้ในเครื่องกลาง'/, 'Inventory registration must not show a second path prompt');
assert.match(frontend, /KY_VIDEO_INVENTORY_BACKUP_MISMATCH[\s\S]*ขนาดหรือ SHA-256 ไม่ตรงกัน/, 'Inventory registration must explain a backup hash mismatch to the Admin');
assert.match(frontend, /ไฟล์ Production:/, 'Inventory cards must label the current Production video file name');
assert.match(frontend, /data-ky-inventory-registration-status/, 'Inventory cards must expose live registration feedback');
assert.match(frontend, /ยังไม่ได้ลงทะเบียน External Backup/, 'Unregistered Inventory cards must show a truthful initial state');
assert.match(frontend, /กำลังลงทะเบียน: \$\{fileName\}/, 'Inventory registration must show the filename being registered');
assert.match(frontend, /ลงทะเบียนไม่สำเร็จ:/, 'Inventory registration failure must remain visible on its card');
assert.match(frontend, /data-ky-annual-admin-toolbar/, 'Annual Admin filters must use a sticky toolbar');
assert.match(frontend, /data-ky-annual-detail/, 'Annual evidence must expose a Detail Drawer action');
assert.match(frontend, /data-ky-inventory-detail/, 'Inventory evidence must expose a Detail Drawer action');
assert.match(frontend, /data-ky-cleanup-panel/, 'destructive actions must be isolated in Cleanup Queue');
assert.match(frontend, /data-ky-heatmap-department/, 'Heatmap must expose every canonical Department row for Browser UAT');
assert.match(frontend, /renderDepartmentDiagnostics/, 'Dashboard must render unmapped Department diagnostics');
assert.match(frontend, /Production \$\{row\.productionVideo\}\/\$\{row\.productionRequired\}/, 'follow-up must show Production requirement progress');
assert.match(frontend, /External verified \$\{row\.verifiedExternalVideo\}\/\$\{row\.externalRequired\}/, 'follow-up must show verified External requirement progress');
assert.match(frontend, /btn-ky-contest-entry/, 'eligible Unit activities must expose contest submission');
assert.match(frontend, /Unit contest entry/, 'Showcase cards must identify annual Unit representatives');
assert.match(main, /ky\.js\?v=20260923-ky-annual-contest-r9/, 'cache chain must expose the annual compliance and contest bundle');
assert.match(index, /main\.js\?v=20260923-fourm-curriculum-soft-disable-r1/, 'HTML entry point must invalidate the cached main module');

console.log('KY annual video evidence contract: PASS');
