'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),{spawnSync}=require('child_process'),p=require('../services/safety-vote-phase10-4');
const root=path.resolve(__dirname,'..','..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');let checks=0;const ok=(v,m)=>{assert(v,m);checks++;};
const youtube=p.canonicalMedia({scopeType:'option',questionCode:'Q1',optionCode:'O1',mediaType:'video',url:'https://www.youtube.com/watch?v=dQw4w9WgXcQ'});ok(youtube.provider==='youtube'&&youtube.embedUrl.includes('youtube-nocookie.com'),'privacy enhanced YouTube canonicalization');
ok(p.canonicalMedia({scopeType:'campaign',mediaType:'link',url:'https://example.test/a#fragment'}).url==='https://example.test/a','fragments removed');
for(const url of['http://example.test/a','https://user:pass@example.test/a','https://localhost:8443/a']){let denied=false;try{p.canonicalMedia({scopeType:'campaign',mediaType:'video',url});}catch{denied=true;}ok(denied,`deny unsafe video ${url}`);}
ok(p.editPolicy('Open',1,1).directEditAllowed===false,'live open immutable');ok(p.editPolicy('Open',1,2).revisionEditAllowed===true,'offline revision editable');ok(p.editPolicy('Open',1,2).activateRevisionAllowed===false,'open activation blocked');ok(p.editPolicy('Closed',1,2).activateRevisionAllowed===true,'closed activation allowed');
const php=`require '${path.join(root,'api','lib','safety_vote_phase10_4.php').replace(/\\/g,'/')}'; echo json_encode([sv104_media(['scopeType'=>'option','questionCode'=>'Q1','optionCode'=>'O1','mediaType'=>'video','url'=>'https://www.youtube.com/watch?v=dQw4w9WgXcQ']),sv104_policy('Open',1,2)]);`,run=spawnSync(process.env.PHP_BIN||'C:\\xampp\\php\\php.exe',['-r',php],{encoding:'utf8',windowsHide:true});assert.strictEqual(run.status,0,run.stderr);const parity=JSON.parse(run.stdout);ok(parity[0].provider===youtube.provider&&parity[0].embedUrl===youtube.embedUrl,'Node/PHP media parity');ok(parity[1].policyCode===p.editPolicy('Open',1,2).policyCode,'Node/PHP policy parity');
const migration=read('backend/migrations/20261009_safety_vote_phase10_4_media_versioning.sql'),node=read('backend/routes/safety-vote-phase10-4.js'),phpRoute=read('api/handlers/safety_vote_phase10_4.php'),wizard=read('public/js/pages/safety-vote-campaign-wizard.js'),participant=read('public/js/pages/safety-vote-page-ux1.js');
for(const text of[migration,node,phpRoute]){ok(text.includes('ParentVersionID'),'version lineage contract');ok(text.includes('SafetyVote_MediaLinks'),'media table contract');}
for(const text of[node,phpRoute]){ok(text.includes('ACTIVATE '),'exact confirmation');ok(text.includes('LIVE_VERSION_IMMUTABLE'),'live edit denial');ok(text.includes('requiresFreshEligibilityFreeze'),'fresh readiness after activation');}
ok(wizard.includes('data-svw-option-field="mediaType"')&&wizard.includes('/media`'),'Option Card media editor');ok(participant.includes('noopener noreferrer')&&participant.includes('referrerpolicy="no-referrer"'),'privacy-safe participant link');ok(!node.includes('fetch(')&&!phpRoute.includes('file_get_contents('),'server never fetches external media');
console.log(`Safety Vote Phase 10.4 static + Node/PHP parity: PASS (${checks} assertions)`);
