'use strict';
const assert=require('assert'),crypto=require('crypto'),fs=require('fs'),path=require('path'),mysql=require('mysql2/promise');
const {spawn}=require('child_process');
require('dotenv').config({path:path.join(__dirname,'..','.env')});
const root=path.resolve(__dirname,'..','..'),stamp=`${Date.now()}_${Math.floor(Math.random()*100000)}`,names={node:`tsh_safety_vote_phase1_node_${stamp}`,php:`tsh_safety_vote_phase1_php_${stamp}`},guard=/^tsh_safety_vote_phase1_(node|php)_\d+_\d+$/,children=[];let admin;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function wait(url){for(let i=0;i<100;i++){try{if((await fetch(url,{headers:{Authorization:'Bearer sv-admin'}})).ok)return;}catch{}await sleep(150);}throw new Error(`Fixture did not start: ${url}`);}
async function call(base,route,{method='GET',body,token='sv-admin'}={}){const headers={Authorization:`Bearer ${token}`,Accept:'application/json'};if(body!==undefined)headers['Content-Type']='application/json';const response=await fetch(base+route,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),text=await response.text();return{status:response.status,data:text?JSON.parse(text):{}};}
async function seed(name){const d=await mysql.createConnection({host:process.env.DB_HOST,port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER,password:process.env.DB_PASS,database:name,multipleStatements:true});await d.query("CREATE TABLE Admin_RolePermissions(role VARCHAR(50),permission VARCHAR(100),granted TINYINT,PRIMARY KEY(role,permission));CREATE TABLE Admin_UserPermissions(employee_id VARCHAR(20),permission VARCHAR(100),granted TINYINT,PRIMARY KEY(employee_id,permission));CREATE TABLE Master_Departments(id INT PRIMARY KEY,Name VARCHAR(100),Status VARCHAR(20),CreatedAt DATETIME,is_safety_core TINYINT);CREATE TABLE Master_SafetyUnits(id INT PRIMARY KEY,name VARCHAR(100),short_code VARCHAR(30),department_id INT,sort_order INT,created_at DATETIME);CREATE TABLE Master_Positions(id INT PRIMARY KEY,Name VARCHAR(100),IsSupervisorPatrol TINYINT,PatrolPassPct DECIMAL(5,2));CREATE TABLE Employees(EmployeeID VARCHAR(20) PRIMARY KEY,EmployeeName VARCHAR(255),Department VARCHAR(100),Unit VARCHAR(100),Role VARCHAR(50),Team VARCHAR(100),Position VARCHAR(100),CompanyEmail VARCHAR(150),Password VARCHAR(255),MustChangePassword TINYINT);INSERT INTO Master_Departments VALUES(1,'Safety','active',NOW(),1);INSERT INTO Master_SafetyUnits VALUES(10,'Core','CORE',1,1,NOW());INSERT INTO Master_Positions VALUES(100,'Officer',0,NULL);INSERT INTO Employees VALUES('SV-ADMIN','Admin','Safety','Core','Admin','A','Officer','admin@example.test','x',0),('SV-USER','User','Safety','Core','User','A','Officer','user@example.test','x',0);");for(const file of['20261008_safety_vote_phase1_foundation.sql','20261008_safety_vote_phase2_core_mvp.sql','20261008_safety_vote_phase3_survey_submission.sql','20261008_safety_vote_phase4_jury_scoring.sql','20261008_safety_vote_phase5_operations.sql','20261008_safety_vote_phase6_secret_election.sql','20261008_safety_vote_phase7_integrations_governance.sql','20261009_safety_vote_phase10_4_media_versioning.sql'])await d.query(fs.readFileSync(path.join(root,'backend','migrations',file),'utf8'));await d.query("UPDATE SafetyVote_Settings SET SettingValue='1' WHERE SettingKey='module_enabled'");await d.end();}
async function lifecycle(label,base,name){
 const created=await call(base,'/admin/campaigns',{method:'POST',body:{titleTh:`${label} revision campaign`,campaignType:'survey',privacyMode:'identified',resultVisibility:'hidden_until_close'}});assert.strictEqual(created.status,201,JSON.stringify(created.data));const c=created.data.data,id=Number(c.id),v1=Number(c.CurrentVersionID),code=c.CampaignCode;
 assert.strictEqual((await call(base,`/admin/campaigns/${id}/eligibility/rules`,{method:'PUT',body:{rules:[{effect:'include',attributeKey:'all',operator:'IN',values:[],reason:'all'}]}})).status,200);
 const builder={questions:[{questionCode:'Q1',questionType:'single_choice',title:'Choose',isRequired:true,minSelections:1,maxSelections:1,options:[{optionCode:'O1',label:'One'},{optionCode:'O2',label:'Two'}]}]};assert.strictEqual((await call(base,`/admin/campaigns/${id}/builder`,{method:'PUT',body:builder})).status,200);
 const media={items:[{scopeType:'option',questionCode:'Q1',optionCode:'O1',mediaType:'video',url:'https://youtu.be/dQw4w9WgXcQ',title:'Safety clip'}]};const savedMedia=await call(base,`/admin/campaigns/${id}/versions/${v1}/media`,{method:'PUT',body:media});assert.strictEqual(savedMedia.status,200,JSON.stringify(savedMedia.data));assert.strictEqual(savedMedia.data.data.items[0].provider,'youtube');assert.strictEqual(savedMedia.data.data.autoEmbed,false);
 const bad=await call(base,`/admin/campaigns/${id}/versions/${v1}/media`,{method:'PUT',body:{items:[{scopeType:'campaign',mediaType:'video',url:'http://example.test/video'}]}});assert.strictEqual(bad.status,400);assert.strictEqual(bad.data.code,'VALIDATION_FAILED');
 assert.strictEqual((await call(base,`/admin/campaigns/${id}/eligibility/freeze`,{method:'POST',body:{reason:'Phase 10.4 guarded freeze'}})).status,201);assert.strictEqual((await call(base,`/admin/campaigns/${id}/lifecycle/open`,{method:'POST',body:{}})).status,200);
 const revision=await call(base,`/admin/campaigns/${id}/versions`,{method:'POST',body:{reason:'Improve wording and training media'}});assert.strictEqual(revision.status,201,JSON.stringify(revision.data));const v2=Number(revision.data.data.versionId);assert.notStrictEqual(v2,v1);assert.strictEqual(revision.data.data.liveVersionChanged,false);
 const versions=await call(base,`/admin/campaigns/${id}/versions`);assert.strictEqual(versions.status,200);assert.strictEqual(Number(versions.data.data.currentVersionId),v1);assert.strictEqual(versions.data.data.versions.find(x=>Number(x.id)===v2).ParentVersionID,v1);
 const liveWrite=await call(base,`/admin/campaigns/${id}/versions/${v1}/media`,{method:'PUT',body:{items:[]}});assert.strictEqual(liveWrite.status,409);assert.strictEqual(liveWrite.data.code,'LIVE_VERSION_IMMUTABLE');
 const revisionMedia=await call(base,`/admin/campaigns/${id}/versions/${v2}/media`,{method:'PUT',body:{items:[{scopeType:'option',questionCode:'Q1',optionCode:'O2',mediaType:'link',url:'https://example.test/safety',title:'Guide'}]}});assert.strictEqual(revisionMedia.status,200,JSON.stringify(revisionMedia.data));
 const wrong=await call(base,`/admin/campaigns/${id}/versions/${v2}/activate`,{method:'POST',body:{confirmation:'ACTIVATE WRONG'}});assert.strictEqual(wrong.status,400);assert.strictEqual(wrong.data.code,'ACTIVATION_CONFIRMATION_REQUIRED');
 const openActivation=await call(base,`/admin/campaigns/${id}/versions/${v2}/activate`,{method:'POST',body:{confirmation:`ACTIVATE ${code} V2`}});assert.strictEqual(openActivation.status,409);assert.strictEqual(openActivation.data.code,'REVISION_ACTIVATION_BLOCKED');
 assert.strictEqual((await call(base,`/admin/campaigns/${id}/lifecycle/close`,{method:'POST',body:{}})).status,200);const activated=await call(base,`/admin/campaigns/${id}/versions/${v2}/activate`,{method:'POST',body:{confirmation:`ACTIVATE ${code} V2`}});assert.strictEqual(activated.status,200,JSON.stringify(activated.data));assert.strictEqual(activated.data.data.status,'Draft');assert.strictEqual(activated.data.data.requiresFreshEligibilityFreeze,true);
 const d=await mysql.createConnection({host:process.env.DB_HOST,port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER,password:process.env.DB_PASS,database:name});const[[row]]=await d.query("SELECT c.CurrentVersionID,c.Status,(SELECT COUNT(*) FROM SafetyVote_CampaignVersions WHERE CampaignID=c.id) versions,(SELECT COUNT(*) FROM SafetyVote_Ballots WHERE CampaignVersionID=?) revisionBallots,(SELECT COUNT(*) FROM SafetyVote_MediaLinks WHERE CampaignVersionID=?) revisionMedia FROM SafetyVote_Campaigns c WHERE c.id=?",[v2,v2,id]);assert.deepStrictEqual([Number(row.CurrentVersionID),row.Status,Number(row.versions),Number(row.revisionBallots),Number(row.revisionMedia)],[v2,'Draft',2,0,1]);await d.end();console.log(`PASS ${label} Phase 10.4 media/versioning/post-open policy`);
}
async function main(){assert(new Set(['localhost','127.0.0.1','::1']).has(String(process.env.DB_HOST||'').toLowerCase()),'Refusing non-loopback DB');admin=await mysql.createConnection({host:process.env.DB_HOST,port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER,password:process.env.DB_PASS});for(const name of Object.values(names)){assert(guard.test(name));await admin.query(`CREATE DATABASE \`${name}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);await seed(name);}children.push(spawn(process.execPath,[path.join(__dirname,'safety-vote-phase1-node-fixture-host.js')],{cwd:root,env:{...process.env,DB_NAME:names.node,SAFETY_VOTE_FIXTURE_DB:names.node,SAFETY_VOTE_FIXTURE_PORT:'5111'},stdio:'ignore',windowsHide:true}));children.push(spawn(process.env.PHP_BIN||'C:\\xampp\\php\\php.exe',['-d','display_errors=0','-S','127.0.0.1:5112',path.join(__dirname,'safety-vote-phase1-php-router.php')],{cwd:root,env:{...process.env,DB_NAME:names.php},stdio:'ignore',windowsHide:true}));await Promise.all([wait('http://127.0.0.1:5111/__ready'),wait('http://127.0.0.1:5112/__ready')]);await lifecycle('node','http://127.0.0.1:5111/api/safety-vote',names.node);await lifecycle('php','http://127.0.0.1:5112/api/safety-vote',names.php);const evidence=path.join(root,'backups','local',`safety-vote-phase104-${Date.now()}`),payload={contract:'2026-10-09-safety-vote-phase10.4-r1',decision:'PASS_LOCAL_MEDIA_VERSIONING_POST_OPEN_POLICY',nodePhpParity:true,liveVersionUnchangedDuringRevision:true,openActivationDenied:true,activationReturnsToDraft:true,requiresFreshEligibilityFreeze:true,externalMediaServerFetch:false,automaticThirdPartyEmbed:false,productionConnected:false,deployed:false,pushed:false,disposableDatabaseResidue:0};payload.resultSha256=crypto.createHash('sha256').update(JSON.stringify(payload)).digest('hex');fs.mkdirSync(evidence,{recursive:true});fs.writeFileSync(path.join(evidence,'result.json'),JSON.stringify(payload,null,2));console.log(`Safety Vote Phase 10.4 guarded Node/PHP regression: PASS (${evidence})`);}
main().catch(e=>{console.error(e.stack||e);process.exitCode=1;}).finally(async()=>{for(const child of children)if(child.exitCode===null)child.kill();await sleep(250);if(admin){for(const name of Object.values(names))if(guard.test(name))await admin.query(`DROP DATABASE IF EXISTS \`${name}\``).catch(()=>{});await admin.end().catch(()=>{});}});
