'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { pathToFileURL } = require('url');
const root = path.resolve(__dirname, '..', '..');
const read = relative => fs.readFileSync(path.join(root, relative), 'utf8');

(async () => {
    const workspace = read('public/js/pages/admin-safety-vote-governance.js');
    const modelSource = read('public/js/pages/safety-vote-governance-model.mjs');
    const model = await import(pathToFileURL(path.join(root, 'public', 'js', 'pages', 'safety-vote-governance-model.mjs')).href);
    const center = read('public/js/pages/admin-safety-vote-ux1.js');
    const components = read('public/js/pages/safety-vote-ux-components.js');
    const css = read('public/style.css');
    const main = read('public/js/main.js');
    const html = read('index.html');
    const preflightDoc = read('docs/safety-vote-ux-phase7-preflight-scope.md');
    let checks = 0;
    const check = (value, message) => { checks += 1; assert(value, message); };

    check(components.includes('__TSH_FEATURE_FLAGS__?.safetyVoteUxV1 === true'), 'UX flag must remain strict opt-in');
    check(center.includes('renderLegacySafetyVoteFoundation(container)'), 'flag-off legacy rollback is missing');
    check(center.includes("action: 'open-governance'") && center.includes('renderSafetyVoteGovernanceWorkspace'), 'Admin governance entry is missing');
    check(workspace.includes('/release-verification`'), 'release verification read is missing');
    check(workspace.includes('/acceptance-evidence`'), 'acceptance evidence read/write is missing');
    check(workspace.includes('/observability`'), 'observability read is missing');
    check(workspace.includes('/release-preflight`'), 'release preflight read is missing');
    check(workspace.includes('/admin/integrations/catalog'), 'adapter catalog read is missing');
    check(workspace.includes('/admin/integrations/providers'), 'provider mode read is missing');
    check(workspace.includes('/integrations/handoffs/preview`'), 'handoff preview route is missing');
    check(workspace.includes('/integrations/handoffs/confirm`'), 'fixture handoff confirmation route is missing');
    check(workspace.includes("acceptanceArea: 'she_owner'") && workspace.includes("decision: 'Accepted'"), 'SHE ownership payload is missing');
    check(workspace.includes('I ACCEPT SHE_OWNER'), 'exact SHE confirmation is missing');
    check(workspace.includes('externalDelivery !== false'), 'external-delivery fail-closed check is missing');
    check(workspace.includes('externalMutation') && workspace.includes('containsVoterIdentity') && workspace.includes('containsBallotChoice'), 'privacy-safe handoff flags are missing');
    check(workspace.includes('openSafetyVoteTypedConfirmationDialog'), 'typed irreversible confirmation dialog is missing');
    check(components.includes("dataset.svDialog = 'typed-confirmation'") && components.includes('expectedConfirmation'), 'typed confirmation component is missing');
    check(components.includes('role="alertdialog"') && components.includes('aria-modal="true"'), 'dialog semantics are incomplete');
    check(components.includes('confirmation.value.trim() === expected'), 'exact confirmation matching is missing');
    check(workspace.includes('state.partial') && workspace.includes('ไม่ถือว่าผ่าน'), 'partial evidence state is missing');
    check(workspace.includes('SAFETY_VOTE_MODULE_DISABLED') && workspace.includes('fail-closed'), 'module-disabled state is missing');
    check(workspace.includes('PERMISSION_DENIED') && workspace.includes('state.denied'), 'permission denied state is missing');
    check(workspace.includes("decision === 'READY_FOR_SEPARATE_PRODUCTION_PREFLIGHT'") || modelSource.includes("decision === 'READY_FOR_SEPARATE_PRODUCTION_PREFLIGHT'"), 'authoritative readiness decision mapping is missing');
    check(modelSource.includes("decision: data.decision === 'READY_FOR_SEPARATE_PRODUCTION_PREFLIGHT' ? data.decision : 'HOLD'"), 'unknown preflight decisions must fail closed to HOLD');
    check(workspace.includes('Production connected:') && workspace.includes('Deploy authorized:'), 'Production/deploy authorization wording is missing');
    check(workspace.includes('evidenceTimeline') && modelSource.includes("type: 'acceptance'"), 'bounded audit timeline is missing');
    check(!workspace.includes('SafetyVote_'), 'client must not query Safety Vote tables directly');
    check(!workspace.includes('BallotAnswers') && !workspace.includes('BallotIdentities'), 'client must not query ballot identity or answers');
    check(!workspace.includes('fetch('), 'workspace must use authenticated API client only');
    check(/safety-vote-ux(?:7|8)-r1/.test(main) && /safety-vote-ux(?:7|8)-r1/.test(html), 'Phase 7-or-later cache chain is incomplete');
    check(css.includes('Safety Vote UX Phase 7'), 'Phase 7 CSS marker is missing');
    check(css.includes('.svg-action-bar') && css.includes('env(safe-area-inset-bottom)'), 'sticky action bar safe-area support is missing');
    check(css.includes('.svg-shell button') && css.includes('min-height:44px'), '44 px targets are not enforced');
    check(css.includes('.svg-shell :focus-visible'), 'focus-visible indicator is missing');
    check(css.includes('@media(max-width:900px)') && css.includes('@media(max-width:600px)'), 'responsive breakpoints are incomplete');
    check(css.includes('overflow-x:clip'), 'horizontal overflow containment is missing');
    check(css.includes('prefers-reduced-motion'), 'reduced-motion support is missing');

    const verification = model.normalizeVerification({ ready: true, privacySafe: true, identityMappings: 0, activeCertifiers: 2, checks: [{ key: 'result', storedHash: 'a', calculatedHash: 'a', state: 'pass' }] });
    check(verification.ready && verification.privacySafe && verification.checks[0].state === 'pass', 'verification normalization is incorrect');
    check(!model.normalizeVerification(null).ready, 'missing verification must not pass');
    check(!model.normalizeVerification({ ready: true, checks: [{ key: 'x', state: 'fail' }] }).ready, 'failed verification check must block readiness');
    const acceptance = model.normalizeAcceptance({ required: ['she_owner'], rows: [{ acceptanceArea: 'she_owner', decision: 'Accepted', evidenceSha256: 'a'.repeat(64), approvedAt: new Date().toISOString() }] });
    check(acceptance.ready && acceptance.missing.length === 0, 'active SHE acceptance is incorrect');
    check(!model.normalizeAcceptance({ required: ['she_owner'], rows: [] }).ready, 'missing SHE acceptance must block readiness');
    check(!model.normalizeAcceptance({ required: ['she_owner'], rows: [{ acceptanceArea: 'she_owner', decision: 'Accepted', revokedAt: new Date().toISOString() }] }).ready, 'revoked acceptance must not pass');
    const preflight = model.normalizePreflight({ decision: 'READY_FOR_SEPARATE_PRODUCTION_PREFLIGHT', ready: true, checks: [{ key: 'x', state: 'pass' }], productionConnected: false, deployAuthorized: false });
    check(preflight.ready && preflight.decision === 'READY_FOR_SEPARATE_PRODUCTION_PREFLIGHT', 'ready preflight normalization is incorrect');
    check(model.normalizePreflight({ decision: 'UNKNOWN', ready: false }).decision === 'HOLD', 'unknown preflight decision must map to HOLD');
    check(!model.normalizePreflight(null).productionConnected && !model.normalizePreflight(null).deployAuthorized, 'missing preflight must not imply Production authorization');
    const observation = model.normalizeObservability({ handoffs: { total: 3, delivered: 2, failed: 1 }, openAlerts: 4, privacy: { voterChoiceMetrics: false, receiptLookup: false } });
    check(observation.handoffs.delivered === 2 && observation.openAlerts === 4, 'observability normalization is incorrect');
    check(!observation.voterChoiceMetrics && !observation.receiptLookup, 'privacy telemetry flags are incorrect');
    const catalog = model.normalizeCatalog({ adapters: [{ key: 'dashboard', mode: 'read_only', automaticMutation: false, canVote: false }] });
    check(catalog.length === 1 && catalog[0].key === 'dashboard' && !catalog[0].automaticMutation, 'catalog normalization is incorrect');
    const preview = model.normalizePreview({ previewHash: 'a'.repeat(64), confirmation: 'CONFIRM', externalMutation: false, payload: { targetAdapter: 'dashboard', resultHash: 'b'.repeat(64), containsVoterIdentity: false, containsBallotChoice: false, externalMutation: false } });
    check(preview && !preview.externalMutation && !preview.payload.containsVoterIdentity && !preview.payload.containsBallotChoice, 'handoff preview privacy flags are incorrect');
    check(model.normalizePreview(null) === null, 'missing preview must remain unavailable');
    check(model.evidenceTimeline(acceptance, [{ type: 'handoff', at: new Date(Date.now() + 1000).toISOString(), title: 'receipt' }])[0].type === 'handoff', 'evidence timeline ordering is incorrect');

    for (const excluded of ['backend/routes/**', 'api/**', 'backend/migrations/**', 'shared/**']) check(preflightDoc.includes(excluded), `excluded scope missing: ${excluded}`);
    check(preflightDoc.includes('d0a9b08e3f3b4a230de3991ef663a25daeacdbe5'), 'input baseline is missing');
    check(preflightDoc.includes('immutableSource=false'), 'immutable-source HOLD is missing');
    check(preflightDoc.includes('GO_FOR_UX_PHASE7_LOCAL_IMPLEMENTATION'), 'preflight decision is missing');

    console.log(`Safety Vote UX Phase 7 static/unit/accessibility/scope contract: PASS (${checks} assertions)`);
})().catch(error => { console.error(error.stack || error); process.exitCode = 1; });
