'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),{spawnSync}=require('child_process');
const p2=require('../services/safety-vote-phase2'),root=path.resolve(__dirname,'..','..'),php=process.env.PHP_BIN||'C:\\xampp\\php\\php.exe';
const questions=[{questionCode:'Q1',questionType:'single_choice',title:'Best image',minSelections:1,maxSelections:1,options:[{optionCode:'A',label:'Image A'},{optionCode:'B',label:'Image B'}]},{questionCode:'Q2',questionType:'multiple_choice',title:'Strengths',minSelections:1,maxSelections:2,options:[{label:'Safe'},{label:'Clear'},{label:'Creative'}]}];
const resolvedQuestions=[{id:10,questionType:'single_choice',isRequired:true,minSelections:1,maxSelections:1,options:[{id:101},{id:102}]},{id:20,questionType:'multiple_choice',isRequired:true,minSelections:1,maxSelections:2,options:[{id:201},{id:202},{id:203}]}];
const answers=[{questionId:10,optionIds:[101]},{questionId:20,optionIds:[201,203]}],employees=[{employeeId:'E002',departmentId:2,safetyUnitId:20,positionId:200,role:'User',team:'B',accountReady:true},{employeeId:'E001',departmentId:1,safetyUnitId:10,positionId:100,role:'Admin',team:'A',accountReady:true}];
const fixture={questions,resolvedQuestions,answers,employees,hashInput:{z:2,a:{d:4,b:1}},transitions:[['Draft','Open'],['Open','Closed'],['Closed','Published'],['Open','Published']]};
const builder=p2.normalizeBuilder(questions),node={builder,answers:p2.validateAnswers(resolvedQuestions,answers),hash:p2.hash(fixture.hashInput),rowsHash:p2.rowsHash(employees),transitions:fixture.transitions.map(x=>p2.canTransition(...x))};
const run=spawnSync(php,[path.join(root,'api','tests','safety_vote_phase2_fixture_runner.php')],{input:JSON.stringify(fixture),encoding:'utf8',windowsHide:true});assert.strictEqual(run.status,0,run.stderr);assert.deepStrictEqual(JSON.parse(run.stdout),node,'Phase 2 Node/PHP contract mismatch');
const nr=fs.readFileSync(path.join(root,'backend','routes','safety-vote-phase2.js'),'utf8'),pr=fs.readFileSync(path.join(root,'api','handlers','safety_vote_phase2.php'),'utf8'),migration=fs.readFileSync(path.join(root,'backend','migrations','20261008_safety_vote_phase2_core_mvp.sql'),'utf8'),main=fs.readFileSync(path.join(root,'public','js','main.js'),'utf8');
for(const source of [nr,pr]){assert.doesNotMatch(source,/\b(CREATE|ALTER|DROP|TRUNCATE)\s+TABLE\b/i);assert.doesNotMatch(source,/(router\.(put|patch|delete)|\$method==='(?:PUT|PATCH|DELETE)').{0,180}ballot/is,'Accepted ballot mutation route detected');}
assert.match(migration,/SafetyVote_BallotIdentities/);assert.match(migration,/UNIQUE KEY uq_sv_participation/);assert.match(migration,/UNIQUE KEY uq_sv_request_key/);assert.match(main,/refreshSafetyVoteNavigation/);assert.match(main,/moduleEnabled/);
console.log('Safety Vote Phase 2 contract/static parity: PASS (builder, answers, hashes, transitions, no runtime DDL or accepted-ballot mutation, preflight-gated menu)');
