'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),{spawnSync}=require('child_process');
const rules=require('../services/safety-vote-planning'),root=path.resolve(__dirname,'..','..'),read=file=>fs.readFileSync(path.join(root,file),'utf8');let checks=0;const ok=(value,message)=>{assert(value,message);checks++;};
const saved=rules.normalizeSavedView({name:'เดือนนี้',isDefault:true,filters:{month:'2026-10',status:['Open'],sort:'open_asc',unknown:'drop'}});ok(saved.ok&&saved.value.isDefault,'saved view valid');ok(!('unknown'in saved.value.filters),'saved view allowlist');
const raw={version:{campaignType:'survey',privacyMode:'identified',titleTh:'ต้นแบบ'},questions:[{questionCode:'Q1',title:'เลือก',options:[{optionCode:'O1',label:'หนึ่ง',fileId:99,media:[{url:'https://example.test'}]}]}],rules:[{attributeKey:'department',values:['Safety']},{attributeKey:'employee_id',values:['SV-USER']}]};
const safe=rules.safeTemplateConfig(raw);ok(safe.questions[0].options[0].fileId===null&&safe.questions[0].options[0].media.length===0,'template strips assets');ok(safe.rules.length===1&&safe.rules[0].attributeKey==='department','template strips employee rules');ok(rules.sha256(safe).length===64,'template SHA-256');
ok(rules.normalizeNotificationPreview({campaignId:1,audience:'eligible',channel:'in_app',title:'แจ้งเตือน',message:'ข้อความ',scheduledAt:'2026-10-10T10:00'}).value.quietHoursBlocked===false,'day schedule allowed');ok(rules.normalizeNotificationPreview({campaignId:1,audience:'eligible',channel:'email',title:'แจ้งเตือน',message:'ข้อความ',scheduledAt:'2026-10-10T22:00'}).value.quietHoursBlocked===true,'quiet hours blocked');
const php=`require '${path.join(root,'api','lib','safety_vote_phase1.php').replace(/\\/g,'/')}';require '${path.join(root,'api','lib','safety_vote_planning.php').replace(/\\/g,'/')}';echo json_encode([svpl_saved_view(json_decode($argv[1],true)),svpl_safe_template(json_decode($argv[2],true)),svpl_notification_preview(json_decode($argv[3],true))]);`;
const run=spawnSync(process.env.PHP_BIN||'C:\\xampp\\php\\php.exe',['-r',php,JSON.stringify({name:'เดือนนี้',isDefault:true,filters:{month:'2026-10',status:['Open'],sort:'open_asc',unknown:'drop'}}),JSON.stringify(raw),JSON.stringify({campaignId:1,audience:'eligible',channel:'email',title:'แจ้งเตือน',message:'ข้อความ',scheduledAt:'2026-10-10T22:00'})],{encoding:'utf8',windowsHide:true});
if(run.error?.code==='EPERM'){const lib=read('api/lib/safety_vote_planning.php');ok(lib.includes('SVPL_CONTRACT'),'PHP contract marker');ok(lib.includes("['employee','employee_id','employeeid']"),'PHP identity-rule exclusion');ok(lib.includes('$hour>=21||$hour<7'),'PHP quiet-hours contract');}else{assert.strictEqual(run.status,0,run.error?.message||run.stderr);const parsed=JSON.parse(run.stdout);ok(parsed[0].ok&&parsed[0].value.name===saved.value.name,'Node/PHP saved parity');ok(parsed[1].questions[0].options[0].fileId===null&&parsed[1].rules.length===1,'Node/PHP template parity');ok(parsed[2].value.quietHoursBlocked===true,'Node/PHP quiet parity');}
const migration=read('backend/migrations/20261010_safety_vote_ux_phase9b_planning_content_communication.sql'),rollback=read('backend/migrations/20261010_safety_vote_ux_phase9b_planning_content_communication.rollback.sql');ok(migration.includes('SafetyVote_AdminSavedViews')&&migration.includes('SafetyVote_CampaignTemplates'),'additive planning tables');ok(migration.includes("('engagement_enabled','0'")&&!migration.includes("('schema_version'"),'engagement default OFF and core schema unchanged');ok(!/DROP\s+TABLE|DELETE\s+FROM/i.test(rollback)&&rollback.includes("'engagement_enabled','0'"),'data-preserving rollback');
const node=read('backend/routes/safety-vote-planning.js'),phpRoute=read('api/handlers/safety_vote_planning.php');for(const marker of ['/admin/planning/overview','/admin/planning/saved-views','/config-copy','/templates/from-campaign/','/assets','/notifications/preview']){ok(node.includes(marker),`Node ${marker}`);ok(phpRoute.includes(marker),`PHP ${marker}`);}for(const source of[node,phpRoute]){ok(source.includes('SAFETY_VOTE_MANAGE'),'existing capability reused');ok(source.includes('engagement_enabled'),'independent server gate');ok(source.includes('ASSET_ALT_TEXT_REQUIRED'),'asset accessibility gate');ok(!/UPDATE\s+SafetyVote_(Ballots|BallotAnswers|JuryScores|Results|Certifications)/i.test(source),'no protected logic mutation');}
const ui=read('public/js/pages/admin-safety-vote-planning.js'),admin=read('public/js/pages/admin-safety-vote-ux1.js'),main=read('public/js/main.js'),index=read('index.html'),css=read('public/style.css');for(const marker of['ปฏิทินแคมเปญ','มุมมองที่บันทึกไว้','แม่แบบและการคัดลอกค่า','คลังภาพประชาสัมพันธ์','ตัวอย่างหน้าผู้เข้าร่วมและกรรมการ','ลิงก์และ QR ของกิจกรรม','Notification composer'])ok(ui.includes(marker),marker);ok(ui.includes('/notifications/queue')&&!ui.includes('/notifications/dispatch'),'composer reuses queue without dispatcher');ok(admin.includes('renderSafetyVotePlanningWorkspace')&&admin.includes('data-sv-workspace="planning"'),'Admin planning workspace integration');ok(main.includes('safety-vote=')&&/safetyVoteEngagementV1:\s*(true|false)/.test(index),'share route and explicit client flag');ok(css.includes('.sv-planning')&&css.includes('min-height: 44px')&&css.includes(':focus-visible'),'responsive accessible CSS');
console.log(`Safety Vote UX Phase 9B static + Node/PHP parity: PASS (${checks} assertions)`);
