CREATE TABLE IF NOT EXISTS accident_hotspot_layout (
    id          TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    FileURL     VARCHAR(1000) NOT NULL,
    FileName    VARCHAR(255) NOT NULL,
    FileType    VARCHAR(100) NOT NULL,
    FileSize    BIGINT UNSIGNED NOT NULL DEFAULT 0,
    UpdatedBy   VARCHAR(100) DEFAULT NULL,
    UpdatedAt   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
