'use strict';

const TRAINING_LOG_ACTIONS = Object.freeze([
    'COURSE_MASTER_CREATE', 'COURSE_MASTER_UPDATE', 'COURSE_MASTER_DISABLE', 'COURSE_MASTER_DELETE',
    'CURRICULUM_CREATE', 'CURRICULUM_CODE_BULK_UPDATE', 'CURRICULUM_UPDATE', 'CURRICULUM_DISABLE',
    'COURSE_CREATE', 'COURSE_RESTORE', 'COURSE_UPDATE', 'COURSE_DISABLE',
    'CURRICULUM_ASSIGNMENT_CREATE', 'CURRICULUM_ASSIGNMENT_REASSIGN',
    'CURRICULUM_ASSIGNMENT_REMOVE', 'CURRICULUM_ASSIGNMENT_TRANSFER',
    'ASSIGNMENT_CREATE', 'ASSIGNMENT_REASSIGN', 'ASSIGNMENT_UPDATE', 'ASSIGNMENT_REMOVE', 'ASSIGNMENT_TRANSFER',
]);
const LEGACY_TRAINING_LOG_ACTIONS = Object.freeze(['COURSE_LINK']);

module.exports = { TRAINING_LOG_ACTIONS, LEGACY_TRAINING_LOG_ACTIONS };
