<?php
declare(strict_types=1);

function bbs_analytics_actor(array $user): string { return trim((string)($user['id'] ?? $user['EmployeeID'] ?? '')); }
function bbs_analytics_admin(array $user): bool { return strcasecmp((string)($user['role'] ?? $user['Role'] ?? ''),'Admin')===0; }
function bbs_analytics_num($value): float { return is_numeric($value)?(float)$value:0.0; }
function bbs_analytics_pct($n,$d): float { $den=bbs_analytics_num($d);return$den>0?round(bbs_analytics_num($n)*10000/$den)/100:0.0; }
function bbs_analytics_int($value): ?int { $v=filter_var($value,FILTER_VALIDATE_INT);return$v!==false&&$v>0?(int)$v:null; }
function bbs_analytics_today(): string { return(new DateTimeImmutable('now',new DateTimeZone('Asia/Bangkok')))->format('Y-m-d'); }
function bbs_analytics_context(array $user): ?array { return db_row("SELECT e.EmployeeID,e.EmployeeName,e.Department,e.Unit,e.Position,md.id DepartmentID,su.id SafetyUnitID,m.BBSLevel FROM employees e LEFT JOIN master_departments md ON LOWER(TRIM(md.Name))=LOWER(TRIM(e.Department)) LEFT JOIN master_safetyunits su ON su.department_id=md.id AND LOWER(TRIM(su.name))=LOWER(TRIM(e.Unit)) LEFT JOIN master_positions p ON LOWER(TRIM(p.Name))=LOWER(TRIM(e.Position)) LEFT JOIN BBS_Position_Level_Mappings m ON m.PositionID=p.id AND m.IsActive=1 WHERE e.EmployeeID=? LIMIT 1",[bbs_analytics_actor($user)]); }
function bbs_analytics_scopes(array $user,array $employee): array { if(bbs_analytics_admin($user))return['personal','team','department','company'];$scopes=['personal'];$rank=bbs_phase1_level_rank($employee['BBSLevel']??null);if($rank>=bbs_phase1_level_rank('Group Leader'))$scopes[]='team';if($rank>=bbs_phase1_level_rank('Department Head'))$scopes[]='department';return$scopes; }
function bbs_analytics_risk($value): string { foreach(['Critical','High','Medium','Low']as$item)if(strcasecmp($item,trim((string)$value))===0)return$item;return''; }
function bbs_analytics_range(int $year,int $month,?string $todayOverride=null): array { $start=sprintf('%04d-%02d-01',$year,$month?:1);$end=$month?(new DateTimeImmutable($start,new DateTimeZone('UTC')))->modify('+1 month')->format('Y-m-d'):sprintf('%04d-01-01',$year+1);$today=$todayOverride?:bbs_analytics_today();$through=$today<$start?$start:($today>=$end?(new DateTimeImmutable($end))->modify('-1 day')->format('Y-m-d'):$today);return['start'=>$start,'end'=>$end,'through'=>$through]; }
function bbs_analytics_resolve(array $user): array {
    $settingRows=db_rows("SELECT SettingKey,SettingValue FROM BBS_Settings WHERE SettingKey IN ('analytics_enabled','analytics_export_enabled')");$settings=[];foreach($settingRows as$row)$settings[$row['SettingKey']]=(string)$row['SettingValue'];if(($settings['analytics_enabled']??'0')!=='1')return['error'=>[503,'BBS analytics is currently disabled.']];
    $employee=bbs_analytics_context($user);if(!$employee)return['error'=>[404,'Employee is not available in Employee Master.']];$scopes=bbs_analytics_scopes($user,$employee);$default=bbs_analytics_admin($user)?'company':$scopes[count($scopes)-1];$scope=strtolower(trim((string)($_GET['scope']??$default)));if(!in_array($scope,$scopes,true))return['error'=>[403,'The requested analytics scope is outside your BBS hierarchy permission.']];
    $year=(int)($_GET['year']??date('Y'));if($year<2000||$year>2100)$year=(int)date('Y');$month=(int)($_GET['month']??0);if($month<0||$month>12)$month=0;$risk=bbs_analytics_risk($_GET['risk']??'');$range=bbs_analytics_range($year,$month);$departmentId=bbs_analytics_int($_GET['departmentId']??null);$unitId=bbs_analytics_int($_GET['safetyUnitId']??null);
    if(!bbs_analytics_admin($user)&&$scope==='department')$departmentId=(int)($employee['DepartmentID']??0)?:null;if(!bbs_analytics_admin($user)&&$scope==='personal'){$departmentId=(int)($employee['DepartmentID']??0)?:null;$unitId=(int)($employee['SafetyUnitID']??0)?:null;}
    if($scope==='team'){$assigned=db_rows("SELECT DISTINCT DepartmentID,SafetyUnitID FROM BBS_Hierarchy_Assignments WHERE SupervisorEmployeeID=? AND IsActive=1 AND EffectiveFrom<=? AND COALESCE(EffectiveTo,'9999-12-31')>=?",[bbs_analytics_actor($user),$range['through'],$range['start']]);if(!$assigned&&!bbs_analytics_admin($user))return['error'=>[403,'No active BBS team assignment is available for this period.']];if($departmentId&&!array_filter($assigned,fn($r)=>(int)$r['DepartmentID']===$departmentId))return['error'=>[403,'Department filter is outside your assigned team.']];if($unitId&&!array_filter($assigned,fn($r)=>(int)$r['SafetyUnitID']===$unitId))return['error'=>[403,'Safety Unit filter is outside your assigned team.']];}
    if($unitId){$unit=db_row('SELECT id,department_id FROM master_safetyunits WHERE id=? LIMIT 1',[$unitId]);if(!$unit||($departmentId&&(int)$unit['department_id']!==$departmentId))return['error'=>[400,'Safety Unit does not belong to the selected Department.']];$departmentId=$departmentId?:((int)$unit['department_id']);}
    $exportEnabled=($settings['analytics_export_enabled']??'0')==='1';return compact('employee','scopes','scope','year','month','risk','range','departmentId','unitId','exportEnabled');
}
function bbs_analytics_where(array $user,array $f,string $alias='o'): array {
    $where=["$alias.Status='Submitted'","$alias.ObservationDate>=?","$alias.ObservationDate<?"];$params=[$f['range']['start'],$f['range']['end']];$actor=bbs_analytics_actor($user);
    if($f['scope']==='personal'){$where[]="($alias.ObserverEmployeeID=? OR $alias.ObservedEmployeeID=?)";$params[]=$actor;$params[]=$actor;}
    elseif($f['scope']==='team'){$where[]="EXISTS(SELECT 1 FROM BBS_Hierarchy_Assignments h WHERE h.SupervisorEmployeeID=? AND h.MemberEmployeeID=$alias.ObservedEmployeeID AND h.DepartmentID=$alias.ObservedDepartmentID AND h.IsActive=1 AND h.EffectiveFrom<=$alias.ObservationDate AND COALESCE(h.EffectiveTo,'9999-12-31')>=$alias.ObservationDate)";$params[]=$actor;}
    elseif($f['scope']==='department'){$where[]="$alias.ObservedDepartmentID=?";$params[]=$f['departmentId']?:$f['employee']['DepartmentID'];}
    if($f['departmentId']&&$f['scope']!=='department'&&$f['scope']!=='personal'){$where[]="$alias.ObservedDepartmentID=?";$params[]=$f['departmentId'];}if($f['unitId']){$where[]="$alias.ObservedSafetyUnitID=?";$params[]=$f['unitId'];}if($f['risk']!==''){$where[]="EXISTS(SELECT 1 FROM BBS_Corrective_Actions risk_ca WHERE risk_ca.ObservationID=$alias.id AND risk_ca.Priority=?)";$params[]=$f['risk'];}return['sql'=>implode(' AND ',$where),'params'=>$params];
}
function bbs_analytics_options(array $user,array $f): array {
    $where='1=1';$params=[];if(!bbs_analytics_admin($user)&&in_array('department',$f['scopes'],true)){$where='d.id=?';$params=[$f['employee']['DepartmentID']];}elseif(!bbs_analytics_admin($user)&&in_array('team',$f['scopes'],true)){$where="EXISTS(SELECT 1 FROM BBS_Hierarchy_Assignments h WHERE h.SupervisorEmployeeID=? AND h.DepartmentID=d.id AND h.IsActive=1 AND h.EffectiveFrom<=CURDATE() AND COALESCE(h.EffectiveTo,'9999-12-31')>=CURDATE())";$params=[bbs_analytics_actor($user)];}elseif(!bbs_analytics_admin($user)){$where='d.id=?';$params=[$f['employee']['DepartmentID']];}$departments=db_rows("SELECT d.id,d.Name FROM master_departments d WHERE $where ORDER BY d.Name",$params);if(!$departments&&!empty($f['employee']['DepartmentID']))$departments=[['id'=>$f['employee']['DepartmentID'],'Name'=>$f['employee']['Department']]];$ids=array_values(array_filter(array_map(fn($r)=>(int)$r['id'],$departments)));$units=[];if($ids){$units=db_rows('SELECT id,name,department_id FROM master_safetyunits WHERE department_id IN ('.implode(',',array_fill(0,count($ids),'?')).') ORDER BY department_id,sort_order,name',$ids);}$years=db_row("SELECT MIN(YEAR(ObservationDate)) minYear,MAX(YEAR(ObservationDate)) maxYear FROM BBS_Observations WHERE Status='Submitted'")?:[];return['scopes'=>$f['scopes'],'departments'=>$departments,'units'=>$units,'risks'=>['Critical','High','Medium','Low'],'years'=>['min'=>(int)($years['minYear']??$f['year']),'max'=>(int)($years['maxYear']??$f['year'])]];
}
function bbs_analytics_required_dates(array $range,string $weekdays): array { $allowed=array_flip(bbs_phase1_weekdays($weekdays));$rows=[];if($range['through']<$range['start'])return[];for($date=new DateTimeImmutable($range['start']);$date->format('Y-m-d')<$range['end']&&$date->format('Y-m-d')<=$range['through'];$date=$date->modify('+1 day')){if(isset($allowed[(int)$date->format('N')]))$rows[]=$date->format('Y-m-d');}return$rows; }
function bbs_analytics_kpi(array $user,array $f,array $where): array {
    $sql="SELECT ie.id EnrollmentID,e.EmployeeID,e.EmployeeName,d.Name DepartmentName,u.name SafetyUnitName,r.TargetCount,r.Weekdays,ie.EffectiveFrom EnrollmentFrom,ie.EffectiveTo EnrollmentTo FROM employees e JOIN master_positions p ON LOWER(TRIM(p.Name))=LOWER(TRIM(e.Position)) JOIN BBS_Position_Level_Mappings m ON m.PositionID=p.id AND m.IsActive=1 JOIN BBS_KPI_Rules r ON r.BBSLevel=m.BBSLevel AND r.MetricKey='submitted_observation' AND r.IsActive=1 JOIN BBS_Inspector_Enrollments ie ON ie.InspectorEmployeeID=e.EmployeeID AND ie.Status='Active' AND ie.KpiRequired=1 AND ie.IsActive=1 AND ie.EffectiveFrom<? AND COALESCE(ie.EffectiveTo,'9999-12-31')>=? LEFT JOIN master_departments d ON LOWER(TRIM(d.Name))=LOWER(TRIM(e.Department)) LEFT JOIN master_safetyunits u ON u.department_id=d.id AND LOWER(TRIM(u.name))=LOWER(TRIM(e.Unit)) WHERE 1=1";$params=[$f['range']['end'],$f['range']['start']];
    if(in_array($f['scope'],['personal','team'],true)){$sql.=' AND e.EmployeeID=?';$params[]=bbs_analytics_actor($user);}elseif($f['scope']==='department'){$sql.=' AND d.id=?';$params[]=$f['departmentId']?:$f['employee']['DepartmentID'];}else{if($f['departmentId']){$sql.=' AND d.id=?';$params[]=$f['departmentId'];}if($f['unitId']){$sql.=' AND u.id=?';$params[]=$f['unitId'];}}
    $people=db_rows($sql,$params);$actualRows=db_rows("SELECT o.ObserverEmployeeID,o.ObservationDate,COUNT(*) ActualCount FROM BBS_Observations o WHERE {$where['sql']} GROUP BY o.ObserverEmployeeID,o.ObservationDate",$where['params']);if(!$people)return['numerator'=>0,'denominator'=>0,'percentage'=>0,'peopleMeeting'=>0,'peopleTotal'=>0,'people'=>[]];
    $ids=array_map(static fn($row)=>(int)$row['EnrollmentID'],$people);$marks=implode(',',array_fill(0,count($ids),'?'));$rules=db_rows("SELECT * FROM BBS_Inspector_Schedule_Rules WHERE EnrollmentID IN ($marks) AND Status='Active' AND EffectiveFrom<? AND COALESCE(EffectiveTo,'9999-12-31')>=?",array_merge($ids,[$f['range']['end'],$f['range']['start']]));$overrides=db_rows("SELECT * FROM BBS_Inspector_Schedule_Overrides WHERE EnrollmentID IN ($marks) AND ScheduleDate>=? AND ScheduleDate<? AND IsActive=1",array_merge($ids,[$f['range']['start'],$f['range']['end']]));foreach($people as&$person){$person['InspectorEmployeeID']=$person['EmployeeID'];$person['InspectorName']=$person['EmployeeName'];}unset($person);$range=$f['range'];$range['today']=$range['through'];$compliance=bbs_schedule_compliance($people,$rules,$overrides,$actualRows,$range);$out=array_map(static fn($row)=>['employeeId'=>$row['inspectorEmployeeId'],'employeeName'=>$row['inspectorName'],'numerator'=>$row['numerator'],'denominator'=>$row['denominator'],'percentage'=>$row['denominator']?$row['percentage']:null],$compliance['people']);$meeting=count(array_filter($compliance['people'],static fn($row)=>$row['denominator']>0&&$row['percentage']>=100));
    return['numerator'=>$compliance['summary']['numerator'],'denominator'=>$compliance['summary']['denominator'],'percentage'=>$compliance['summary']['denominator']?$compliance['summary']['percentage']:null,'peopleMeeting'=>$meeting,'peopleTotal'=>count($out),'formula'=>'Capped submitted observations / effective inspector schedule target','people'=>$out];
}
function bbs_analytics_aging($days): string { $v=max(0,(int)$days);return$v<=3?'0-3 days':($v<=7?'4-7 days':($v<=14?'8-14 days':'15+ days')); }
function bbs_analytics_merge(array $obs,array $actions): array { $map=[];foreach($obs as$row){$key=(int)($row['DepartmentID']??0).':'.(int)($row['SafetyUnitID']??0);$map[$key]=['departmentId'=>(int)($row['DepartmentID']??0),'safetyUnitId'=>(int)($row['SafetyUnitID']??0),'department'=>$row['Department']??'-','unit'=>$row['Unit']??'-','observations'=>(int)$row['Observations'],'safe'=>(int)$row['SafeCount'],'unsafe'=>(int)$row['UnsafeCount'],'na'=>(int)$row['NACount'],'actionOpen'=>0,'actionOverdue'=>0];}foreach($actions as$row){$key=(int)($row['DepartmentID']??0).':'.(int)($row['SafetyUnitID']??0);if(!isset($map[$key]))$map[$key]=['departmentId'=>(int)($row['DepartmentID']??0),'safetyUnitId'=>(int)($row['SafetyUnitID']??0),'department'=>$row['Department']??'-','unit'=>$row['Unit']??'-','observations'=>0,'safe'=>0,'unsafe'=>0,'na'=>0,'actionOpen'=>0,'actionOverdue'=>0];$map[$key]['actionOpen']=(int)$row['ActionOpen'];$map[$key]['actionOverdue']=(int)$row['ActionOverdue'];}foreach($map as&$row)$row['unsafeRate']=bbs_analytics_pct($row['unsafe'],$row['safe']+$row['unsafe']);unset($row);$rows=array_values($map);usort($rows,fn($a,$b)=>$b['unsafeRate']<=>$a['unsafeRate']?:$b['observations']<=>$a['observations']);return$rows; }
function bbs_analytics_payload(array $user,array $f,bool $details=false): array {
    $where=bbs_analytics_where($user,$f);$period=$f['month']?'DAY(o.ObservationDate)':'MONTH(o.ObservationDate)';$trend=db_rows("SELECT $period PeriodNo,COUNT(DISTINCT o.id) Observations,SUM(a.Response='Safe') SafeCount,SUM(a.Response='Unsafe') UnsafeCount,SUM(a.Response='N/A') NACount FROM BBS_Observations o LEFT JOIN BBS_Observation_Answers a ON a.ObservationID=o.id WHERE {$where['sql']} GROUP BY PeriodNo ORDER BY PeriodNo",$where['params']);$pareto=db_rows("SELECT a.CategoryNameSnapshot Category,COUNT(*) Total,SUM(a.Response='Unsafe') UnsafeCount FROM BBS_Observations o JOIN BBS_Observation_Answers a ON a.ObservationID=o.id WHERE {$where['sql']} GROUP BY a.CategoryNameSnapshot ORDER BY UnsafeCount DESC,Total DESC,Category LIMIT 20",$where['params']);$comparison=db_rows("SELECT o.ObservedDepartmentID DepartmentID,o.ObservedSafetyUnitID SafetyUnitID,MAX(o.ObservedDepartmentSnapshot) Department,MAX(o.ObservedUnitSnapshot) Unit,COUNT(DISTINCT o.id) Observations,SUM(a.Response='Safe') SafeCount,SUM(a.Response='Unsafe') UnsafeCount,SUM(a.Response='N/A') NACount FROM BBS_Observations o LEFT JOIN BBS_Observation_Answers a ON a.ObservationID=o.id WHERE {$where['sql']} GROUP BY o.ObservedDepartmentID,o.ObservedSafetyUnitID",$where['params']);
    $actionParams=$where['params'];$riskSql='';if($f['risk']!==''){$riskSql=' AND ca.Priority=?';$actionParams[]=$f['risk'];}$action=db_row("SELECT COUNT(*) Total,SUM(ca.Status='Open') OpenCount,SUM(ca.Status='In Progress') InProgressCount,SUM(ca.Status='Pending Verification') PendingVerificationCount,SUM(ca.Status='Closed') ClosedCount,SUM(ca.Status<>'Closed' AND ca.DueDate<CURDATE()) OverdueCount,AVG(CASE WHEN ca.Status='Closed' THEN DATEDIFF(ca.ClosedAt,ca.CreatedAt) END) AvgClosureDays FROM BBS_Corrective_Actions ca JOIN BBS_Observations o ON o.id=ca.ObservationID WHERE {$where['sql']}$riskSql",$actionParams)?:[];$actionRows=db_rows("SELECT DATEDIFF(COALESCE(ca.ClosedAt,CURDATE()),ca.CreatedAt) AgeDays FROM BBS_Corrective_Actions ca JOIN BBS_Observations o ON o.id=ca.ObservationID WHERE {$where['sql']}$riskSql",$actionParams);$actionComparison=db_rows("SELECT o.ObservedDepartmentID DepartmentID,o.ObservedSafetyUnitID SafetyUnitID,MAX(o.ObservedDepartmentSnapshot) Department,MAX(o.ObservedUnitSnapshot) Unit,SUM(ca.Status<>'Closed') ActionOpen,SUM(ca.Status<>'Closed' AND ca.DueDate<CURDATE()) ActionOverdue FROM BBS_Corrective_Actions ca JOIN BBS_Observations o ON o.id=ca.ObservationID WHERE {$where['sql']}$riskSql GROUP BY o.ObservedDepartmentID,o.ObservedSafetyUnitID",$actionParams);
    $recent=db_rows("SELECT o.id,o.ObservationNo,o.ObservationDate,o.ObserverEmployeeID,o.ObserverNameSnapshot,o.ObservedEmployeeID,o.ObservedNameSnapshot,o.ObservedDepartmentSnapshot,o.ObservedUnitSnapshot,SUM(a.Response='Safe') SafeCount,SUM(a.Response='Unsafe') UnsafeCount,SUM(a.Response='N/A') NACount,(SELECT COUNT(*) FROM BBS_Corrective_Actions ca WHERE ca.ObservationID=o.id AND ca.Status<>'Closed') OpenActions FROM BBS_Observations o LEFT JOIN BBS_Observation_Answers a ON a.ObservationID=o.id WHERE {$where['sql']} GROUP BY o.id ORDER BY o.ObservationDate DESC,o.id DESC LIMIT ".($details?5000:12),$where['params']);
    $trendOut=[];$totals=['observations'=>0,'safe'=>0,'unsafe'=>0,'na'=>0];foreach($trend as$row){$entry=['period'=>(int)$row['PeriodNo'],'label'=>$f['month']?(string)$row['PeriodNo']:date('M',mktime(0,0,0,(int)$row['PeriodNo'],1,2000)),'observations'=>(int)$row['Observations'],'safe'=>(int)$row['SafeCount'],'unsafe'=>(int)$row['UnsafeCount'],'na'=>(int)$row['NACount']];foreach(['observations','safe','unsafe','na']as$key)$totals[$key]+=$entry[$key];$trendOut[]=$entry;}$totals['unsafeRate']=bbs_analytics_pct($totals['unsafe'],$totals['safe']+$totals['unsafe']);$paretoOut=array_map(fn($r)=>['category'=>$r['Category'],'total'=>(int)$r['Total'],'unsafe'=>(int)$r['UnsafeCount'],'unsafeRate'=>bbs_analytics_pct($r['UnsafeCount'],$r['Total'])],$pareto);$heatmap=array_map(fn($r)=>['departmentId'=>(int)($r['DepartmentID']??0),'safetyUnitId'=>(int)($r['SafetyUnitID']??0),'department'=>$r['Department']??'-','unit'=>$r['Unit']??'-','observations'=>(int)$r['Observations'],'safe'=>(int)$r['SafeCount'],'unsafe'=>(int)$r['UnsafeCount'],'na'=>(int)$r['NACount'],'unsafeRate'=>bbs_analytics_pct($r['UnsafeCount'],(int)$r['SafeCount']+(int)$r['UnsafeCount'])],$comparison);$aging=['0-3 days'=>0,'4-7 days'=>0,'8-14 days'=>0,'15+ days'=>0];foreach($actionRows as$row)$aging[bbs_analytics_aging($row['AgeDays'])]++;$actions=['total'=>(int)($action['Total']??0),'open'=>(int)($action['OpenCount']??0),'inProgress'=>(int)($action['InProgressCount']??0),'pendingVerification'=>(int)($action['PendingVerificationCount']??0),'closed'=>(int)($action['ClosedCount']??0),'overdue'=>(int)($action['OverdueCount']??0),'closureRate'=>bbs_analytics_pct($action['ClosedCount']??0,$action['Total']??0),'avgClosureDays'=>round(bbs_analytics_num($action['AvgClosureDays']??0),1),'aging'=>array_map(fn($k,$v)=>['bucket'=>$k,'count'=>$v],array_keys($aging),array_values($aging))];
    return['meta'=>['scope'=>$f['scope'],'year'=>$f['year'],'month'=>$f['month'],'departmentId'=>$f['departmentId'],'safetyUnitId'=>$f['unitId'],'risk'=>$f['risk'],'periodStart'=>$f['range']['start'],'periodEnd'=>$f['range']['end'],'periodThrough'=>$f['range']['through'],'generatedAt'=>(new DateTimeImmutable())->format(DateTimeInterface::ATOM),'detailCount'=>count($recent)],'permissions'=>['scopes'=>$f['scopes'],'canCompany'=>bbs_analytics_admin($user),'canExport'=>$f['exportEnabled']],'options'=>bbs_analytics_options($user,$f),'kpi'=>bbs_analytics_kpi($user,$f,$where),'totals'=>$totals,'trend'=>$trendOut,'pareto'=>$paretoOut,'heatmap'=>$heatmap,'actions'=>$actions,'comparison'=>bbs_analytics_merge($comparison,$actionComparison),'recent'=>$recent];
}
function handle_bbs_analytics_routes(string $method,string $path): bool {
    if(strpos($path,'/bbs/analytics')!==0)return false;$user=require_user();if($method==='GET'&&$path==='/bbs/analytics'){$f=bbs_analytics_resolve($user);if(isset($f['error']))json_response(['success'=>false,'message'=>$f['error'][1]],$f['error'][0]);json_response(['success'=>true,'data'=>bbs_analytics_payload($user,$f)]);}
    if($method==='GET'&&$path==='/bbs/analytics/export-data'){$f=bbs_analytics_resolve($user);if(isset($f['error']))json_response(['success'=>false,'message'=>$f['error'][1]],$f['error'][0]);if(empty($f['exportEnabled']))json_response(['success'=>false,'message'=>'BBS analytics export is currently disabled.'],403);$data=bbs_analytics_payload($user,$f,true);if(bbs_analytics_admin($user))bbs_phase1_audit($user,'BBS_ANALYTICS_EXPORT','BBS_Analytics',$f['scope'].':'.$f['year'].':'.$f['month'],'department='.($f['departmentId']?:'all').'; unit='.($f['unitId']?:'all').'; risk='.($f['risk']?:'all').'; rows='.count($data['recent']));json_response(['success'=>true,'data'=>$data]);}
    if($method==='GET'&&$path==='/bbs/analytics/drilldown'){$f=bbs_analytics_resolve($user);if(isset($f['error']))json_response(['success'=>false,'message'=>$f['error'][1]],$f['error'][0]);$metric=(string)($_GET['metric']??'observations');if(!in_array($metric,['observations','safe','unsafe','actions','overdue'],true))json_response(['success'=>false,'message'=>'Unsupported drill-down metric.'],400);$data=bbs_analytics_payload($user,$f,true);$rows=$data['recent'];if($metric==='unsafe')$rows=array_values(array_filter($rows,fn($r)=>(int)$r['UnsafeCount']>0));if($metric==='safe')$rows=array_values(array_filter($rows,fn($r)=>(int)$r['SafeCount']>0));if($metric==='actions')$rows=array_values(array_filter($rows,fn($r)=>(int)$r['OpenActions']>0));if($metric==='overdue'){$where=bbs_analytics_where($user,$f);$params=$where['params'];$riskSql='';if($f['risk']!==''){$riskSql=' AND ca.Priority=?';$params[]=$f['risk'];}$rows=db_rows("SELECT o.id,o.ObservationNo,o.ObservationDate,o.ObserverEmployeeID,o.ObserverNameSnapshot,o.ObservedEmployeeID,o.ObservedNameSnapshot,o.ObservedDepartmentSnapshot,o.ObservedUnitSnapshot,COUNT(ca.id) OpenActions,SUM(ca.DueDate<CURDATE()) OverdueActions FROM BBS_Observations o JOIN BBS_Corrective_Actions ca ON ca.ObservationID=o.id AND ca.Status<>'Closed' WHERE {$where['sql']}$riskSql GROUP BY o.id HAVING OverdueActions>0 ORDER BY o.ObservationDate DESC,o.id DESC LIMIT 500",$params);}if(bbs_analytics_admin($user))bbs_phase1_audit($user,'BBS_ANALYTICS_DRILLDOWN','BBS_Analytics',$metric,'scope='.$f['scope'].'; year='.$f['year'].'; rows='.count($rows));json_response(['success'=>true,'data'=>['meta'=>$data['meta'],'metric'=>$metric,'rows'=>$rows]]);}
    json_response(['success'=>false,'message'=>'BBS analytics route not found.'],404);return true;
}
