<?php
declare(strict_types=1);
require_once __DIR__.'/../lib/bbs_card_print_receipt.php';
require_once __DIR__ . '/bbs_list_query.php';

require_once __DIR__.'/../lib/bbs_card.php';
require_once __DIR__.'/../lib/bbs_community.php';
require_once __DIR__.'/bbs_smart_card.php';

function bbs_card_qr_limit(string $token): array {
    global $config;$ip=(string)($_SERVER['REMOTE_ADDR']??'unknown');$ipHash=hash('sha256',(string)$config['jwt_secret'].':'.$ip);$fingerprint=bbs_card_fingerprint($token);$setting=db_row("SELECT SettingValue FROM BBS_Settings WHERE SettingKey='qr_resolve_limit_5m' LIMIT 1");$limit=max(5,min(200,(int)($setting['SettingValue']??30)));$row=db_row('SELECT COUNT(*) count FROM BBS_QR_Resolve_Attempts WHERE IPHash=? AND AttemptedAt>=DATE_SUB(NOW(),INTERVAL 5 MINUTE)',[$ipHash]);return['allowed'=>(int)($row['count']??0)<$limit,'ipHash'=>$ipHash,'fingerprint'=>$fingerprint];
}
function bbs_card_record_resolve(array $state,bool $success): void { db_execute('INSERT INTO BBS_QR_Resolve_Attempts(IPHash,TokenFingerprint,Successful) VALUES(?,?,?)',[$state['ipHash'],$state['fingerprint'],$success?1:0]); }
function bbs_card_active_token(string $token,?PDO $pdo=null): ?array { $pdo=$pdo?:db();$stmt=$pdo->prepare("SELECT c.*,t.Status TemplateStatus FROM BBS_Cards c JOIN BBS_Card_Templates t ON t.id=c.TemplateID WHERE c.TokenHash=? AND c.Status='Active' AND t.Status='Active' LIMIT 1");$stmt->execute([bbs_card_hash($token)]);$row=$stmt->fetch();return$row?:null; }
function bbs_department_card_active_token(string $token,?PDO $pdo=null): ?array { $pdo=$pdo?:db();$stmt=$pdo->prepare("SELECT q.*,d.Name DepartmentName FROM BBS_Department_QR_Cards q JOIN master_departments d ON d.id=q.DepartmentID WHERE q.TokenHash=? AND q.Status='Active' LIMIT 1");$stmt->execute([bbs_card_hash($token)]);$row=$stmt->fetch();return$row?:null; }
function bbs_card_can_target(array $user,array $card): bool { $uid=(string)($user['id']??'');if(strcasecmp((string)($user['role']??''),'Admin')===0||strcasecmp($uid,(string)$card['EmployeeID'])===0)return true;$date=(new DateTimeImmutable('now',new DateTimeZone('Asia/Bangkok')))->format('Y-m-d');return(bool)db_row("SELECT id FROM BBS_Hierarchy_Assignments WHERE SupervisorEmployeeID=? AND MemberEmployeeID=? AND IsActive=1 AND EffectiveFrom<=? AND (EffectiveTo IS NULL OR EffectiveTo>=?) LIMIT 1",[$uid,$card['EmployeeID'],$date,$date]); }
function bbs_card_designer_rendering_enabled(?PDO $pdo=null): bool { $pdo=$pdo?:db();$stmt=$pdo->prepare("SELECT SettingValue FROM BBS_Settings WHERE SettingKey='visual_card_designer_rendering_enabled' LIMIT 1");$stmt->execute();return(string)($stmt->fetch()['SettingValue']??'0')==='1'; }
function bbs_card_designer_safe_layout(array $version,array $sides,array $elements,array $assets): array { $assetByStored=[];foreach($assets as$asset)$assetByStored[(string)$asset['StoredName']]=(int)$asset['id'];return['layoutVersionId'=>(int)$version['id'],'versionNo'=>(int)$version['VersionNo'],'widthMM'=>(float)$version['WidthMM'],'heightMM'=>(float)$version['HeightMM'],'dpi'=>(int)$version['DPI'],'duplexFlip'=>(string)$version['DuplexFlip'],'backRotation'=>(int)$version['BackRotation'],'sides'=>array_map(fn($side)=>['side'=>(string)$side['Side'],'storageClass'=>(string)$side['StorageClass'],'backgroundAssetId'=>$side['StorageClass']==='DesignerAsset'?($assetByStored[(string)$side['BackgroundStoredName']]??null):null,'backgroundUrl'=>'/bbs/admin/card-designer/versions/'.(int)$version['id'].'/sides/'.strtolower((string)$side['Side']).'/background','backgroundFit'=>(string)$side['BackgroundFit'],'backgroundPositionXBP'=>(int)$side['BackgroundPositionXBP'],'backgroundPositionYBP'=>(int)$side['BackgroundPositionYBP'],'bleedMM'=>(float)$side['BleedMM'],'safeMarginMM'=>(float)$side['SafeMarginMM']],$sides),'elements'=>array_map(fn($element)=>['elementKey'=>(string)$element['ElementKey'],'side'=>(string)$element['Side'],'elementType'=>(string)$element['ElementType'],'dataSourceKey'=>$element['DataSourceKey']?:null,'staticText'=>$element['StaticText']?:null,'assetId'=>$element['AssetID']===null?null:(int)$element['AssetID'],'assetUrl'=>$element['AssetID']===null?null:'/bbs/admin/card-designer/assets/'.(int)$element['AssetID'].'/file','xBP'=>(int)$element['XBP'],'yBP'=>(int)$element['YBP'],'widthBP'=>(int)$element['WidthBP'],'heightBP'=>(int)$element['HeightBP'],'rotationDeg'=>(int)$element['RotationDeg'],'zIndex'=>(int)$element['ZIndex'],'visible'=>(bool)$element['Visible'],'style'=>json_decode((string)($element['StyleJSON']??'{}'),true)?:[]],$elements),'assets'=>array_map(fn($asset)=>['id'=>(int)$asset['id'],'assetKey'=>(string)$asset['AssetKey'],'originalName'=>(string)$asset['OriginalName'],'mimeType'=>(string)$asset['MimeType']],$assets)]; }
function bbs_card_active_personal_designer_layout(PDO $pdo,int $templateId): ?array { try{$stmt=$pdo->prepare("SELECT * FROM BBS_Card_Layout_Versions WHERE PersonalTemplateID=? AND TemplateKind='Personal' AND Status='Active' LIMIT 1");$stmt->execute([$templateId]);$version=$stmt->fetch();if(!$version)return null;$stmt=$pdo->prepare("SELECT * FROM BBS_Card_Layout_Sides WHERE LayoutVersionID=? ORDER BY FIELD(Side,'Front','Back')");$stmt->execute([(int)$version['id']]);$sides=$stmt->fetchAll();$stmt=$pdo->prepare("SELECT * FROM BBS_Card_Layout_Elements WHERE LayoutVersionID=? ORDER BY FIELD(Side,'Front','Back'),ZIndex,id");$stmt->execute([(int)$version['id']]);$elements=$stmt->fetchAll();$stmt=$pdo->prepare("SELECT * FROM BBS_Card_Layout_Assets WHERE LayoutVersionID=? AND Status='Active' ORDER BY id");$stmt->execute([(int)$version['id']]);return bbs_card_designer_safe_layout($version,$sides,$elements,$stmt->fetchAll());}catch(PDOException$e){if((int)($e->errorInfo[1]??0)===1146)return null;throw$e;} }
function bbs_card_designer_personal_render(PDO $pdo,array $employee,array $template,array $card,string $token,string $actor): ?array { if(!bbs_card_designer_rendering_enabled($pdo))return null;$layout=bbs_card_active_personal_designer_layout($pdo,(int)$template['id']);if(!$layout)return null;$values=['employee.full_name'=>(string)($employee['EmployeeName']??''),'employee.id'=>(string)($employee['EmployeeID']??''),'employee.department'=>(string)($employee['Department']??''),'employee.safety_unit'=>(string)($employee['Unit']??''),'employee.position'=>(string)($employee['Position']??''),'employee.bbs_level'=>(string)($employee['BBSLevel']??''),'employee.photo'=>'','card.personal_qr'=>(string)($card['qrUrl']??''),'card.issue_date'=>(new DateTimeImmutable('now',new DateTimeZone('Asia/Bangkok')))->format('Y-m-d'),'template.name'=>(string)($template['TemplateName']??''),'organization.name'=>'Thai Summit Harness Co., Ltd.','organization.logo'=>''];$snapshot=['layout'=>$layout,'values'=>array_replace($values,['card.personal_qr'=>['kind'=>'PersonalQr','fingerprint'=>bbs_card_fingerprint($token)]])];return['layout'=>$layout,'values'=>$values,'printSnapshot'=>['layoutVersionId'=>$layout['layoutVersionId'],'renderContractHash'=>hash('sha256',(string)json_encode($snapshot,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)),'snapshot'=>$snapshot,'receipt'=>bbs_print_receipt_create('Personal',(int)$card['cardId'],$actor,$snapshot)]]; }
function bbs_card_issue(PDO $pdo,array $user,array $employee,array $template,string $reason): array { $token=bbs_card_token();$stmt=$pdo->prepare("INSERT INTO BBS_Cards(EmployeeID,TemplateID,TokenHash,TokenFingerprint,Status,IssueReason,IssuedBy) VALUES(?,?,?,?,'Active',?,?)");$stmt->execute([$employee['EmployeeID'],$template['id'],bbs_card_hash($token),bbs_card_fingerprint($token),$reason!==''?$reason:null,(string)$user['id']]);$payload=array_merge(['cardId'=>(int)$pdo->lastInsertId(),'rawToken'=>$token],bbs_card_payload($employee,$template,$token));$render=bbs_card_designer_personal_render($pdo,$employee,$template,$payload,$token,(string)$user['id']);return$render?array_merge($payload,['designerRender'=>$render]):$payload; }
function bbs_card_upload(): array {
    $file=$_FILES['template']??null;if(!is_array($file)||(int)($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)json_response(['success'=>false,'message'=>'A JPG, PNG, or WebP card template is required.'],400);if((int)($file['size']??0)>10*1024*1024)json_response(['success'=>false,'message'=>'Template must not exceed 10 MB.'],400);$mime=bbs_card_file_mime((string)$file['tmp_name']);if(!in_array($mime,['image/jpeg','image/png','image/webp'],true))json_response(['success'=>false,'message'=>'Template file content is not a supported image.'],400);$ext=['image/jpeg'=>'.jpg','image/png'=>'.png','image/webp'=>'.webp'][$mime];$stored=time().'-'.bin2hex(random_bytes(18)).$ext;$target=bbs_card_template_dir().'/'.$stored;if(!move_uploaded_file((string)$file['tmp_name'],$target))json_response(['success'=>false,'message'=>'Unable to store card template.'],500);return['stored'=>$stored,'name'=>bbs_card_clean($file['name']??'template',255),'mime'=>$mime,'size'=>(int)$file['size'],'target'=>$target];
}

function handle_bbs_card_routes(string $method,string $path): bool {
    if(strpos($path,'/bbs/')!==0)return false;
    if($method==='POST'&&$path==='/bbs/qr/resolve'){$body=json_body();$token=(string)($body['token']??'');$limit=bbs_card_qr_limit($token);if(empty($limit['allowed']))json_response(['success'=>false,'code'=>'QR_RATE_LIMITED','message'=>'Too many QR attempts. Please try again later.'],429);if(!bbs_card_valid_token($token)){bbs_card_record_resolve($limit,false);json_response(['success'=>false,'code'=>'QR_NOT_ACTIVE','message'=>'This BBS QR is not active.'],404);}$card=bbs_card_active_token($token);$departmentCard=$card?null:bbs_department_card_active_token($token);bbs_card_record_resolve($limit,(bool)($card||$departmentCard));if(!$card&&!$departmentCard)json_response(['success'=>false,'code'=>'QR_NOT_ACTIVE','message'=>'This BBS QR is not active.'],404);if($card)db_execute('UPDATE BBS_Cards SET LastResolvedAt=NOW(),ResolveCount=ResolveCount+1 WHERE id=?',[(int)$card['id']]);else db_execute('UPDATE BBS_Department_QR_Cards SET LastResolvedAt=NOW(),ResolveCount=ResolveCount+1 WHERE id=?',[(int)$departmentCard['id']]);json_response(['success'=>true,'data'=>['active'=>true,'route'=>'#bbs-smart-card','requiresLogin'=>true]]);}
    $user=require_user();
    if($method==='POST'&&$path==='/bbs/qr/claim'){$body=json_body();$token=(string)($body['token']??'');if(!bbs_card_valid_token($token))json_response(['success'=>false,'code'=>'QR_NOT_ACTIVE','message'=>'This BBS QR is not active.'],404);$card=bbs_card_active_token($token);$departmentCard=$card?null:bbs_department_card_active_token($token);if(!$card&&!$departmentCard)json_response(['success'=>false,'code'=>'QR_NOT_ACTIVE','message'=>'This BBS QR is not active.'],404);if($departmentCard){$employee=db_row("SELECT e.EmployeeID,d.id DepartmentID FROM employees e LEFT JOIN master_departments d ON LOWER(TRIM(d.Name))=LOWER(TRIM(e.Department)) WHERE e.EmployeeID=? LIMIT 1",[(string)$user['id']]);$isAdmin=strcasecmp((string)($user['role']??''),'Admin')===0;if(!$isAdmin&&(int)($employee['DepartmentID']??0)!==(int)$departmentCard['DepartmentID'])json_response(['success'=>false,'code'=>'QR_SCOPE_DENIED','message'=>'This Community QR belongs to another Department.'],403);json_response(['success'=>true,'data'=>['mode'=>'community','route'=>bbs_card_route($body['returnRoute']??''),'departmentId'=>(int)$departmentCard['DepartmentID'],'departmentName'=>$departmentCard['DepartmentName']]]);}if(!bbs_card_can_target($user,$card))json_response(['success'=>false,'code'=>'QR_SCOPE_DENIED','message'=>'You do not have permission to use this employee card.'],403);$employees=bbs_card_employees([(string)$card['EmployeeID']]);if(!$employees)json_response(['success'=>false,'message'=>'Card owner is no longer available.'],404);$self=strcasecmp((string)$card['EmployeeID'],(string)$user['id'])===0;json_response(['success'=>true,'data'=>['mode'=>$self?'workspace':'observation','route'=>bbs_card_route($body['returnRoute']??''),'employee'=>$self?null:$employees[0]]]);}
    if(strpos($path,'/bbs/admin/')!==0)return false;$admin=require_admin();
    if($method==='GET'&&$path==='/bbs/admin/card-templates')json_response(['success'=>true,'data'=>db_rows("SELECT t.*,d.Name DepartmentName FROM BBS_Card_Templates t LEFT JOIN master_departments d ON d.id=t.DepartmentID ORDER BY FIELD(t.Status,'Active','Draft','Archived'),t.UpdatedAt DESC,t.id DESC")]);
    if($method==='POST'&&$path==='/bbs/admin/card-templates'){$upload=bbs_card_upload();try{$name=bbs_card_clean($_POST['templateName']??'',160);$department=bbs_phase1_positive_int($_POST['departmentId']??null);$level=bbs_card_clean($_POST['bbsLevel']??'',40)?:null;if($name==='')throw new InvalidArgumentException('Template name is required.');if($level!==null&&!in_array($level,bbs_phase1_levels(),true))throw new InvalidArgumentException('BBS level is invalid.');if($department&&!db_row('SELECT id FROM master_departments WHERE id=?',[$department]))throw new InvalidArgumentException('Department is invalid.');$stmt=db()->prepare('INSERT INTO BBS_Card_Templates(TemplateName,DepartmentID,BBSLevel,BackgroundStoredName,OriginalName,MimeType,FileSize,IncludeEmployeeID,CreatedBy,UpdatedBy) VALUES(?,?,?,?,?,?,?,?,?,?)');$stmt->execute([$name,$department,$level,$upload['stored'],$upload['name'],$upload['mime'],$upload['size'],(string)($_POST['includeEmployeeId']??'1')==='0'?0:1,$admin['id'],$admin['id']]);$id=(int)db()->lastInsertId();bbs_phase1_audit($admin,'BBS_CARD_TEMPLATE_CREATE','BBS_Card_Template',(string)$id,'Created Draft BBS card template.');json_response(['success'=>true,'data'=>db_row('SELECT * FROM BBS_Card_Templates WHERE id=?',[$id])],201);}catch(InvalidArgumentException $e){@unlink($upload['target']);json_response(['success'=>false,'message'=>$e->getMessage()],400);}catch(Throwable $e){@unlink($upload['target']);throw$e;}}
    $fileParams=route_params($path,'/bbs/admin/card-templates/:id/file');if($method==='GET'&&$fileParams!==null){$row=db_row('SELECT BackgroundStoredName,OriginalName,MimeType FROM BBS_Card_Templates WHERE id=?',[bbs_phase1_positive_int($fileParams['id'])]);if(!$row)json_response(['success'=>false,'message'=>'Template was not found.'],404);$file=bbs_card_template_dir().'/'.basename((string)$row['BackgroundStoredName']);if(!is_file($file))json_response(['success'=>false,'message'=>'Template file was not found.'],404);header('Content-Type: '.$row['MimeType']);header('Content-Disposition: inline; filename="'.str_replace(['"','\\'],'_',bbs_card_clean($row['OriginalName'])).'"');header('Cache-Control: private, no-store');readfile($file);exit;}
    $templateParams=route_params($path,'/bbs/admin/card-templates/:id');if($method==='PUT'&&$templateParams!==null){$body=json_body();$id=bbs_phase1_positive_int($templateParams['id']);$version=bbs_phase1_positive_int($body['rowVersion']??null);$action=strtolower(bbs_card_clean($body['action']??'',20));if(!$id||!$version||!in_array($action,['activate','archive'],true))json_response(['success'=>false,'message'=>'Valid template ID, RowVersion, and action are required.'],400);$pdo=db();$pdo->beginTransaction();try{$stmt=$pdo->prepare('SELECT * FROM BBS_Card_Templates WHERE id=? FOR UPDATE');$stmt->execute([$id]);$row=$stmt->fetch();if(!$row){$pdo->rollBack();json_response(['success'=>false,'message'=>'Template was not found.'],404);}if((int)$row['RowVersion']!==$version){$pdo->rollBack();json_response(['success'=>false,'code'=>'VERSION_CONFLICT','message'=>'Template was changed by another user.'],409);}if($action==='activate'){if($row['Status']==='Archived'){$pdo->rollBack();json_response(['success'=>false,'message'=>'Archived templates cannot be activated.'],409);}$pdo->prepare("UPDATE BBS_Card_Templates SET Status='Archived',ArchivedAt=NOW(),ArchivedBy=?,UpdatedBy=?,RowVersion=RowVersion+1 WHERE Status='Active' AND id<>? AND DepartmentID <=> ? AND BBSLevel <=> ?")->execute([$admin['id'],$admin['id'],$id,$row['DepartmentID'],$row['BBSLevel']]);$pdo->prepare("UPDATE BBS_Card_Templates SET Status='Active',ActivatedAt=NOW(),ActivatedBy=?,UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=?")->execute([$admin['id'],$admin['id'],$id]);}else{$pdo->prepare("UPDATE BBS_Card_Templates SET Status='Archived',ArchivedAt=NOW(),ArchivedBy=?,UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=?")->execute([$admin['id'],$admin['id'],$id]);}$pdo->commit();bbs_phase1_audit($admin,$action==='activate'?'BBS_CARD_TEMPLATE_ACTIVATE':'BBS_CARD_TEMPLATE_ARCHIVE','BBS_Card_Template',(string)$id,$action.' card template.');json_response(['success'=>true,'data'=>db_row('SELECT * FROM BBS_Card_Templates WHERE id=?',[$id])]);}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
    if($method==='GET'&&$path==='/bbs/admin/card-employees'){$paging=bbs_list_query($_GET,24);$q=bbs_list_search($_GET['q']??'');$departmentId=bbs_phase1_positive_int($_GET['departmentId']??null);$where=["FIELD(m.BBSLevel,'Operator','Group Leader','Department Head','Section Head','Manager')>=2"];$params=[];if($departmentId){$where[]='md.id=?';$params[]=$departmentId;}if($q!==''){$where[]='(e.EmployeeID LIKE ? OR e.EmployeeName LIKE ? OR e.Department LIKE ? OR e.Unit LIKE ? OR e.Position LIKE ?)';for($i=0;$i<5;$i++)$params[]='%'.$q.'%';}$from="FROM employees e JOIN master_positions p ON LOWER(TRIM(p.Name))=LOWER(TRIM(e.Position)) JOIN BBS_Position_Level_Mappings m ON m.PositionID=p.id AND m.IsActive=1 LEFT JOIN master_departments md ON LOWER(TRIM(md.Name))=LOWER(TRIM(e.Department)) LEFT JOIN BBS_Cards c ON c.id=(SELECT x.id FROM BBS_Cards x WHERE x.EmployeeID=e.EmployeeID AND x.Status='Active' ORDER BY x.id DESC LIMIT 1) WHERE ".implode(' AND ',$where);$select="SELECT e.EmployeeID,e.EmployeeName,e.Department,e.Unit,e.Position,m.BBSLevel,md.id DepartmentID,c.id ActiveCardID,c.TokenFingerprint,c.IssuedAt $from";if(!$paging['paged'])json_response(['success'=>true,'data'=>db_rows($select.' ORDER BY e.Department,e.Unit,e.EmployeeName',$params)]);$count=db_row("SELECT COUNT(*) total $from",$params);$meta=bbs_list_pagination((int)($count['total']??0),$paging['page'],$paging['pageSize']);json_response(['success'=>true,'data'=>['rows'=>db_rows($select.' ORDER BY e.Department,e.Unit,e.EmployeeName LIMIT '.(int)$meta['pageSize'].' OFFSET '.(($meta['page']-1)*$meta['pageSize']),$params),'pagination'=>$meta]]);}
    if($method==='GET'&&$path==='/bbs/admin/cards'){$paging=bbs_list_query($_GET);$q=bbs_list_search($_GET['q']??'');$departmentId=bbs_phase1_positive_int($_GET['departmentId']??null);$status=in_array($_GET['status']??'',['Active','Revoked','Replaced'],true)?$_GET['status']:null;$where=['1=1'];$params=[];if($status){$where[]='c.Status=?';$params[]=$status;}if($departmentId){$where[]='md.id=?';$params[]=$departmentId;}if($q!==''){$where[]='(c.EmployeeID LIKE ? OR e.EmployeeName LIKE ? OR e.Department LIKE ? OR e.Unit LIKE ? OR e.Position LIKE ? OR t.TemplateName LIKE ? OR c.TokenFingerprint LIKE ?)';for($i=0;$i<7;$i++)$params[]='%'.$q.'%';}$from='FROM BBS_Cards c JOIN employees e ON e.EmployeeID=c.EmployeeID JOIN BBS_Card_Templates t ON t.id=c.TemplateID LEFT JOIN master_departments md ON LOWER(TRIM(md.Name))=LOWER(TRIM(e.Department)) WHERE '.implode(' AND ',$where);$select="SELECT c.id,c.EmployeeID,c.TemplateID,c.TokenFingerprint,c.Status,c.IssueReason,c.IssuedAt,c.IssuedBy,c.RevokedAt,c.RevokedBy,c.RevokeReason,c.ReplacedByCardID,c.ResolveCount,e.EmployeeName,e.Department,e.Unit,e.Position,t.TemplateName $from";if(!$paging['paged'])json_response(['success'=>true,'data'=>db_rows($select.' ORDER BY c.IssuedAt DESC,c.id DESC LIMIT 500',$params)]);$count=db_row("SELECT COUNT(*) total $from",$params);$meta=bbs_list_pagination((int)($count['total']??0),$paging['page'],$paging['pageSize']);json_response(['success'=>true,'data'=>['rows'=>db_rows($select.' ORDER BY c.IssuedAt DESC,c.id DESC LIMIT '.(int)$meta['pageSize'].' OFFSET '.(($meta['page']-1)*$meta['pageSize']),$params),'pagination'=>$meta]]);}
    if($method==='POST'&&$path==='/bbs/admin/cards/issue'){$body=json_body();$ids=array_values(array_unique(array_filter(array_map(fn($v)=>bbs_card_clean($v,50),is_array($body['employeeIds']??null)?$body['employeeIds']:[]))));$templateId=bbs_phase1_positive_int($body['templateId']??null);$reason=bbs_card_clean($body['reason']??'',255);if(!$ids||count($ids)>100||!$templateId)json_response(['success'=>false,'message'=>'Choose 1-100 employees and an Active template.'],400);$pdo=db();$pdo->beginTransaction();try{$stmt=$pdo->prepare("SELECT * FROM BBS_Card_Templates WHERE id=? AND Status='Active' FOR UPDATE");$stmt->execute([$templateId]);$template=$stmt->fetch();if(!$template){$pdo->rollBack();json_response(['success'=>false,'message'=>'The selected card template is not Active.'],409);}$employees=bbs_card_employees($ids,$pdo);if(count($employees)!==count($ids)){$pdo->rollBack();json_response(['success'=>false,'message'=>'One or more employees were not found.'],400);}$cards=[];foreach($employees as$employee){if(bbs_phase1_level_rank($employee['BBSLevel']??null)<bbs_phase1_level_rank('Group Leader')){$pdo->rollBack();json_response(['success'=>false,'message'=>'Personal cards are available from Group Leader level upward ('.$employee['EmployeeID'].').'],400);}if(!bbs_card_template_matches($template,$employee)){$pdo->rollBack();json_response(['success'=>false,'message'=>'Template scope does not match employee '.$employee['EmployeeID'].'.'],400);}$stmt=$pdo->prepare("SELECT id FROM BBS_Cards WHERE EmployeeID=? AND Status='Active' LIMIT 1");$stmt->execute([$employee['EmployeeID']]);if($stmt->fetch()){$pdo->rollBack();json_response(['success'=>false,'code'=>'ACTIVE_CARD_EXISTS','message'=>'Employee '.$employee['EmployeeID'].' already has an Active card. Use Replace.'],409);}$cards[]=bbs_card_issue($pdo,$admin,$employee,$template,$reason);}$pdo->commit();bbs_phase1_audit($admin,'BBS_CARD_ISSUE','BBS_Card_Batch',implode(',',array_column($cards,'cardId')),'Issued '.count($cards).' BBS card(s).');json_response(['success'=>true,'data'=>$cards],201);}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();if($e instanceof PDOException&&(int)($e->errorInfo[1]??0)===1062)json_response(['success'=>false,'code'=>'ACTIVE_CARD_EXISTS','message'=>'This employee already has an Active card. Use Replace.'],409);throw$e;}}
    $revoke=route_params($path,'/bbs/admin/cards/:id/revoke');if($method==='POST'&&$revoke!==null){$body=json_body();$id=bbs_phase1_positive_int($revoke['id']);$reason=bbs_card_clean($body['reason']??'',255);if(!$id||$reason==='')json_response(['success'=>false,'message'=>'Card ID and revoke reason are required.'],400);$count=db_execute("UPDATE BBS_Cards SET Status='Revoked',RevokedAt=NOW(),RevokedBy=?,RevokeReason=? WHERE id=? AND Status='Active'",[$admin['id'],$reason,$id]);if(!$count)json_response(['success'=>false,'message'=>'Only an Active card can be revoked.'],409);bbs_phase1_audit($admin,'BBS_CARD_REVOKE','BBS_Card',(string)$id,'Revoked BBS card.');json_response(['success'=>true]);}
    $replace=route_params($path,'/bbs/admin/cards/:id/replace');if($method==='POST'&&$replace!==null){$body=json_body();$id=bbs_phase1_positive_int($replace['id']);$reason=bbs_card_clean($body['reason']??'',255)?:'Replace / reprint';if(!$id)json_response(['success'=>false,'message'=>'Valid card ID is required.'],400);$pdo=db();$pdo->beginTransaction();try{$stmt=$pdo->prepare("SELECT c.id CardID,c.EmployeeID,c.TemplateID,t.* FROM BBS_Cards c JOIN BBS_Card_Templates t ON t.id=c.TemplateID WHERE c.id=? AND c.Status='Active' AND t.Status='Active' FOR UPDATE");$stmt->execute([$id]);$old=$stmt->fetch();if(!$old){$pdo->rollBack();json_response(['success'=>false,'message'=>'Only an Active card with an Active template can be replaced.'],409);}$employee=bbs_card_employees([(string)$old['EmployeeID']],$pdo)[0]??null;if(!$employee){$pdo->rollBack();json_response(['success'=>false,'message'=>'Employee was not found.'],404);}if(bbs_phase1_level_rank($employee['BBSLevel']??null)<bbs_phase1_level_rank('Group Leader')){$pdo->rollBack();json_response(['success'=>false,'message'=>'The employee is no longer eligible for a personal BBS card.'],409);}$old['id']=(int)$old['TemplateID'];$pdo->prepare("UPDATE BBS_Cards SET Status='Replaced',RevokedAt=NOW(),RevokedBy=?,RevokeReason=? WHERE id=?")->execute([$admin['id'],$reason,$id]);$new=bbs_card_issue($pdo,$admin,$employee,$old,$reason);$pdo->prepare('UPDATE BBS_Cards SET ReplacedByCardID=? WHERE id=?')->execute([$new['cardId'],$id]);$pdo->commit();bbs_phase1_audit($admin,'BBS_CARD_REPLACE','BBS_Card',(string)$id,'Replaced BBS card and rotated QR token.');json_response(['success'=>true,'data'=>$new],201);}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
    if($method==='POST'&&$path==='/bbs/admin/cards/print-log'){
        $body=json_body();$ids=array_values(array_unique(array_filter(array_map('bbs_phase1_positive_int',is_array($body['cardIds']??null)?$body['cardIds']:[]))));
        if(!$ids||count($ids)>100)json_response(['success'=>false,'message'=>'Choose 1-100 cards.'],400);
        $receipts=[];$supplied=array_key_exists('designerReceipts',$body)?$body['designerReceipts']:[];
        if(!is_array($supplied)||count($supplied)>count($ids))json_response(['success'=>false,'message'=>'Invalid prepared card receipts.'],400);
        foreach($supplied as$entry){$id=bbs_phase1_positive_int($entry['cardId']??null);if(!in_array($id,$ids,true)||isset($receipts[$id])||!is_string($entry['receipt']??null))json_response(['success'=>false,'message'=>'Invalid prepared card receipts.'],400);$receipts[$id]=$entry['receipt'];}
        $pdo=db();$pdo->beginTransaction();
        try{
            $marks=implode(',',array_fill(0,count($ids),'?'));$stmt=$pdo->prepare("SELECT id,TokenFingerprint FROM BBS_Cards WHERE id IN ($marks) FOR UPDATE");$stmt->execute($ids);$rows=$stmt->fetchAll();
            if(count($rows)!==count($ids)){$pdo->rollBack();json_response(['success'=>false,'message'=>'One or more cards were not found.'],400);}
            $byId=[];foreach($rows as$row)$byId[(int)$row['id']]=$row;
            $mode=count($ids)>1?'batch':'single';$reason=bbs_card_clean($body['reason']??'',255)?:null;$printLogIds=[];$snapshotCount=0;
            $insert=$pdo->prepare('INSERT INTO BBS_Card_Print_Logs(CardID,PrintMode,PrintedBy,Reason) VALUES(?,?,?,?)');
            foreach($ids as$id){
                $snapshot=isset($receipts[$id])?bbs_print_receipt_read($receipts[$id],['kind'=>'Personal','subjectId'=>$id,'actorId'=>(string)$admin['id'],'fingerprint'=>$byId[$id]['TokenFingerprint']]):null;
                $insert->execute([$id,$mode,$admin['id'],$reason]);$printLogId=(int)$pdo->lastInsertId();$printLogIds[]=$printLogId;
                if($snapshot){$snapshotInsert=$pdo->prepare('INSERT INTO BBS_Card_Designer_Print_Snapshots(LayoutVersionID,PersonalPrintLogID,RenderContractHash,SnapshotJSON,RenderMetadata) VALUES(?,?,?,?,?)');$snapshotInsert->execute([$snapshot['layoutVersionId'],$printLogId,$snapshot['renderContractHash'],$snapshot['snapshotJson'],json_encode(['renderer'=>'visual-card-designer','rawQrStored'=>false])]);$snapshotCount++;}
            }
            $pdo->commit();bbs_phase1_audit($admin,'BBS_CARD_PRINT','BBS_Card_Batch',implode(',',$ids),'Recorded '.$mode.' card print; designer snapshots='.$snapshotCount.'.');
            json_response(['success'=>true,'data'=>['count'=>count($ids),'mode'=>$mode,'printLogIds'=>$printLogIds]],201);
        }catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();bbs_print_receipt_respond($e);throw$e;}
    }
    return false;
}
