<?php
declare(strict_types=1);

require_once __DIR__.'/../lib/bbs_card_designer.php';

final class BbsMasterArtworkException extends InvalidArgumentException {}

function bbs_designer_setting(string $key): string { $row=db_row('SELECT SettingValue FROM BBS_Settings WHERE SettingKey=? LIMIT 1',[$key]);return(string)($row['SettingValue']??'0'); }
function bbs_designer_runtime_settings(array $rows): array { $values=[];foreach($rows as $row)$values[(string)$row['SettingKey']]=(string)$row['SettingValue'];return['stagedAdminOnly'=>($values['staged_admin_only']??'0')==='1','pilotScopeOnly'=>($values['pilot_scope_only']??'0')==='1','designerEnabled'=>($values['visual_card_designer_enabled']??'0')==='1','renderingEnabled'=>($values['visual_card_designer_rendering_enabled']??'0')==='1']; }
function bbs_designer_require_enabled(): void { if(bbs_designer_setting('visual_card_designer_enabled')!=='1')json_response(['success'=>false,'code'=>'BBS_DESIGNER_DISABLED','message'=>'Visual Card Designer is disabled.'],409); }
function bbs_designer_kind_info(string $value): array { $kind=bbs_designer_kind($value);return$kind==='Personal'?['kind'=>$kind,'parentTable'=>'BBS_Card_Templates','parentColumn'=>'PersonalTemplateID','storageClass'=>'PersonalTemplate']:['kind'=>$kind,'parentTable'=>'BBS_Department_Card_Templates','parentColumn'=>'DepartmentTemplateID','storageClass'=>'DepartmentTemplate']; }
function bbs_designer_asset_dir(): string { $dir=dirname(__DIR__,2).'/backend/private-uploads/bbs-card-designer';if(!is_dir($dir))mkdir($dir,0770,true);return$dir; }
function bbs_designer_master_dir(): string { $dir=dirname(__DIR__,2).'/backend/private-uploads/bbs-card-master-artwork';if(!is_dir($dir))mkdir($dir,0770,true);return$dir; }
function bbs_designer_master_payload(array $row): array { return['id'=>(int)$row['id'],'templateKind'=>$row['TemplateKind'],'side'=>$row['Side'],'versionNo'=>(int)$row['VersionNo'],'originalName'=>$row['OriginalName'],'mimeType'=>$row['MimeType'],'fileSize'=>(int)$row['FileSize'],'pixelWidth'=>$row['PixelWidth']===null?null:(int)$row['PixelWidth'],'pixelHeight'=>$row['PixelHeight']===null?null:(int)$row['PixelHeight'],'status'=>$row['Status'],'createdAt'=>$row['CreatedAt'],'activatedAt'=>$row['ActivatedAt'],'archivedAt'=>$row['ArchivedAt']]; }
function bbs_designer_asset_payload(array $row): array { return['id'=>(int)$row['id'],'assetKey'=>$row['AssetKey'],'masterArtworkId'=>$row['MasterArtworkID']===null?null:(int)$row['MasterArtworkID'],'masterArtworkKind'=>$row['MasterArtworkKind']??null,'masterArtworkSide'=>$row['MasterArtworkSide']??null,'originalName'=>$row['OriginalName'],'mimeType'=>$row['MimeType'],'fileSize'=>(int)$row['FileSize'],'pixelWidth'=>$row['PixelWidth']===null?null:(int)$row['PixelWidth'],'pixelHeight'=>$row['PixelHeight']===null?null:(int)$row['PixelHeight'],'status'=>$row['Status']]; }
function bbs_designer_preset_payload(array $row): array { return['id'=>(int)$row['id'],'templateKind'=>$row['TemplateKind'],'presetName'=>$row['PresetName'],'status'=>$row['Status'],'rowVersion'=>(int)$row['RowVersion'],'createdAt'=>$row['CreatedAt'],'updatedAt'=>$row['UpdatedAt'],'trashedAt'=>$row['TrashedAt']]; }
function bbs_designer_reusable_preset(array $layout): array { foreach($layout['elements']as$element)if($element['assetId']!==null||$element['elementType']==='StaticImage')throw new InvalidArgumentException('Remove static private images before saving this layout as a Preset. Master Artwork backgrounds are kept by the destination Draft.');$sides=[];foreach($layout['sides']as$side)$sides[]=array_intersect_key($side,array_flip(['side','backgroundFit','backgroundPositionXBP','backgroundPositionYBP','bleedMM','safeMarginMM']));$elements=[];foreach($layout['elements']as$element){$element['assetId']=null;$elements[]=$element;}return['templateKind'=>$layout['templateKind'],'widthMM'=>$layout['widthMM'],'heightMM'=>$layout['heightMM'],'dpi'=>$layout['dpi'],'duplexFlip'=>$layout['duplexFlip'],'backRotation'=>$layout['backRotation'],'sides'=>$sides,'elements'=>$elements]; }
function bbs_designer_apply_preset(array $current,array $preset): array { $bySide=[];foreach((array)($preset['sides']??[])as$side)$bySide[$side['side']??'']=$side;$sides=[];$protected=['storageClass','backgroundAssetId','masterArtworkId','masterArtworkKind','masterArtworkSide','backgroundStoredName','backgroundOriginalName','backgroundMimeType','backgroundFileSize','pixelWidth','pixelHeight'];foreach($current['sides']as$side)$sides[]=array_merge($side,$bySide[$side['side']]??[],array_intersect_key($side,array_flip($protected)));return array_merge($current,['widthMM'=>$preset['widthMM']??null,'heightMM'=>$preset['heightMM']??null,'dpi'=>$preset['dpi']??300,'duplexFlip'=>$preset['duplexFlip']??'LongEdge','backRotation'=>$preset['backRotation']??0,'sides'=>$sides,'elements'=>$preset['elements']??[]]); }
function bbs_designer_upload_asset(string $field): array { $file=$_FILES[$field]??null;if(!is_array($file)||(int)($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)json_response(['success'=>false,'message'=>'A JPG, PNG, or WebP designer image is required.'],400);if((int)($file['size']??0)>10*1024*1024)json_response(['success'=>false,'message'=>'Designer image must not exceed 10 MB.'],400);$mime=bbs_card_file_mime((string)$file['tmp_name']);if(!in_array($mime,['image/jpeg','image/png','image/webp'],true))json_response(['success'=>false,'message'=>'Designer image content must be JPEG, PNG, or WebP.'],400);$ext=['image/jpeg'=>'.jpg','image/png'=>'.png','image/webp'=>'.webp'][$mime];$stored=time().'-'.bin2hex(random_bytes(18)).$ext;$target=bbs_designer_asset_dir().'/'.basename($stored);if(!move_uploaded_file((string)$file['tmp_name'],$target))json_response(['success'=>false,'message'=>'Unable to store designer image.'],500);return['stored'=>$stored,'target'=>$target,'name'=>bbs_card_clean($file['name']??'image',255),'mime'=>$mime,'size'=>(int)$file['size']]; }
function bbs_designer_upload_master(string $field): array { $file=$_FILES[$field]??null;if(!is_array($file)||(int)($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)json_response(['success'=>false,'message'=>'A JPG, PNG, or WebP Master Artwork file is required.'],400);if((int)($file['size']??0)>10*1024*1024)json_response(['success'=>false,'message'=>'Master Artwork must not exceed 10 MB.'],400);$mime=bbs_card_file_mime((string)$file['tmp_name']);if(!in_array($mime,['image/jpeg','image/png','image/webp'],true))json_response(['success'=>false,'message'=>'Master Artwork content must be JPEG, PNG, or WebP.'],400);$ext=['image/jpeg'=>'.jpg','image/png'=>'.png','image/webp'=>'.webp'][$mime];$stored=time().'-'.bin2hex(random_bytes(18)).$ext;$target=bbs_designer_master_dir().'/'.basename($stored);if(!move_uploaded_file((string)$file['tmp_name'],$target))json_response(['success'=>false,'message'=>'Unable to store Master Artwork.'],500);$size=@getimagesize($target);return['stored'=>$stored,'target'=>$target,'name'=>bbs_card_clean($file['name']??'artwork',255),'mime'=>$mime,'size'=>(int)$file['size'],'width'=>is_array($size)?(int)$size[0]:null,'height'=>is_array($size)?(int)$size[1]:null]; }
function bbs_designer_row_layout(array $version,array $sides,array $elements,array $assets=[]): array {
    $layout=['templateKind'=>$version['TemplateKind'],'widthMM'=>(float)$version['WidthMM'],'heightMM'=>(float)$version['HeightMM'],'dpi'=>(int)$version['DPI'],'duplexFlip'=>$version['DuplexFlip'],'backRotation'=>(int)$version['BackRotation'],'sides'=>[],'elements'=>[]];
    $assetByName=[];foreach($assets as$asset)$assetByName[(string)$asset['StoredName']]=$asset;
    foreach($sides as$row){$asset=$assetByName[(string)$row['BackgroundStoredName']]??null;$layout['sides'][]=['side'=>$row['Side'],'storageClass'=>$row['StorageClass'],'backgroundAssetId'=>$row['StorageClass']==='DesignerAsset'&&$asset?(int)$asset['id']:null,'masterArtworkId'=>$asset&&$asset['MasterArtworkID']!==null?(int)$asset['MasterArtworkID']:null,'masterArtworkKind'=>$asset['MasterArtworkKind']??null,'masterArtworkSide'=>$asset['MasterArtworkSide']??null,'backgroundStoredName'=>$row['StorageClass']==='DesignerAsset'?'asset-reference':'parent-reference','backgroundOriginalName'=>$row['BackgroundOriginalName'],'backgroundMimeType'=>$row['BackgroundMimeType'],'backgroundFileSize'=>(int)$row['BackgroundFileSize'],'pixelWidth'=>$row['PixelWidth']===null?null:(int)$row['PixelWidth'],'pixelHeight'=>$row['PixelHeight']===null?null:(int)$row['PixelHeight'],'backgroundFit'=>$row['BackgroundFit'],'backgroundPositionXBP'=>(int)$row['BackgroundPositionXBP'],'backgroundPositionYBP'=>(int)$row['BackgroundPositionYBP'],'bleedMM'=>(float)$row['BleedMM'],'safeMarginMM'=>(float)$row['SafeMarginMM']];}
    foreach($elements as$row)$layout['elements'][]=['elementKey'=>$row['ElementKey'],'side'=>$row['Side'],'elementType'=>$row['ElementType'],'dataSourceKey'=>$row['DataSourceKey'],'staticText'=>$row['StaticText'],'assetId'=>$row['AssetID']===null?null:(int)$row['AssetID'],'xBP'=>(int)$row['XBP'],'yBP'=>(int)$row['YBP'],'widthBP'=>(int)$row['WidthBP'],'heightBP'=>(int)$row['HeightBP'],'rotationDeg'=>(float)$row['RotationDeg'],'zIndex'=>(int)$row['ZIndex'],'visible'=>(bool)$row['Visible'],'locked'=>(bool)$row['Locked'],'required'=>(bool)$row['Required'],'style'=>json_decode((string)($row['StyleJSON']??'{}'),true)?:[]];
    $version['id']=(int)$version['id'];$version['VersionNo']=(int)$version['VersionNo'];$version['RowVersion']=(int)$version['RowVersion'];$version['layout']=$layout;$version['assets']=array_map('bbs_designer_asset_payload',$assets);$version['readiness']=bbs_designer_readiness($layout);return$version;
}
function bbs_designer_detail(int $id,?PDO $pdo=null,bool $lock=false,bool $includeDeleted=false): ?array {
    $pdo=$pdo?:db();$stmt=$pdo->prepare('SELECT * FROM BBS_Card_Layout_Versions WHERE id=?'.($includeDeleted?'':' AND IsDeleted=0').($lock?' FOR UPDATE':''));$stmt->execute([$id]);$version=$stmt->fetch();if(!$version)return null;
    $stmt=$pdo->prepare("SELECT * FROM BBS_Card_Layout_Sides WHERE LayoutVersionID=? ORDER BY FIELD(Side,'Front','Back')");$stmt->execute([$id]);$sides=$stmt->fetchAll();
    $stmt=$pdo->prepare("SELECT * FROM BBS_Card_Layout_Elements WHERE LayoutVersionID=? ORDER BY FIELD(Side,'Front','Back'),ZIndex,id");$stmt->execute([$id]);$elements=$stmt->fetchAll();
    $stmt=$pdo->prepare("SELECT a.*,m.TemplateKind MasterArtworkKind,m.Side MasterArtworkSide FROM BBS_Card_Layout_Assets a LEFT JOIN BBS_Card_Master_Artwork m ON m.id=a.MasterArtworkID WHERE a.LayoutVersionID=? AND a.Status='Active' ORDER BY a.CreatedAt,a.id");$stmt->execute([$id]);return bbs_designer_row_layout($version,$sides,$elements,$stmt->fetchAll());
}
function bbs_designer_insert_content(PDO $pdo,int $versionId,array $layout): void {
    $side=$pdo->prepare('INSERT INTO BBS_Card_Layout_Sides(LayoutVersionID,Side,StorageClass,BackgroundStoredName,BackgroundOriginalName,BackgroundMimeType,BackgroundFileSize,PixelWidth,PixelHeight,BackgroundFit,BackgroundPositionXBP,BackgroundPositionYBP,BleedMM,SafeMarginMM) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
    foreach($layout['sides'] as$item)$side->execute([$versionId,$item['side'],$item['storageClass'],$item['backgroundStoredName'],$item['backgroundOriginalName'],$item['backgroundMimeType'],$item['backgroundFileSize'],$item['pixelWidth'],$item['pixelHeight'],$item['backgroundFit'],$item['backgroundPositionXBP'],$item['backgroundPositionYBP'],$item['bleedMM'],$item['safeMarginMM']]);
    $element=$pdo->prepare('INSERT INTO BBS_Card_Layout_Elements(LayoutVersionID,ElementKey,Side,ElementType,DataSourceKey,StaticText,AssetID,XBP,YBP,WidthBP,HeightBP,RotationDeg,ZIndex,Visible,Locked,Required,StyleJSON) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
    foreach($layout['elements'] as$item)$element->execute([$versionId,$item['elementKey'],$item['side'],$item['elementType'],$item['dataSourceKey'],$item['staticText'],$item['assetId'],$item['xBP'],$item['yBP'],$item['widthBP'],$item['heightBP'],$item['rotationDeg'],$item['zIndex'],$item['visible'],$item['locked'],$item['required'],json_encode($item['style'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);
}
function bbs_designer_legacy_payload(array $parent,array $info): array {
    $personal=$info['kind']==='Personal';$elements=$personal?[
        ['elementKey'=>'employee-name','side'=>'Front','elementType'=>'DynamicText','dataSourceKey'=>'employee.full_name','xBP'=>700,'yBP'=>6500,'widthBP'=>5200,'heightBP'=>900,'zIndex'=>10,'required'=>true,'style'=>['fontSizePt'=>14,'fontWeight'=>'700']],
        ['elementKey'=>'employee-department','side'=>'Front','elementType'=>'DynamicText','dataSourceKey'=>'employee.department','xBP'=>700,'yBP'=>7450,'widthBP'=>5200,'heightBP'=>650,'zIndex'=>11,'required'=>true,'style'=>['fontSizePt'=>9]],
        ['elementKey'=>'employee-position','side'=>'Front','elementType'=>'DynamicText','dataSourceKey'=>'employee.position','xBP'=>700,'yBP'=>8150,'widthBP'=>5200,'heightBP'=>650,'zIndex'=>12,'style'=>['fontSizePt'=>9]],
        ['elementKey'=>'personal-qr','side'=>'Front','elementType'=>'QR','dataSourceKey'=>'card.personal_qr','xBP'=>6800,'yBP'=>6100,'widthBP'=>2500,'heightBP'=>2500,'zIndex'=>20,'required'=>true,'style'=>['objectFit'=>'Contain']],
        ['elementKey'=>'department-qr','side'=>'Back','elementType'=>'QR','dataSourceKey'=>'department.community_qr','xBP'=>6800,'yBP'=>6100,'widthBP'=>2500,'heightBP'=>2500,'zIndex'=>20,'required'=>true,'style'=>['objectFit'=>'Contain']],
    ]:[['elementKey'=>'department-qr','side'=>'Front','elementType'=>'QR','dataSourceKey'=>'department.community_qr','xBP'=>6900,'yBP'=>6900,'widthBP'=>2400,'heightBP'=>2400,'zIndex'=>20,'required'=>true,'style'=>['objectFit'=>'Contain']]];
    if($personal&&(int)($parent['IncludeEmployeeID']??1)!==0)$elements[]=['elementKey'=>'employee-id','side'=>'Front','elementType'=>'DynamicText','dataSourceKey'=>'employee.id','xBP'=>700,'yBP'=>8850,'widthBP'=>5200,'heightBP'=>550,'zIndex'=>13,'style'=>['fontSizePt'=>8]];
    $base=['storageClass'=>$info['storageClass'],'backgroundStoredName'=>$parent['BackgroundStoredName'],'backgroundOriginalName'=>$parent['OriginalName'],'backgroundMimeType'=>$parent['MimeType'],'backgroundFileSize'=>(int)($parent['FileSize']??0),'backgroundFit'=>'Cover','backgroundPositionXBP'=>5000,'backgroundPositionYBP'=>5000,'bleedMM'=>0,'safeMarginMM'=>3];$sides=[array_merge(['side'=>'Front'],$base),array_merge(['side'=>'Back'],$base)];
    return['templateKind'=>$info['kind'],'widthMM'=>(float)$parent['WidthMM'],'heightMM'=>(float)$parent['HeightMM'],'dpi'=>300,'duplexFlip'=>'LongEdge','backRotation'=>0,'sides'=>$sides,'elements'=>$elements];
}
function bbs_designer_canonicalize_resources(PDO $pdo,array $version,array $layout): array {
    $info=bbs_designer_kind_info((string)$version['TemplateKind']);$parentId=(int)$version[$info['parentColumn']];$stmt=$pdo->prepare("SELECT * FROM {$info['parentTable']} WHERE id=?");$stmt->execute([$parentId]);$parent=$stmt->fetch();if(!$parent)throw new InvalidArgumentException('Parent template was not found.');
    $stmt=$pdo->prepare("SELECT a.*,m.TemplateKind MasterArtworkKind,m.Side MasterArtworkSide FROM BBS_Card_Layout_Assets a LEFT JOIN BBS_Card_Master_Artwork m ON m.id=a.MasterArtworkID WHERE a.LayoutVersionID=? AND a.Status='Active'");$stmt->execute([(int)$version['id']]);$assets=$stmt->fetchAll();$byId=[];foreach($assets as$asset)$byId[(int)$asset['id']]=$asset;
    foreach(array_values(array_unique(array_filter(array_column($layout['elements'],'assetId'))))as$id)if(!isset($byId[(int)$id]))throw new InvalidArgumentException('One or more static assets do not belong to this Draft.');
    foreach($layout['sides']as$index=>$side){if($side['storageClass']!=='DesignerAsset')throw new BbsMasterArtworkException($info['kind'].' '.$side['side'].' background must use Master Artwork.');$asset=$byId[(int)($side['backgroundAssetId']??0)]??null;if(!$asset)throw new BbsMasterArtworkException('Designer background must reference an uploaded Master Artwork snapshot from this Draft.');if(empty($asset['MasterArtworkID'])||$asset['MasterArtworkKind']!==$info['kind']||$asset['MasterArtworkSide']!==$side['side'])throw new BbsMasterArtworkException($info['kind'].' '.$side['side'].' background must use its matching Master Artwork snapshot.');$layout['sides'][$index]=array_merge($side,['backgroundAssetId'=>(int)$asset['id'],'masterArtworkId'=>(int)$asset['MasterArtworkID'],'masterArtworkKind'=>$asset['MasterArtworkKind'],'masterArtworkSide'=>$asset['MasterArtworkSide'],'backgroundStoredName'=>$asset['StoredName'],'backgroundOriginalName'=>$asset['OriginalName'],'backgroundMimeType'=>$asset['MimeType'],'backgroundFileSize'=>(int)$asset['FileSize'],'pixelWidth'=>$asset['PixelWidth']===null?null:(int)$asset['PixelWidth'],'pixelHeight'=>$asset['PixelHeight']===null?null:(int)$asset['PixelHeight']]);}
    return$layout;
}
function bbs_designer_master_snapshot(PDO $pdo,int $versionId,string $kind,array $layout,string $actor,array &$createdFiles): array {
    $info=bbs_designer_kind_info($kind);$stmt=$pdo->prepare("SELECT p.id FROM BBS_Card_Layout_Versions v JOIN {$info['parentTable']} p ON p.id=v.{$info['parentColumn']} WHERE v.id=? AND p.IsDeleted=0");$stmt->execute([$versionId]);if(!$stmt->fetch())throw new InvalidArgumentException('A Designer Draft cannot be created for a template in Trash.');
    $stmt=$pdo->prepare("SELECT * FROM BBS_Card_Master_Artwork WHERE TemplateKind=? AND Status='Active' ORDER BY FIELD(Side,'Front','Back') FOR UPDATE");$stmt->execute([$kind]);$bySide=[];foreach($stmt->fetchAll()as$row)$bySide[$row['Side']]=$row;
    foreach(['Front','Back']as$side)if(!isset($bySide[$side]))throw new BbsMasterArtworkException("$kind $side Master Artwork is required before creating a Designer Draft.");
    foreach($layout['sides']as$index=>$side){$master=$bySide[$side['side']];$source=bbs_designer_master_dir().'/'.basename((string)$master['StoredName']);if(!is_file($source)||bbs_card_file_mime($source)!==$master['MimeType'])throw new BbsMasterArtworkException($kind.' '.$side['side'].' Master Artwork file is unavailable.');$ext=['image/jpeg'=>'.jpg','image/png'=>'.png','image/webp'=>'.webp'][$master['MimeType']];$stored=time().'-'.bin2hex(random_bytes(18)).$ext;$target=bbs_designer_asset_dir().'/'.basename($stored);if(!copy($source,$target))throw new RuntimeException('Unable to snapshot Master Artwork.');$createdFiles[]=$target;$stmt=$pdo->prepare("INSERT INTO BBS_Card_Layout_Assets(LayoutVersionID,MasterArtworkID,AssetKey,StoredName,OriginalName,MimeType,FileSize,PixelWidth,PixelHeight,Status,CreatedBy) VALUES(?,?,?,?,?,?,?,?,?,'Active',?)");$stmt->execute([$versionId,$master['id'],'master-'.strtolower($side['side']).'-v'.$master['VersionNo'],$stored,$master['OriginalName'],$master['MimeType'],$master['FileSize'],$master['PixelWidth'],$master['PixelHeight'],$actor]);$layout['sides'][$index]=array_merge($side,['storageClass'=>'DesignerAsset','backgroundAssetId'=>(int)$pdo->lastInsertId(),'masterArtworkId'=>(int)$master['id'],'masterArtworkKind'=>$kind,'masterArtworkSide'=>$side['side'],'backgroundStoredName'=>$stored,'backgroundOriginalName'=>$master['OriginalName'],'backgroundMimeType'=>$master['MimeType'],'backgroundFileSize'=>(int)$master['FileSize'],'pixelWidth'=>$master['PixelWidth']===null?null:(int)$master['PixelWidth'],'pixelHeight'=>$master['PixelHeight']===null?null:(int)$master['PixelHeight']]);}
    return$layout;
}
function bbs_designer_error(Throwable $error): void { if($error instanceof BbsMasterArtworkException)json_response(['success'=>false,'code'=>'MASTER_ARTWORK_REQUIRED','message'=>$error->getMessage()],409);if($error instanceof InvalidArgumentException)json_response(['success'=>false,'code'=>'BBS_DESIGNER_VALIDATION_FAILED','message'=>$error->getMessage()],400);if(($error instanceof PDOException)&&in_array((int)($error->errorInfo[1]??0),[1054,1146],true))json_response(['success'=>false,'code'=>'BBS_DESIGNER_SETUP_REQUIRED','message'=>'The latest BBS card Designer database migration is required.'],503);if(($error instanceof PDOException)&&($error->errorInfo[1]??null)===1062)json_response(['success'=>false,'code'=>'VERSION_CONFLICT','message'=>'The layout version conflicts with an existing record.'],409);throw$error; }

function handle_bbs_card_designer_routes(string $method,string $path): bool {
    if(strpos($path,'/bbs/admin/card-designer')!==0&&strpos($path,'/bbs/admin/card-master-artwork')!==0&&strpos($path,'/bbs/admin/card-layout-presets')!==0)return false;$admin=require_admin();
    try{
        if($method==='GET'&&$path==='/bbs/admin/card-master-artwork'){$records=array_map('bbs_designer_master_payload',db_rows("SELECT * FROM BBS_Card_Master_Artwork ORDER BY FIELD(TemplateKind,'Personal','Department'),FIELD(Side,'Front','Back'),VersionNo DESC,id DESC"));$slots=['Personal'=>['Front'=>null,'Back'=>null],'Department'=>['Front'=>null,'Back'=>null]];foreach($records as$row)if($row['status']==='Active')$slots[$row['templateKind']][$row['side']]=$row;json_response(['success'=>true,'data'=>['slots'=>$slots,'records'=>$records]]);}
        $masterUpload=route_params($path,'/bbs/admin/card-master-artwork/:kind/:side');if($method==='POST'&&$masterUpload!==null){bbs_designer_require_enabled();$kind=bbs_designer_kind($masterUpload['kind']);$side=ucfirst(strtolower(bbs_designer_clean($masterUpload['side'],10)));if(!in_array($side,['Front','Back'],true))throw new InvalidArgumentException('Master Artwork side must be Front or Back.');$upload=bbs_designer_upload_master('artwork');$pdo=db();$pdo->beginTransaction();try{$stmt=$pdo->prepare("SELECT id FROM BBS_Card_Master_Artwork WHERE TemplateKind=? AND Side=? AND Status='Active' FOR UPDATE");$stmt->execute([$kind,$side]);$stmt=$pdo->prepare('SELECT COALESCE(MAX(VersionNo),0)+1 nextNo FROM BBS_Card_Master_Artwork WHERE TemplateKind=? AND Side=?');$stmt->execute([$kind,$side]);$next=(int)$stmt->fetch()['nextNo'];$stmt=$pdo->prepare("UPDATE BBS_Card_Master_Artwork SET Status='Archived',ArchivedAt=NOW() WHERE TemplateKind=? AND Side=? AND Status='Active'");$stmt->execute([$kind,$side]);$stmt=$pdo->prepare("INSERT INTO BBS_Card_Master_Artwork(TemplateKind,Side,VersionNo,StoredName,OriginalName,MimeType,FileSize,PixelWidth,PixelHeight,Status,CreatedBy,ActivatedAt) VALUES(?,?,?,?,?,?,?,?,?,'Active',?,NOW())");$stmt->execute([$kind,$side,$next,$upload['stored'],$upload['name'],$upload['mime'],$upload['size'],$upload['width'],$upload['height'],$admin['id']]);$id=(int)$pdo->lastInsertId();$pdo->commit();bbs_phase1_audit($admin,'BBS_CARD_MASTER_ARTWORK_ACTIVATE','BBS_Card_Master_Artwork',(string)$id,"Activated $kind $side Master Artwork.");json_response(['success'=>true,'data'=>bbs_designer_master_payload(db_row('SELECT * FROM BBS_Card_Master_Artwork WHERE id=?',[$id]))],201);}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();if(is_file($upload['target']))@unlink($upload['target']);throw$e;}}
        $masterFile=route_params($path,'/bbs/admin/card-master-artwork/:id/file');if($method==='GET'&&$masterFile!==null){$id=bbs_phase1_positive_int($masterFile['id']);$row=$id?db_row('SELECT * FROM BBS_Card_Master_Artwork WHERE id=?',[$id]):null;if(!$row)json_response(['success'=>false,'message'=>'Master Artwork was not found.'],404);$file=bbs_designer_master_dir().'/'.basename((string)$row['StoredName']);if(!is_file($file)||bbs_card_file_mime($file)!==$row['MimeType'])json_response(['success'=>false,'message'=>'Master Artwork file is unavailable.'],404);header('Content-Type: '.$row['MimeType']);header("Content-Disposition: inline; filename*=UTF-8''".rawurlencode((string)$row['OriginalName']));header('Cache-Control: private, no-store');readfile($file);exit;}
        if($method==='GET'&&$path==='/bbs/admin/card-designer/catalog'){$catalog=bbs_designer_catalog();$slots=['Personal'=>['Front'=>null,'Back'=>null],'Department'=>['Front'=>null,'Back'=>null]];foreach(db_rows("SELECT * FROM BBS_Card_Master_Artwork WHERE Status='Active' ORDER BY FIELD(TemplateKind,'Personal','Department'),FIELD(Side,'Front','Back')")as$row)$slots[$row['TemplateKind']][$row['Side']]=bbs_designer_master_payload($row);$catalog['masterArtwork']=$slots;$catalog['settings']=['designerEnabled'=>bbs_designer_setting('visual_card_designer_enabled')==='1','renderingEnabled'=>bbs_designer_setting('visual_card_designer_rendering_enabled')==='1'];json_response(['success'=>true,'data'=>$catalog]);}
        if($method==='POST'&&$path==='/bbs/admin/card-designer/runtime'){$action=strtolower(bbs_designer_clean(json_body()['action']??'',20));if(!in_array($action,['enable','disable'],true))throw new InvalidArgumentException('Runtime action must be enable or disable.');$pdo=db();$pdo->beginTransaction();try{$rows=$pdo->query("SELECT SettingKey,SettingValue FROM BBS_Settings WHERE SettingKey IN ('staged_admin_only','pilot_scope_only','visual_card_designer_enabled','visual_card_designer_rendering_enabled') FOR UPDATE")->fetchAll();if(count($rows)!==4){$pdo->rollBack();json_response(['success'=>false,'code'=>'BBS_DESIGNER_SETUP_REQUIRED','message'=>'BBS Designer runtime settings are not configured.'],409);}$before=bbs_designer_runtime_settings($rows);if($action==='enable'&&(!$before['stagedAdminOnly']||$before['pilotScopeOnly'])){$pdo->rollBack();json_response(['success'=>false,'code'=>'BBS_DESIGNER_ADMIN_ONLY_REQUIRED','message'=>'Designer runtime can be enabled only while BBS remains Admin-only.'],409);}if($action==='enable'&&$before['designerEnabled']!==$before['renderingEnabled']){$pdo->rollBack();json_response(['success'=>false,'code'=>'BBS_DESIGNER_RUNTIME_STATE_CONFLICT','message'=>'Designer runtime settings are inconsistent; disable them before enabling again.'],409);}$value=$action==='enable'?'1':'0';$stmt=$pdo->prepare("UPDATE BBS_Settings SET SettingValue=?,UpdatedAt=NOW(),UpdatedBy=? WHERE SettingKey IN ('visual_card_designer_enabled','visual_card_designer_rendering_enabled')");$stmt->execute([$value,$admin['id']]);$afterRows=$pdo->query("SELECT SettingKey,SettingValue FROM BBS_Settings WHERE SettingKey IN ('staged_admin_only','pilot_scope_only','visual_card_designer_enabled','visual_card_designer_rendering_enabled') ORDER BY SettingKey")->fetchAll();$settings=bbs_designer_runtime_settings($afterRows);if($settings['designerEnabled']!==$settings['renderingEnabled']||($action==='enable'&&(!$settings['stagedAdminOnly']||$settings['pilotScopeOnly'])))throw new RuntimeException('Designer runtime setting verification failed.');$pdo->commit();bbs_phase1_audit($admin,$action==='enable'?'BBS_CARD_DESIGNER_RUNTIME_ENABLE':'BBS_CARD_DESIGNER_RUNTIME_DISABLE','BBS_Settings','visual_card_designer_runtime',"$action Visual Card Designer runtime while staged Admin-only.");json_response(['success'=>true,'data'=>array_merge($settings,['action'=>$action])]);}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
        $list=route_params($path,'/bbs/admin/card-designer/:kind/:templateId/versions');if($method==='GET'&&$list!==null){$info=bbs_designer_kind_info($list['kind']);$templateId=bbs_phase1_positive_int($list['templateId']);$deleted=(string)($_GET['trash']??'0')==='1'?1:0;if(!$templateId)throw new InvalidArgumentException('Template ID is required.');json_response(['success'=>true,'data'=>db_rows("SELECT id,TemplateKind,VersionNo,WidthMM,HeightMM,DPI,DuplexFlip,BackRotation,Status,BootstrapSource,RowVersion,IsDeleted,CreatedAt,UpdatedAt,ActivatedAt,ArchivedAt,DeletedAt FROM BBS_Card_Layout_Versions WHERE {$info['parentColumn']}=? AND IsDeleted=? ORDER BY VersionNo DESC,id DESC",[$templateId,$deleted])]);}
        if($method==='POST'&&$list!==null){bbs_designer_require_enabled();$info=bbs_designer_kind_info($list['kind']);$templateId=bbs_phase1_positive_int($list['templateId']);$body=json_body();$sourceId=bbs_phase1_positive_int($body['sourceVersionId']??null);if(!$templateId)throw new InvalidArgumentException('Template ID is required.');$pdo=db();$createdFiles=[];$pdo->beginTransaction();try{$stmt=$pdo->prepare("SELECT * FROM {$info['parentTable']} WHERE id=? FOR UPDATE");$stmt->execute([$templateId]);$parent=$stmt->fetch();if(!$parent){$pdo->rollBack();json_response(['success'=>false,'message'=>'Parent template was not found.'],404);}$stmt=$pdo->prepare("SELECT COALESCE(MAX(VersionNo),0)+1 nextNo FROM BBS_Card_Layout_Versions WHERE {$info['parentColumn']}=?");$stmt->execute([$templateId]);$next=(int)$stmt->fetch()['nextNo'];if($sourceId){$source=bbs_designer_detail($sourceId,$pdo,true);if(!$source||$source['TemplateKind']!==$info['kind']||(int)$source[$info['parentColumn']]!==$templateId){$pdo->rollBack();json_response(['success'=>false,'message'=>'Source layout version was not found for this template.'],404);}if(array_filter($source['layout']['elements'],fn($element)=>!empty($element['assetId'])))throw new InvalidArgumentException('Layouts with static private assets must be recreated and re-uploaded for each Draft.');$payload=$source['layout'];}else$payload=bbs_designer_legacy_payload($parent,$info);$layout=bbs_designer_normalize($payload,$info['kind']);$personal=$info['kind']==='Personal'?$templateId:null;$department=$info['kind']==='Department'?$templateId:null;$stmt=$pdo->prepare("INSERT INTO BBS_Card_Layout_Versions(TemplateKind,PersonalTemplateID,DepartmentTemplateID,VersionNo,WidthMM,HeightMM,DPI,DuplexFlip,BackRotation,Status,CreatedBy,UpdatedBy) VALUES(?,?,?,?,?,?,?,?,?,'Draft',?,?)");$stmt->execute([$info['kind'],$personal,$department,$next,$layout['widthMM'],$layout['heightMM'],$layout['dpi'],$layout['duplexFlip'],$layout['backRotation'],$admin['id'],$admin['id']]);$id=(int)$pdo->lastInsertId();$layout=bbs_designer_master_snapshot($pdo,$id,$info['kind'],$layout,(string)$admin['id'],$createdFiles);bbs_designer_insert_content($pdo,$id,$layout);$pdo->commit();bbs_phase1_audit($admin,'BBS_CARD_LAYOUT_DRAFT_CREATE','BBS_Card_Layout_Version',(string)$id,'Created Draft visual card layout from isolated Master Artwork snapshots.');json_response(['success'=>true,'data'=>bbs_designer_detail($id)],201);}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();foreach($createdFiles as$file)if(is_file($file))@unlink($file);throw$e;}}
        $detail=route_params($path,'/bbs/admin/card-designer/versions/:id');if($method==='GET'&&$detail!==null){$id=bbs_phase1_positive_int($detail['id']);if(!$id)throw new InvalidArgumentException('Layout version ID is required.');$row=bbs_designer_detail($id);if(!$row)json_response(['success'=>false,'message'=>'Layout version was not found.'],404);json_response(['success'=>true,'data'=>$row]);}
        if($method==='PUT'&&$detail!==null){bbs_designer_require_enabled();$id=bbs_phase1_positive_int($detail['id']);$body=json_body();$rowVersion=bbs_phase1_positive_int($body['rowVersion']??null);if(!$id||!$rowVersion)throw new InvalidArgumentException('Layout version ID and RowVersion are required.');$pdo=db();$pdo->beginTransaction();try{$current=bbs_designer_detail($id,$pdo,true);if(!$current){$pdo->rollBack();json_response(['success'=>false,'message'=>'Layout version was not found.'],404);}if($current['Status']!=='Draft'){$pdo->rollBack();json_response(['success'=>false,'code'=>'IMMUTABLE_LAYOUT_VERSION','message'=>'Only a Draft layout can be edited.'],409);}if((int)$current['RowVersion']!==$rowVersion){$pdo->rollBack();json_response(['success'=>false,'code'=>'VERSION_CONFLICT','message'=>'Layout was changed by another user.'],409);}$layout=bbs_designer_canonicalize_resources($pdo,$current,bbs_designer_normalize((array)($body['layout']??[]),$current['TemplateKind']));$pdo->prepare('DELETE FROM BBS_Card_Layout_Elements WHERE LayoutVersionID=?')->execute([$id]);$pdo->prepare('DELETE FROM BBS_Card_Layout_Sides WHERE LayoutVersionID=?')->execute([$id]);$pdo->prepare('UPDATE BBS_Card_Layout_Versions SET WidthMM=?,HeightMM=?,DPI=?,DuplexFlip=?,BackRotation=?,UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=?')->execute([$layout['widthMM'],$layout['heightMM'],$layout['dpi'],$layout['duplexFlip'],$layout['backRotation'],$admin['id'],$id]);bbs_designer_insert_content($pdo,$id,$layout);$pdo->commit();bbs_phase1_audit($admin,'BBS_CARD_LAYOUT_DRAFT_UPDATE','BBS_Card_Layout_Version',(string)$id,'Updated Draft visual card layout.');json_response(['success'=>true,'data'=>bbs_designer_detail($id)]);}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
        $lifecycle=route_params($path,'/bbs/admin/card-designer/versions/:id/lifecycle');if($method==='POST'&&$lifecycle!==null){bbs_designer_require_enabled();$id=bbs_phase1_positive_int($lifecycle['id']);$action=strtolower(bbs_designer_clean(json_body()['action']??'',20));if(!$id||!in_array($action,['activate','archive'],true))throw new InvalidArgumentException('Lifecycle action must be activate or archive.');$pdo=db();$pdo->beginTransaction();try{$current=bbs_designer_detail($id,$pdo,true);if(!$current){$pdo->rollBack();json_response(['success'=>false,'message'=>'Layout version was not found.'],404);}$info=bbs_designer_kind_info($current['TemplateKind']);if($action==='activate'){if($current['Status']!=='Draft'){$pdo->rollBack();json_response(['success'=>false,'code'=>'IMMUTABLE_LAYOUT_VERSION','message'=>'Only a Draft layout can be activated.'],409);}if(($current['readiness']['status']??'Blocked')==='Blocked'){$pdo->rollBack();json_response(['success'=>false,'code'=>'LAYOUT_NOT_READY','message'=>'A blocked layout cannot be activated.'],409);}$stmt=$pdo->prepare("UPDATE BBS_Card_Layout_Versions SET Status='Archived',ArchivedAt=NOW(),ArchivedBy=?,UpdatedBy=?,RowVersion=RowVersion+1 WHERE {$info['parentColumn']}=? AND Status='Active'");$stmt->execute([$admin['id'],$admin['id'],$current[$info['parentColumn']]]);$pdo->prepare("UPDATE BBS_Card_Layout_Versions SET Status='Active',ActivatedAt=NOW(),ActivatedBy=?,UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=?")->execute([$admin['id'],$admin['id'],$id]);}else{if($current['Status']!=='Draft'){$pdo->rollBack();json_response(['success'=>false,'code'=>'IMMUTABLE_LAYOUT_VERSION','message'=>'Only a Draft layout can be archived.'],409);}$pdo->prepare("UPDATE BBS_Card_Layout_Versions SET Status='Archived',ArchivedAt=NOW(),ArchivedBy=?,UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=?")->execute([$admin['id'],$admin['id'],$id]);}$pdo->commit();bbs_phase1_audit($admin,$action==='activate'?'BBS_CARD_LAYOUT_ACTIVATE':'BBS_CARD_LAYOUT_ARCHIVE','BBS_Card_Layout_Version',(string)$id,"$action visual card layout.");json_response(['success'=>true,'data'=>bbs_designer_detail($id)]);}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
        $ready=route_params($path,'/bbs/admin/card-designer/versions/:id/readiness');if($method==='POST'&&$ready!==null){$id=bbs_phase1_positive_int($ready['id']);if(!$id)throw new InvalidArgumentException('Layout version ID is required.');$row=bbs_designer_detail($id);if(!$row)json_response(['success'=>false,'message'=>'Layout version was not found.'],404);json_response(['success'=>true,'data'=>$row['readiness']]);}
        $assetUpload=route_params($path,'/bbs/admin/card-designer/versions/:id/assets');if($method==='POST'&&$assetUpload!==null){bbs_designer_require_enabled();$id=bbs_phase1_positive_int($assetUpload['id']);$assetKey=bbs_card_clean($_POST['assetKey']??'',80);if(!$id||!preg_match('/^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$/',$assetKey))json_response(['success'=>false,'message'=>'A valid asset key is required.'],400);$upload=bbs_designer_upload_asset('asset');$pdo=db();$pdo->beginTransaction();try{$current=bbs_designer_detail($id,$pdo,true);if(!$current){$pdo->rollBack();@unlink($upload['target']);json_response(['success'=>false,'message'=>'Layout version was not found.'],404);}if($current['Status']!=='Draft'){$pdo->rollBack();@unlink($upload['target']);json_response(['success'=>false,'code'=>'IMMUTABLE_LAYOUT_VERSION','message'=>'Assets can be uploaded only to a Draft layout.'],409);}$stmt=$pdo->prepare("INSERT INTO BBS_Card_Layout_Assets(LayoutVersionID,AssetKey,StoredName,OriginalName,MimeType,FileSize,Status,CreatedBy) VALUES(?,?,?,?,?,?,'Active',?)");$stmt->execute([$id,$assetKey,$upload['stored'],$upload['name'],$upload['mime'],$upload['size'],$admin['id']]);$assetId=(int)$pdo->lastInsertId();$pdo->commit();bbs_phase1_audit($admin,'BBS_CARD_LAYOUT_ASSET_UPLOAD','BBS_Card_Layout_Asset',(string)$assetId,"layout=$id; key=$assetKey");json_response(['success'=>true,'data'=>bbs_designer_asset_payload(db_row('SELECT * FROM BBS_Card_Layout_Assets WHERE id=?',[$assetId]))],201);}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();@unlink($upload['target']);throw$e;}}
        $assetFile=route_params($path,'/bbs/admin/card-designer/assets/:assetId/file');if($method==='GET'&&$assetFile!==null){$assetId=bbs_phase1_positive_int($assetFile['assetId']);$row=db_row("SELECT * FROM BBS_Card_Layout_Assets WHERE id=? AND Status='Active'",[$assetId]);if(!$row)json_response(['success'=>false,'message'=>'Designer asset was not found.'],404);$file=bbs_designer_asset_dir().'/'.basename((string)$row['StoredName']);if(!is_file($file)||bbs_card_file_mime($file)!==$row['MimeType'])json_response(['success'=>false,'message'=>'Designer asset file is unavailable.'],404);header('Content-Type: '.$row['MimeType']);header("Content-Disposition: inline; filename*=UTF-8''".rawurlencode((string)$row['OriginalName']));header('Cache-Control: private, no-store');readfile($file);exit;}
        $background=route_params($path,'/bbs/admin/card-designer/versions/:id/sides/:side/background');if($method==='GET'&&$background!==null){$id=bbs_phase1_positive_int($background['id']);$side=strtolower((string)$background['side'])==='back'?'Back':'Front';$row=db_row('SELECT StorageClass,BackgroundStoredName,BackgroundOriginalName,BackgroundMimeType FROM BBS_Card_Layout_Sides WHERE LayoutVersionID=? AND Side=?',[$id,$side]);if(!$row||!in_array($row['StorageClass'],['PersonalTemplate','DepartmentTemplate','DesignerAsset'],true))json_response(['success'=>false,'message'=>'Layout background was not found.'],404);$root=$row['StorageClass']==='DesignerAsset'?bbs_designer_asset_dir():bbs_card_template_dir();$file=$root.'/'.basename((string)$row['BackgroundStoredName']);if(!is_file($file)||bbs_card_file_mime($file)!==$row['BackgroundMimeType'])json_response(['success'=>false,'message'=>'Layout background file is unavailable.'],404);header('Content-Type: '.$row['BackgroundMimeType']);header("Content-Disposition: inline; filename*=UTF-8''".rawurlencode((string)$row['BackgroundOriginalName']));header('Cache-Control: private, no-store');readfile($file);exit;}
        if($method==='GET'&&$path==='/bbs/admin/card-layout-presets'){$kind=bbs_designer_kind($_GET['kind']??'');$status=(string)($_GET['trash']??'0')==='1'?'Trashed':'Active';$rows=db_rows('SELECT * FROM BBS_Card_Layout_Presets WHERE TemplateKind=? AND Status=? ORDER BY UpdatedAt DESC,id DESC',[$kind,$status]);json_response(['success'=>true,'data'=>array_map('bbs_designer_preset_payload',$rows)]);}
        if($method==='POST'&&$path==='/bbs/admin/card-layout-presets'){bbs_designer_require_enabled();$body=json_body();$layoutId=bbs_phase1_positive_int($body['layoutVersionId']??null);$name=bbs_designer_clean($body['presetName']??'',160);if(!$layoutId||$name==='')throw new InvalidArgumentException('Draft layout and Preset name are required.');$pdo=db();$pdo->beginTransaction();try{$current=bbs_designer_detail($layoutId,$pdo,true);if(!$current){$pdo->rollBack();json_response(['success'=>false,'message'=>'Draft layout was not found.'],404);}if($current['Status']!=='Draft'){$pdo->rollBack();json_response(['success'=>false,'code'=>'IMMUTABLE_LAYOUT_VERSION','message'=>'A Preset can be saved only from a Draft layout.'],409);}$layout=bbs_designer_reusable_preset($current['layout']);$stmt=$pdo->prepare("INSERT INTO BBS_Card_Layout_Presets(TemplateKind,PresetName,LayoutJSON,Status,CreatedBy,UpdatedBy) VALUES(?,?,?,'Active',?,?)");$stmt->execute([$current['TemplateKind'],$name,json_encode($layout,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$admin['id'],$admin['id']]);$id=(int)$pdo->lastInsertId();$pdo->commit();bbs_phase1_audit($admin,'BBS_CARD_LAYOUT_PRESET_CREATE','BBS_Card_Layout_Preset',(string)$id,'Created '.$current['TemplateKind'].' layout Preset.');json_response(['success'=>true,'data'=>bbs_designer_preset_payload(db_row('SELECT * FROM BBS_Card_Layout_Presets WHERE id=?',[$id]))],201);}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
        $presetApply=route_params($path,'/bbs/admin/card-layout-presets/:id/apply');if($method==='POST'&&$presetApply!==null){bbs_designer_require_enabled();$body=json_body();$presetId=bbs_phase1_positive_int($presetApply['id']);$layoutId=bbs_phase1_positive_int($body['layoutVersionId']??null);$rowVersion=bbs_phase1_positive_int($body['rowVersion']??null);if(!$presetId||!$layoutId||!$rowVersion)throw new InvalidArgumentException('Preset, Draft layout, and RowVersion are required.');$pdo=db();$pdo->beginTransaction();try{$stmt=$pdo->prepare("SELECT * FROM BBS_Card_Layout_Presets WHERE id=? AND Status='Active' FOR UPDATE");$stmt->execute([$presetId]);$preset=$stmt->fetch();$current=bbs_designer_detail($layoutId,$pdo,true);if(!$preset||!$current){$pdo->rollBack();json_response(['success'=>false,'message'=>'Preset or Draft layout was not found.'],404);}if($current['Status']!=='Draft'){$pdo->rollBack();json_response(['success'=>false,'code'=>'IMMUTABLE_LAYOUT_VERSION','message'=>'A Preset can be applied only to a Draft layout.'],409);}if((int)$current['RowVersion']!==$rowVersion){$pdo->rollBack();json_response(['success'=>false,'code'=>'VERSION_CONFLICT','message'=>'Layout was changed by another user.'],409);}if($preset['TemplateKind']!==$current['TemplateKind']){$pdo->rollBack();json_response(['success'=>false,'code'=>'PRESET_KIND_MISMATCH','message'=>'Personal and Department Presets cannot be used across card types.'],409);}$stored=json_decode((string)$preset['LayoutJSON'],true);if(!is_array($stored))throw new InvalidArgumentException('Preset content is invalid.');$layout=bbs_designer_canonicalize_resources($pdo,$current,bbs_designer_normalize(bbs_designer_apply_preset($current['layout'],$stored),$current['TemplateKind']));$pdo->prepare('DELETE FROM BBS_Card_Layout_Elements WHERE LayoutVersionID=?')->execute([$layoutId]);$pdo->prepare('DELETE FROM BBS_Card_Layout_Sides WHERE LayoutVersionID=?')->execute([$layoutId]);$pdo->prepare('UPDATE BBS_Card_Layout_Versions SET WidthMM=?,HeightMM=?,DPI=?,DuplexFlip=?,BackRotation=?,UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=?')->execute([$layout['widthMM'],$layout['heightMM'],$layout['dpi'],$layout['duplexFlip'],$layout['backRotation'],$admin['id'],$layoutId]);bbs_designer_insert_content($pdo,$layoutId,$layout);$pdo->commit();bbs_phase1_audit($admin,'BBS_CARD_LAYOUT_PRESET_APPLY','BBS_Card_Layout_Version',(string)$layoutId,'Applied '.$current['TemplateKind'].' layout Preset.');json_response(['success'=>true,'data'=>bbs_designer_detail($layoutId)]);}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
        $preset=route_params($path,'/bbs/admin/card-layout-presets/:id');if($method==='DELETE'&&$preset!==null){bbs_designer_require_enabled();$body=json_body();$id=bbs_phase1_positive_int($preset['id']);$version=bbs_phase1_positive_int($body['rowVersion']??null);if(!$id||!$version)throw new InvalidArgumentException('Preset and RowVersion are required.');$stmt=db()->prepare("UPDATE BBS_Card_Layout_Presets SET Status='Trashed',TrashedAt=NOW(),TrashedBy=?,UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=? AND Status='Active' AND RowVersion=?");$stmt->execute([$admin['id'],$admin['id'],$id,$version]);if(!$stmt->rowCount())json_response(['success'=>false,'code'=>'VERSION_CONFLICT','message'=>'Preset changed or is already in Trash.'],409);bbs_phase1_audit($admin,'BBS_CARD_LAYOUT_PRESET_TRASH','BBS_Card_Layout_Preset',(string)$id,'Moved layout Preset to recoverable Trash.');json_response(['success'=>true]);}
        $presetRestore=route_params($path,'/bbs/admin/card-layout-presets/:id/restore');if($method==='POST'&&$presetRestore!==null){bbs_designer_require_enabled();$body=json_body();$id=bbs_phase1_positive_int($presetRestore['id']);$version=bbs_phase1_positive_int($body['rowVersion']??null);if(!$id||!$version)throw new InvalidArgumentException('Preset and RowVersion are required.');$stmt=db()->prepare("UPDATE BBS_Card_Layout_Presets SET Status='Active',TrashedAt=NULL,TrashedBy=NULL,UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=? AND Status='Trashed' AND RowVersion=?");$stmt->execute([$admin['id'],$id,$version]);if(!$stmt->rowCount())json_response(['success'=>false,'code'=>'VERSION_CONFLICT','message'=>'Preset changed or is no longer in Trash.'],409);bbs_phase1_audit($admin,'BBS_CARD_LAYOUT_PRESET_RESTORE','BBS_Card_Layout_Preset',(string)$id,'Restored layout Preset from Trash.');json_response(['success'=>true]);}
        if($method==='DELETE'&&$detail!==null){bbs_designer_require_enabled();$body=json_body();$id=bbs_phase1_positive_int($detail['id']);$version=bbs_phase1_positive_int($body['rowVersion']??null);if(!$id||!$version)throw new InvalidArgumentException('Draft layout and RowVersion are required.');$stmt=db()->prepare("UPDATE BBS_Card_Layout_Versions SET IsDeleted=1,DeletedAt=NOW(),DeletedBy=?,UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=? AND Status='Draft' AND IsDeleted=0 AND RowVersion=?");$stmt->execute([$admin['id'],$admin['id'],$id,$version]);if(!$stmt->rowCount())json_response(['success'=>false,'code'=>'SAFE_TRASH_REJECTED','message'=>'Only an unchanged Draft layout can be moved to Trash.'],409);bbs_phase1_audit($admin,'BBS_CARD_LAYOUT_TRASH','BBS_Card_Layout_Version',(string)$id,'Moved Draft layout to recoverable Trash; assets and history were retained.');json_response(['success'=>true]);}
        $layoutRestore=route_params($path,'/bbs/admin/card-designer/versions/:id/restore');if($method==='POST'&&$layoutRestore!==null){bbs_designer_require_enabled();$body=json_body();$id=bbs_phase1_positive_int($layoutRestore['id']);$version=bbs_phase1_positive_int($body['rowVersion']??null);if(!$id||!$version)throw new InvalidArgumentException('Draft layout and RowVersion are required.');$stmt=db()->prepare("UPDATE BBS_Card_Layout_Versions SET IsDeleted=0,DeletedAt=NULL,DeletedBy=NULL,UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=? AND Status='Draft' AND IsDeleted=1 AND RowVersion=?");$stmt->execute([$admin['id'],$id,$version]);if(!$stmt->rowCount())json_response(['success'=>false,'code'=>'VERSION_CONFLICT','message'=>'Draft layout changed or is no longer in Trash.'],409);bbs_phase1_audit($admin,'BBS_CARD_LAYOUT_RESTORE','BBS_Card_Layout_Version',(string)$id,'Restored Draft layout from Trash.');json_response(['success'=>true,'data'=>bbs_designer_detail($id)]);}
        return false;
    }catch(Throwable$e){bbs_designer_error($e);}return true;
}
