<?php
declare(strict_types=1);

require_once __DIR__.'/../lib/safety_vote_phase1.php';

const SV_REQUIRED_TABLES=['SafetyVote_Settings','SafetyVote_Campaigns','SafetyVote_CampaignVersions','SafetyVote_Stages','SafetyVote_EligibilityRules','SafetyVote_EligibilitySnapshots','SafetyVote_EligibleVoters','SafetyVote_CampaignRoles','SafetyVote_Files','SafetyVote_AuditLogs','SafetyVote_Questions','SafetyVote_Options','SafetyVote_Candidates','SafetyVote_Participation','SafetyVote_Ballots','SafetyVote_BallotIdentities','SafetyVote_BallotAnswers','SafetyVote_RequestKeys','SafetyVote_Submissions','SafetyVote_Nominations','SafetyVote_JuryCriteria','SafetyVote_JuryAssignments','SafetyVote_JuryScores','SafetyVote_ResultSnapshots','SafetyVote_ResultRows','SafetyVote_Certifications','SafetyVote_StageAdvancements','SafetyVote_Reports','SafetyVote_ExportJobs','SafetyVote_Notifications','SafetyVote_NotificationDeliveries'];
const SV_SCHEMA_VERSION='2026-10-08-phase5-r1';
const SV_PERMISSIONS=['SAFETY_VOTE_VIEW','SAFETY_VOTE_CREATE','SAFETY_VOTE_MANAGE','SAFETY_VOTE_ELIGIBILITY_MANAGE','SAFETY_VOTE_SUBMISSION_REVIEW','SAFETY_VOTE_JURY','SAFETY_VOTE_RESULT_VIEW','SAFETY_VOTE_CERTIFY','SAFETY_VOTE_EXPORT','SAFETY_VOTE_AUDIT_VIEW','SAFETY_VOTE_ADMIN'];

function sv_actor(array $user): string{return trim((string)($user['id']??$user['EmployeeID']??''));}
function sv_role(array $user): string{return strtoupper(trim((string)($user['role']??$user['Role']??'')));}
function sv_schema_health(): array { $marks=implode(',',array_fill(0,count(SV_REQUIRED_TABLES),'?'));$rows=db_rows("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ($marks)",SV_REQUIRED_TABLES);$found=[];foreach($rows as$row)$found[strtolower((string)$row['TABLE_NAME'])]=true;$missing=array_values(array_filter(SV_REQUIRED_TABLES,fn($name)=>!isset($found[strtolower($name)])));if($missing)return['ready'=>false,'missing'=>$missing,'contractVersion'=>SAFETY_VOTE_CONTRACT_VERSION,'schemaVersion'=>null,'moduleEnabled'=>false];$map=[];foreach(db_rows("SELECT SettingKey,SettingValue FROM SafetyVote_Settings WHERE SettingKey IN ('contract_version','schema_version','module_enabled')")as$row)$map[$row['SettingKey']]=(string)$row['SettingValue'];return['ready'=>($map['contract_version']??'')===SAFETY_VOTE_CONTRACT_VERSION&&in_array($map['schema_version']??'',[SV_SCHEMA_VERSION,'2026-10-08-phase6-r1','2026-10-08-phase7-r1'],true),'missing'=>[],'contractVersion'=>$map['contract_version']??null,'schemaVersion'=>$map['schema_version']??null,'moduleEnabled'=>($map['module_enabled']??'0')==='1']; }
function sv_require_schema(): array { try{$health=sv_schema_health();}catch(Throwable$error){json_response(['success'=>false,'code'=>'SAFETY_VOTE_SCHEMA_NOT_READY','message'=>'Unable to verify Safety Vote schema.'],503);}if(empty($health['ready']))json_response(['success'=>false,'code'=>'SAFETY_VOTE_SCHEMA_NOT_READY','message'=>'Safety Vote schema is not ready.','details'=>$health],503);return$health; }
function sv_has_permission(array$user,string$permission): bool {if(sv_role($user)==='ADMIN')return true;$override=db_row('SELECT granted FROM admin_userpermissions WHERE employee_id=? AND permission=? LIMIT 1',[sv_actor($user),$permission]);if($override)return(int)$override['granted']===1;$role=db_row('SELECT granted FROM admin_rolepermissions WHERE UPPER(role)=? AND permission=? LIMIT 1',[sv_role($user),$permission]);if($role&&(int)$role['granted']===1)return true;$admin=db_row('SELECT granted FROM admin_userpermissions WHERE employee_id=? AND permission=? LIMIT 1',[sv_actor($user),'SAFETY_VOTE_ADMIN']);return$admin&&(int)$admin['granted']===1;}
function sv_require_permission(array$user,string$permission): void {if(!sv_has_permission($user,$permission))json_response(['success'=>false,'code'=>'PERMISSION_DENIED','message'=>'Safety Vote permission is required.'],403);}
function sv_audit(array$user,string$action,string$targetType,string$targetId,string$detail,array$metadata=[],?int$campaignId=null,?int$versionId=null): void {try{db_execute('INSERT INTO SafetyVote_AuditLogs(CampaignID,CampaignVersionID,ActorEmployeeID,ActorRole,Action,TargetType,TargetID,StatusCode,BoundedDetail,MetadataJson,IPAddress,UserAgent) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[$campaignId,$versionId,sv_actor($user),sv_role($user),$action,$targetType,$targetId,200,sv_clean($detail,1000)?:null,json_encode($metadata,JSON_UNESCAPED_UNICODE),(string)($_SERVER['REMOTE_ADDR']??''),mb_substr((string)($_SERVER['HTTP_USER_AGENT']??''),0,255)]);}catch(Throwable$error){error_log('[safety-vote] audit failed: '.$error->getMessage());}}
function sv_campaign_row(int$id,bool$lock=false): ?array {return db_row("SELECT c.*,v.VersionNo,v.ContractVersion,v.TemplateKey,v.CampaignType,v.PrivacyMode,v.TitleTh,v.TitleEn,v.Summary,v.Description,v.RulesText,v.TimeZone,v.OpenAt,v.CloseAt,v.ResultVisibility,v.PrivacyThreshold,v.Status VersionStatus,v.RowVersion VersionRowVersion FROM SafetyVote_Campaigns c JOIN SafetyVote_CampaignVersions v ON v.id=c.CurrentVersionID WHERE c.id=?".($lock?' FOR UPDATE':''),[$id]);}
function sv_master_projection(): array { $employees=db_rows('SELECT EmployeeID,EmployeeName,Department,Unit,Team,Position,Role,Password,MustChangePassword FROM employees ORDER BY EmployeeID');$departments=db_rows('SELECT id,Name,Status,is_safety_core FROM master_departments ORDER BY Name');$units=db_rows('SELECT id,name,department_id,short_code,sort_order FROM master_safetyunits ORDER BY department_id,sort_order,name');$positions=db_rows('SELECT id,Name FROM master_positions ORDER BY Name');$index=onboarding_build_master_index(['departments'=>$departments,'units'=>$units]);$key=fn($value)=>onboarding_normalize_name($value);$dept=[];$unit=[];$pos=[];foreach($departments as$row)$dept[$key($row['Name'])]=$row;foreach($units as$row)$unit[(string)$row['department_id']."\0".$key($row['name'])]=$row;foreach($positions as$row)$pos[$key($row['Name'])]=$row;$rows=[];foreach($employees as$row){$d=$dept[$key($row['Department'])]??null;$u=$d?($unit[(string)$d['id']."\0".$key($row['Unit'])]??null):null;$p=$pos[$key($row['Position'])]??null;try{$status=onboarding_resolve_with_index($row,$index);}catch(OnboardingResolutionException$error){$status=$error->reason;}$warnings=[];if(!$d)$warnings[]='DEPARTMENT_UNRESOLVED';if($d&&!$u&&array_filter($units,fn($x)=>(int)$x['department_id']===(int)$d['id']))$warnings[]='SAFETY_UNIT_UNRESOLVED';if(!$p)$warnings[]='POSITION_UNRESOLVED';$rows[]=['employeeId'=>(string)$row['EmployeeID'],'employeeName'=>(string)($row['EmployeeName']??''),'departmentId'=>$d?(int)$d['id']:null,'departmentName'=>(string)($row['Department']??''),'safetyUnitId'=>$u?(int)$u['id']:null,'safetyUnitName'=>(string)($row['Unit']??''),'positionId'=>$p?(int)$p['id']:null,'positionName'=>(string)($row['Position']??''),'role'=>(string)($row['Role']??''),'team'=>(string)($row['Team']??''),'masterPresent'=>true,'accountReady'=>$status===ONBOARDING_READY,'onboardingStatus'=>$status,'masterWarnings'=>$warnings];}return['employees'=>$rows,'departments'=>$departments,'units'=>$units,'positions'=>$positions]; }
function sv_private_dir(): string {$dir=dirname(__DIR__).DIRECTORY_SEPARATOR.'private'.DIRECTORY_SEPARATOR.'safety-vote';if(!is_dir($dir)&&!mkdir($dir,0770,true)&&!is_dir($dir))throw new RuntimeException('Unable to prepare Safety Vote private storage.');return$dir;}
function sv_file_mime(string$file): ?string {$head=(string)file_get_contents($file,false,null,0,16);if(strlen($head)>=3&&ord($head[0])===0xff&&ord($head[1])===0xd8&&ord($head[2])===0xff)return'image/jpeg';if(substr($head,0,8)==="\x89PNG\r\n\x1a\n")return'image/png';if(substr($head,0,4)==='RIFF'&&substr($head,8,4)==='WEBP')return'image/webp';if(substr($head,0,5)==='%PDF-')return'application/pdf';return null;}

function handle_safety_vote_routes(string$method,string$path): bool {
    if(strpos($path,'/safety-vote/')!==0)return false;$user=require_user();
    if($method==='GET'&&$path==='/safety-vote/admin/health'){sv_require_permission($user,'SAFETY_VOTE_VIEW');$health=sv_schema_health();json_response(['success'=>$health['ready'],'data'=>$health]+(!$health['ready']?['code'=>'SAFETY_VOTE_SCHEMA_NOT_READY','message'=>'Safety Vote schema is not ready.']:[]),$health['ready']?200:503);}
    sv_require_schema();
    if($method==='GET'&&$path==='/safety-vote/admin/permissions'){sv_require_permission($user,'SAFETY_VOTE_VIEW');json_response(['success'=>true,'data'=>['permissions'=>SV_PERMISSIONS,'admin'=>sv_role($user)==='ADMIN']]);}
    if($method==='GET'&&$path==='/safety-vote/admin/campaigns'){sv_require_permission($user,'SAFETY_VOTE_MANAGE');$rows=db_rows('SELECT c.id,c.CampaignCode,c.Status,c.OwnerEmployeeID,c.DiscoveryMode,c.RowVersion,c.CreatedAt,c.UpdatedAt,v.VersionNo,v.CampaignType,v.PrivacyMode,v.TitleTh,v.TitleEn,v.ResultVisibility,v.RowVersion VersionRowVersion FROM SafetyVote_Campaigns c JOIN SafetyVote_CampaignVersions v ON v.id=c.CurrentVersionID ORDER BY c.UpdatedAt DESC,c.id DESC LIMIT 250');json_response(['success'=>true,'data'=>['rows'=>$rows,'total'=>count($rows)]]);}
    if($method==='POST'&&$path==='/safety-vote/admin/campaigns'){sv_require_permission($user,'SAFETY_VOTE_CREATE');$parsed=sv_campaign(json_body());if(!$parsed['ok'])json_response(['success'=>false,'code'=>'VALIDATION_FAILED','message'=>'Campaign validation failed.','details'=>$parsed['errors']],400);$v=$parsed['value'];$pdo=db();$pdo->beginTransaction();try{$stmt=$pdo->prepare("INSERT INTO SafetyVote_Campaigns(CampaignCode,Status,OwnerEmployeeID,DiscoveryMode,ScheduledOpenAt,ScheduledCloseAt,CreatedBy,UpdatedBy) VALUES(?,'Draft',?,?,?,?,?,?)");$stmt->execute([$v['campaignCode'],sv_actor($user),$v['discoveryMode'],$v['openAt'],$v['closeAt'],sv_actor($user),sv_actor($user)]);$id=(int)$pdo->lastInsertId();$stmt=$pdo->prepare('INSERT INTO SafetyVote_CampaignVersions(CampaignID,VersionNo,ContractVersion,TemplateKey,CampaignType,PrivacyMode,TitleTh,TitleEn,Summary,Description,RulesText,OpenAt,CloseAt,ResultVisibility,PrivacyThreshold,CreatedBy,UpdatedBy) VALUES(?,1,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$stmt->execute([$id,SAFETY_VOTE_CONTRACT_VERSION,$v['templateKey'],$v['campaignType'],$v['privacyMode'],$v['titleTh'],$v['titleEn'],$v['summary'],$v['description'],$v['rulesText'],$v['openAt'],$v['closeAt'],$v['resultVisibility'],$v['privacyThreshold'],sv_actor($user),sv_actor($user)]);$versionId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE SafetyVote_Campaigns SET CurrentVersionID=? WHERE id=?')->execute([$versionId,$id]);$pdo->commit();sv_audit($user,'SAFETY_VOTE_CAMPAIGN_CREATE','SafetyVote_Campaign',(string)$id,'code='.$v['campaignCode'].'; type='.$v['campaignType'],[],$id,$versionId);json_response(['success'=>true,'data'=>sv_campaign_row($id)],201);}catch(Throwable$error){if($pdo->inTransaction())$pdo->rollBack();if((string)$error->getCode()==='23000')json_response(['success'=>false,'code'=>'CAMPAIGN_CODE_EXISTS','message'=>'Campaign code already exists.'],409);throw$error;}}
    $campaign=route_params($path,'/safety-vote/admin/campaigns/:id');
    if($campaign!==null&&$method==='GET'){sv_require_permission($user,'SAFETY_VOTE_MANAGE');$id=sv_positive_int($campaign['id']);$row=$id?sv_campaign_row($id):null;if(!$row)json_response(['success'=>false,'code'=>'CAMPAIGN_NOT_FOUND','message'=>'Campaign was not found.'],404);$rules=db_rows('SELECT * FROM SafetyVote_EligibilityRules WHERE CampaignVersionID=? ORDER BY RuleGroup,RuleOrder,id',[$row['CurrentVersionID']]);foreach($rules as&$rule)$rule['values']=json_decode((string)$rule['ValuesJson'],true)?:[];unset($rule);json_response(['success'=>true,'data'=>['campaign'=>$row,'eligibilityRules'=>$rules]]);}
    if($campaign!==null&&$method==='PUT'){sv_require_permission($user,'SAFETY_VOTE_MANAGE');$id=sv_positive_int($campaign['id']);$body=json_body();$expected=sv_positive_int($body['rowVersion']??null);if(!$id||!$expected)json_response(['success'=>false,'code'=>'VALIDATION_FAILED','message'=>'Campaign ID and rowVersion are required.'],400);$parsed=sv_campaign($body);if(!$parsed['ok'])json_response(['success'=>false,'code'=>'VALIDATION_FAILED','message'=>'Campaign validation failed.','details'=>$parsed['errors']],400);$pdo=db();$pdo->beginTransaction();try{$row=sv_campaign_row($id,true);if(!$row){$pdo->rollBack();json_response(['success'=>false,'code'=>'CAMPAIGN_NOT_FOUND','message'=>'Campaign was not found.'],404);}if($row['Status']!=='Draft'||$row['VersionStatus']!=='Draft'){$pdo->rollBack();json_response(['success'=>false,'code'=>'CAMPAIGN_STATE_CONFLICT','message'=>'Only Draft campaigns can be edited.'],409);}if((int)$row['RowVersion']!==$expected){$pdo->rollBack();json_response(['success'=>false,'code'=>'VERSION_CONFLICT','message'=>'Campaign changed. Reload before saving.'],409);}$v=$parsed['value'];$pdo->prepare('UPDATE SafetyVote_Campaigns SET CampaignCode=?,DiscoveryMode=?,ScheduledOpenAt=?,ScheduledCloseAt=?,UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=?')->execute([$v['campaignCode'],$v['discoveryMode'],$v['openAt'],$v['closeAt'],sv_actor($user),$id]);$pdo->prepare('UPDATE SafetyVote_CampaignVersions SET TemplateKey=?,CampaignType=?,PrivacyMode=?,TitleTh=?,TitleEn=?,Summary=?,Description=?,RulesText=?,OpenAt=?,CloseAt=?,ResultVisibility=?,PrivacyThreshold=?,UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=?')->execute([$v['templateKey'],$v['campaignType'],$v['privacyMode'],$v['titleTh'],$v['titleEn'],$v['summary'],$v['description'],$v['rulesText'],$v['openAt'],$v['closeAt'],$v['resultVisibility'],$v['privacyThreshold'],sv_actor($user),$row['CurrentVersionID']]);$pdo->commit();sv_audit($user,'SAFETY_VOTE_CAMPAIGN_UPDATE','SafetyVote_Campaign',(string)$id,'code='.$v['campaignCode'],[],$id,(int)$row['CurrentVersionID']);json_response(['success'=>true,'data'=>sv_campaign_row($id)]);}catch(Throwable$error){if($pdo->inTransaction())$pdo->rollBack();if((string)$error->getCode()==='23000')json_response(['success'=>false,'code'=>'CAMPAIGN_CODE_EXISTS','message'=>'Campaign code already exists.'],409);throw$error;}}
    if($campaign!==null&&$method==='DELETE'){sv_require_permission($user,'SAFETY_VOTE_MANAGE');$id=sv_positive_int($campaign['id']);$body=json_body();$reason=sv_clean($body['reason']??'',500);if(!$id||!$reason)json_response(['success'=>false,'code'=>'VALIDATION_FAILED','message'=>'Campaign ID and void reason are required.'],400);$pdo=db();$pdo->beginTransaction();try{$row=sv_campaign_row($id,true);if(!$row){$pdo->rollBack();json_response(['success'=>false,'code'=>'CAMPAIGN_NOT_FOUND','message'=>'Campaign was not found.'],404);}if($row['Status']!=='Draft'||$row['VersionStatus']!=='Draft'){$pdo->rollBack();json_response(['success'=>false,'code'=>'CAMPAIGN_STATE_CONFLICT','message'=>'Only Draft campaigns can be voided.'],409);}$pdo->prepare("UPDATE SafetyVote_Campaigns SET Status='Voided',VoidedAt=NOW(),VoidedBy=?,VoidReason=?,UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=?")->execute([sv_actor($user),$reason,sv_actor($user),$id]);$pdo->prepare("UPDATE SafetyVote_CampaignVersions SET Status='Voided',UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=?")->execute([sv_actor($user),$row['CurrentVersionID']]);$pdo->commit();sv_audit($user,'SAFETY_VOTE_CAMPAIGN_VOID','SafetyVote_Campaign',(string)$id,$reason,[],$id,(int)$row['CurrentVersionID']);json_response(['success'=>true,'data'=>['id'=>$id,'status'=>'Voided']]);}catch(Throwable$error){if($pdo->inTransaction())$pdo->rollBack();throw$error;}}
    $masterMap=['/safety-vote/admin/master/departments'=>'departments','/safety-vote/admin/master/safety-units'=>'units','/safety-vote/admin/master/positions'=>'positions'];if($method==='GET'&&isset($masterMap[$path])){sv_require_permission($user,'SAFETY_VOTE_MANAGE');$data=sv_master_projection();json_response(['success'=>true,'data'=>$data[$masterMap[$path]]]);}
    if($method==='GET'&&$path==='/safety-vote/admin/master/employees'){sv_require_permission($user,'SAFETY_VOTE_MANAGE');$data=sv_master_projection();$q=mb_strtolower(sv_clean($_GET['q']??'',100),'UTF-8');$departmentId=sv_positive_int($_GET['departmentId']??null);$unitId=sv_positive_int($_GET['safetyUnitId']??null);$rows=array_values(array_filter($data['employees'],function($row)use($q,$departmentId,$unitId){if($q!==''&&!array_filter([$row['employeeId'],$row['employeeName'],$row['departmentName'],$row['safetyUnitName'],$row['positionName']],fn($v)=>mb_strpos(mb_strtolower((string)$v,'UTF-8'),$q)!==false))return false;if($departmentId&&(int)$row['departmentId']!==$departmentId)return false;if($unitId&&(int)$row['safetyUnitId']!==$unitId)return false;return true;}));$page=max(1,sv_positive_int($_GET['page']??null)??1);$pageSize=min(100,max(1,sv_positive_int($_GET['pageSize']??null)??25));json_response(['success'=>true,'data'=>['rows'=>array_slice($rows,($page-1)*$pageSize,$pageSize),'total'=>count($rows),'page'=>$page,'pageSize'=>$pageSize]]);}
    $ruleRoute=route_params($path,'/safety-vote/admin/campaigns/:id/eligibility/rules');if($method==='PUT'&&$ruleRoute!==null){sv_require_permission($user,'SAFETY_VOTE_ELIGIBILITY_MANAGE');$id=sv_positive_int($ruleRoute['id']);$body=json_body();$parsed=sv_rules($body['rules']??null);if(!$id||!$parsed['ok'])json_response(['success'=>false,'code'=>'VALIDATION_FAILED','message'=>'Eligibility rules are invalid.','details'=>$parsed['errors']],400);$pdo=db();$pdo->beginTransaction();try{$row=sv_campaign_row($id,true);if(!$row){$pdo->rollBack();json_response(['success'=>false,'code'=>'CAMPAIGN_NOT_FOUND','message'=>'Campaign was not found.'],404);}if($row['Status']!=='Draft'){$pdo->rollBack();json_response(['success'=>false,'code'=>'CAMPAIGN_STATE_CONFLICT','message'=>'Eligibility rules are editable only in Draft.'],409);}$pdo->prepare('DELETE FROM SafetyVote_EligibilityRules WHERE CampaignVersionID=?')->execute([$row['CurrentVersionID']]);$stmt=$pdo->prepare('INSERT INTO SafetyVote_EligibilityRules(CampaignVersionID,RuleGroup,RuleOrder,Effect,AttributeKey,Operator,ValuesJson,Reason,CreatedBy,UpdatedBy) VALUES(?,?,?,?,?,?,?,?,?,?)');foreach($parsed['rules']as$rule)$stmt->execute([$row['CurrentVersionID'],$rule['ruleGroup'],$rule['ruleOrder'],$rule['effect'],$rule['attributeKey'],$rule['operator'],json_encode($rule['values'],JSON_UNESCAPED_UNICODE),$rule['reason'],sv_actor($user),sv_actor($user)]);$pdo->commit();$hash=sv_hash($parsed['rules']);sv_audit($user,'SAFETY_VOTE_ELIGIBILITY_RULES_UPDATE','SafetyVote_Campaign',(string)$id,'rules='.count($parsed['rules']),['ruleCount'=>count($parsed['rules']),'ruleHash'=>$hash],$id,(int)$row['CurrentVersionID']);json_response(['success'=>true,'data'=>['rules'=>$parsed['rules'],'ruleHash'=>$hash]]);}catch(Throwable$error){if($pdo->inTransaction())$pdo->rollBack();throw$error;}}
    $preview=route_params($path,'/safety-vote/admin/campaigns/:id/eligibility/preview');if($method==='POST'&&$preview!==null){sv_require_permission($user,'SAFETY_VOTE_ELIGIBILITY_MANAGE');$id=sv_positive_int($preview['id']);$row=$id?sv_campaign_row($id):null;if(!$row)json_response(['success'=>false,'code'=>'CAMPAIGN_NOT_FOUND','message'=>'Campaign was not found.'],404);$body=json_body();if(isset($body['rules'])&&is_array($body['rules']))$parsed=sv_rules($body['rules']);else{$stored=db_rows('SELECT RuleGroup ruleGroup,RuleOrder ruleOrder,Effect effect,AttributeKey attributeKey,Operator operator,ValuesJson,Reason reason FROM SafetyVote_EligibilityRules WHERE CampaignVersionID=? AND IsActive=1 ORDER BY RuleGroup,RuleOrder,id',[$row['CurrentVersionID']]);foreach($stored as&$rule)$rule['values']=json_decode((string)$rule['ValuesJson'],true)?:[];unset($rule);$parsed=sv_rules($stored);}if(!$parsed['ok'])json_response(['success'=>false,'code'=>'VALIDATION_FAILED','message'=>'Eligibility rules are invalid.','details'=>$parsed['errors']],400);$master=sv_master_projection();$eligible=sv_evaluate($parsed['rules'],$master['employees']);$warnings=0;$breakdown=[];foreach($eligible as$employee){$warnings+=count($employee['masterWarnings']);$key=$employee['departmentName']?:'Unresolved';$breakdown[$key]=($breakdown[$key]??0)+1;}json_response(['success'=>true,'data'=>['ruleHash'=>sv_hash($parsed['rules']),'eligibleCount'=>count($eligible),'accountReadyCount'=>count(array_filter($eligible,fn($e)=>$e['accountReady'])),'warningCount'=>$warnings,'breakdown'=>$breakdown,'rows'=>array_slice($eligible,0,250),'truncated'=>count($eligible)>250]]);}
    $upload=route_params($path,'/safety-vote/admin/campaigns/:id/files');if($method==='POST'&&$upload!==null){sv_require_permission($user,'SAFETY_VOTE_MANAGE');$id=sv_positive_int($upload['id']);$row=$id?sv_campaign_row($id):null;$file=$_FILES['file']??null;if(!$row)json_response(['success'=>false,'code'=>'CAMPAIGN_NOT_FOUND','message'=>'Campaign was not found.'],404);if($row['Status']!=='Draft')json_response(['success'=>false,'code'=>'CAMPAIGN_STATE_CONFLICT','message'=>'Files can be added only to Draft campaigns.'],409);if(!$file||(int)$file['error']!==UPLOAD_ERR_OK||(int)$file['size']>10*1024*1024)json_response(['success'=>false,'code'=>'FILE_UPLOAD_REJECTED','message'=>'A file not exceeding 10 MB is required.'],400);$mime=sv_file_mime((string)$file['tmp_name']);if(!$mime||!in_array($mime,['image/jpeg','image/png','image/webp','application/pdf'],true))json_response(['success'=>false,'code'=>'FILE_UPLOAD_REJECTED','message'=>'File content is not an allowed image or PDF.'],400);$ext=['image/jpeg'=>'.jpg','image/png'=>'.png','image/webp'=>'.webp','application/pdf'=>'.pdf'][$mime];$stored=time().'-'.bin2hex(random_bytes(18)).$ext;$target=sv_private_dir().DIRECTORY_SEPARATOR.$stored;if(!move_uploaded_file((string)$file['tmp_name'],$target))json_response(['success'=>false,'code'=>'FILE_UPLOAD_REJECTED','message'=>'Unable to store file.'],500);$sha=hash_file('sha256',$target);try{db_execute('INSERT INTO SafetyVote_Files(CampaignID,CampaignVersionID,FilePurpose,StoredName,OriginalName,MimeType,FileSize,ContentSha256,UploadedBy) VALUES(?,?,?,?,?,?,?,?,?)',[$id,$row['CurrentVersionID'],sv_clean($_POST['filePurpose']??'cover',40),$stored,sv_clean($file['name']??'',255),$mime,(int)$file['size'],$sha,sv_actor($user)]);$fileId=(int)db()->lastInsertId();}catch(Throwable$error){@unlink($target);throw$error;}sv_audit($user,'SAFETY_VOTE_FILE_UPLOAD','SafetyVote_File',(string)$fileId,'size='.(int)$file['size'],['mime'=>$mime,'sha256'=>$sha],$id,(int)$row['CurrentVersionID']);json_response(['success'=>true,'data'=>['id'=>$fileId,'originalName'=>sv_clean($file['name']??'',255),'mimeType'=>$mime,'fileSize'=>(int)$file['size'],'sha256'=>$sha]],201);}
    $fileRoute=route_params($path,'/safety-vote/files/:fileId');if($method==='GET'&&$fileRoute!==null){sv_require_permission($user,'SAFETY_VOTE_VIEW');$id=sv_positive_int($fileRoute['fileId']);$file=$id?db_row("SELECT * FROM SafetyVote_Files WHERE id=? AND Status='Active' LIMIT 1",[$id]):null;if(!$file)json_response(['success'=>false,'code'=>'FILE_NOT_FOUND','message'=>'File was not found.'],404);if(sv_role($user)!=='ADMIN'&&!sv_has_permission($user,'SAFETY_VOTE_MANAGE')){$scope=db_row("SELECT e.id FROM SafetyVote_EligibilitySnapshots s JOIN SafetyVote_EligibleVoters e ON e.SnapshotID=s.id JOIN SafetyVote_Campaigns c ON c.CurrentVersionID=s.CampaignVersionID WHERE c.id=? AND s.Status='frozen' AND e.EmployeeID=? LIMIT 1",[$file['CampaignID'],sv_actor($user)]);if(!$scope)json_response(['success'=>false,'code'=>'FILE_NOT_FOUND','message'=>'File was not found.'],404);}$disk=sv_private_dir().DIRECTORY_SEPARATOR.basename((string)$file['StoredName']);if(!is_file($disk)||sv_file_mime($disk)!==$file['MimeType'])json_response(['success'=>false,'code'=>'FILE_NOT_FOUND','message'=>'File is unavailable.'],404);header('Content-Type: '.$file['MimeType']);header("Content-Disposition: inline; filename*=UTF-8''".rawurlencode((string)$file['OriginalName']));header('Cache-Control: private, no-store');header('X-Content-Type-Options: nosniff');readfile($disk);exit;}
    $removeFile=route_params($path,'/safety-vote/admin/campaigns/:id/files/:fileId');
    if($method==='DELETE'&&$removeFile!==null){
        sv_require_permission($user,'SAFETY_VOTE_MANAGE');
        $id=sv_positive_int($removeFile['id']);$fileId=sv_positive_int($removeFile['fileId']);$body=json_body();$reason=sv_clean($body['reason']??'',255);
        if(!$id||!$fileId||!$reason)json_response(['success'=>false,'code'=>'VALIDATION_FAILED','message'=>'Campaign, file and removal reason are required.'],400);
        $row=sv_campaign_row($id);
        if(!$row)json_response(['success'=>false,'code'=>'CAMPAIGN_NOT_FOUND','message'=>'Campaign was not found.'],404);
        if($row['Status']!=='Draft'||$row['VersionStatus']!=='Draft')json_response(['success'=>false,'code'=>'CAMPAIGN_STATE_CONFLICT','message'=>'Files can be removed only from Draft campaigns.'],409);
        $stmt=db()->prepare("UPDATE SafetyVote_Files SET Status='Removed',RemovedBy=?,RemovedAt=NOW(),RemovalReason=? WHERE id=? AND CampaignID=? AND Status='Active'");
        $stmt->execute([sv_actor($user),$reason,$fileId,$id]);
        if($stmt->rowCount()===0)json_response(['success'=>false,'code'=>'FILE_NOT_FOUND','message'=>'File was not found.'],404);
        sv_audit($user,'SAFETY_VOTE_FILE_REMOVE','SafetyVote_File',(string)$fileId,$reason,[],$id,(int)$row['CurrentVersionID']);
        json_response(['success'=>true]);
    }
    return false;
}
