<?php
declare(strict_types=1);
require_once __DIR__.'/../lib/safety_vote_analytics.php';

function sva_gate(): void {
    sv_require_schema();
    $table=db_row("SELECT COUNT(*) total FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='SafetyVote_EngagementCounters'");
    $module=db_row("SELECT SettingValue FROM SafetyVote_Settings WHERE SettingKey='module_enabled'");
    $setting=db_row("SELECT SettingValue FROM SafetyVote_Settings WHERE SettingKey='engagement_enabled'");
    if((int)($table['total']??0)!==1)json_response(['success'=>false,'code'=>'SAFETY_VOTE_ANALYTICS_SETUP_REQUIRED','message'=>'Safety Vote engagement analytics migration is required.'],503);
    if((string)($module['SettingValue']??'0')!=='1')json_response(['success'=>false,'code'=>'SAFETY_VOTE_MODULE_DISABLED','message'=>'Safety Vote is disabled.'],503);
    if((string)($setting['SettingValue']??'0')!=='1')json_response(['success'=>false,'code'=>'SAFETY_VOTE_ENGAGEMENT_DISABLED','message'=>'Safety Vote engagement features are disabled.'],503);
}
function sva_range(): ?array {
    $today=new DateTimeImmutable('today');$to=preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)($_GET['to']??''))?(string)$_GET['to']:$today->format('Y-m-d');$from=preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)($_GET['from']??''))?(string)$_GET['from']:$today->modify('-29 days')->format('Y-m-d');
    try{$a=new DateTimeImmutable($from.' 00:00:00');$b=new DateTimeImmutable($to.' 23:59:59');}catch(Throwable$e){return null;}$days=(int)$a->diff($b)->format('%r%a');return$days<0||$days>366?null:['from'=>$from,'to'=>$to];
}
function sva_model(): array {
    $range=sva_range();if(!$range)json_response(['success'=>false,'code'=>'DATE_RANGE_INVALID','message'=>'Date range must be between 1 and 366 days.'],400);$campaignId=isset($_GET['campaignId'])?(int)$_GET['campaignId']:null;if(isset($_GET['campaignId'])&&$campaignId<=0)json_response(['success'=>false,'code'=>'CAMPAIGN_ID_INVALID'],400);$filter=$campaignId?:null;$params=[$filter,$filter];
    $campaignRows=db_rows("SELECT c.id,c.CampaignCode campaignCode,c.Status status,c.CurrentVersionID currentVersionId,v.TitleTh title,v.CampaignType campaignType,v.PrivacyMode privacyMode,v.PrivacyThreshold privacyThreshold,COALESCE((SELECT es.EligibleCount FROM SafetyVote_EligibilitySnapshots es WHERE es.CampaignVersionID=c.CurrentVersionID AND es.Status='frozen' ORDER BY es.id DESC LIMIT 1),0) eligible,(SELECT COUNT(*) FROM SafetyVote_Participation p WHERE p.CampaignVersionID=c.CurrentVersionID AND p.State IN ('started','submitted')) started,(SELECT COUNT(*) FROM SafetyVote_Participation p WHERE p.CampaignVersionID=c.CurrentVersionID AND p.State='submitted') submitted FROM SafetyVote_Campaigns c JOIN SafetyVote_CampaignVersions v ON v.id=c.CurrentVersionID WHERE c.Status<>'Voided' AND (? IS NULL OR c.id=?) ORDER BY c.UpdatedAt DESC,c.id DESC LIMIT 250",$params);
    $counterRows=db_rows("SELECT CampaignID campaignId,PromotionID promotionId,MetricKey metricKey,SUM(MetricCount) total FROM SafetyVote_EngagementCounters WHERE MetricDay BETWEEN ? AND ? AND (? IS NULL OR CampaignID=?) GROUP BY CampaignID,PromotionID,MetricKey",[$range['from'],$range['to'],$filter,$filter]);
    $promotionRows=db_rows("SELECT p.id promotionId,p.CampaignID campaignId,p.TitleTh title,p.CtaLabel ctaLabel,p.Status status FROM SafetyVote_Promotions p WHERE (? IS NULL OR p.CampaignID=?) ORDER BY p.CampaignID,p.Priority DESC,p.id",$params);
    $notificationRows=db_rows("SELECT n.CampaignID campaignId,n.Channel channel,n.Status status,COALESCE(n.LastErrorCode,'') errorCode,COUNT(*) total FROM SafetyVote_Notifications n WHERE DATE(n.CreatedAt) BETWEEN ? AND ? AND (? IS NULL OR n.CampaignID=?) GROUP BY n.CampaignID,n.Channel,n.Status,COALESCE(n.LastErrorCode,'') ORDER BY n.CampaignID,n.Channel,n.Status",[$range['from'],$range['to'],$filter,$filter]);
    $readRows=db_rows("SELECT n.CampaignID campaignId,COUNT(*) total FROM SafetyVote_NotificationReads r JOIN SafetyVote_Notifications n ON n.id=r.NotificationID WHERE DATE(r.ReadAt) BETWEEN ? AND ? AND (? IS NULL OR n.CampaignID=?) GROUP BY n.CampaignID",[$range['from'],$range['to'],$filter,$filter]);
    $scheduleRows=db_rows("SELECT n.CampaignID campaignId,c.CampaignCode campaignCode,n.Channel channel,n.ScheduledAt scheduledAt,COUNT(*) total FROM SafetyVote_Notifications n JOIN SafetyVote_Campaigns c ON c.id=n.CampaignID WHERE DATE(n.ScheduledAt) BETWEEN ? AND ? AND (? IS NULL OR n.CampaignID=?) GROUP BY n.CampaignID,c.CampaignCode,n.Channel,n.ScheduledAt ORDER BY n.ScheduledAt",[$range['from'],$range['to'],$filter,$filter]);
    $auditRows=db_rows("SELECT CampaignID campaignId,BoundedDetail detail FROM SafetyVote_AuditLogs WHERE Action='SAFETY_VOTE_NOTIFICATION_QUEUE' AND DATE(OccurredAt) BETWEEN ? AND ? AND (? IS NULL OR CampaignID=?) ORDER BY id DESC LIMIT 1000",[$range['from'],$range['to'],$filter,$filter]);
    $counters=[];foreach($counterRows as$row)$counters[$row['campaignId'].':'.$row['promotionId'].':'.$row['metricKey']]=sva_int($row['total']);$reads=[];foreach($readRows as$row)$reads[(int)$row['campaignId']]=sva_int($row['total']);$reach=[];foreach($notificationRows as$row)if($row['status']==='Sent')$reach[(int)$row['campaignId']]=($reach[(int)$row['campaignId']]??0)+sva_int($row['total']);$audit=[];foreach($auditRows as$row){$id=(int)$row['campaignId'];$audit[$id]=$audit[$id]??['queued'=>0,'suppressed'=>0];$parsed=sva_queue_audit($row['detail']);$audit[$id]['queued']+=$parsed['queued'];$audit[$id]['suppressed']+=$parsed['suppressed'];}
    $thresholds=[];foreach($campaignRows as$row)$thresholds[(int)$row['id']]=max(2,sva_int($row['privacyThreshold']??5)?:5);$byCampaign=[];foreach($promotionRows as$row){$cid=(int)$row['campaignId'];$pid=(int)$row['promotionId'];$threshold=$thresholds[$cid]??5;$impressions=$counters[$cid.':'.$pid.':impression']??0;$clicks=$counters[$cid.':'.$pid.':cta_click']??0;$byCampaign[$cid][]=['id'=>$pid,'campaignId'=>$cid,'title'=>$row['title'],'ctaLabel'=>$row['ctaLabel'],'status'=>$row['status'],'impressions'=>sva_metric($impressions,$threshold),'ctaClicks'=>sva_metric($clicks,$threshold,$impressions)];}
    $campaigns=[];foreach($campaignRows as$row){$id=(int)$row['id'];$promotions=$byCampaign[$id]??[];$impressions=0;$clicks=0;foreach($promotions as$item){$impressions+=$counters[$id.':'.$item['id'].':impression']??0;$clicks+=$counters[$id.':'.$item['id'].':cta_click']??0;}$metric=sva_campaign_metric($row+['reach'=>$reach[$id]??0,'notificationReads'=>$reads[$id]??0,'impressions'=>$impressions,'ctaClicks'=>$clicks]);$metric['promotions']=$promotions;$campaigns[]=$metric;}
    $deliveries=[];foreach($notificationRows as$row){$id=(int)$row['campaignId'];$deliveries[]=['campaignId'=>$id,'channel'=>$row['channel'],'status'=>$row['status'],'errorCode'=>$row['errorCode']?:null,'total'=>sva_metric($row['total'],$thresholds[$id]??5)];}$suppressions=[];foreach($audit as$id=>$value)$suppressions[]=['campaignId'=>$id,'queued'=>sva_metric($value['queued'],$thresholds[$id]??5),'suppressed'=>sva_metric($value['suppressed'],$thresholds[$id]??5)];$conflicts=sva_conflicts($scheduleRows);
    return['contract'=>SVA_CONTRACT,'range'=>$range,'privacySafe'=>true,'containsIdentity'=>false,'containsVoterChoice'=>false,'campaigns'=>$campaigns,'deliveries'=>$deliveries,'suppressions'=>$suppressions,'scheduleConflicts'=>$conflicts,'recommendations'=>sva_recommendations($campaigns,$deliveries,$conflicts),'exportClassification'=>'authorized_aggregate_only'];
}

function handle_safety_vote_analytics_routes(string$method,string$path): bool {
    $event=route_params($path,'/safety-vote/engagement/promotions/:id/events');$dashboard=$path==='/safety-vote/admin/engagement/analytics';$export=$path==='/safety-vote/admin/engagement/analytics/export.csv';if(!$event&&!$dashboard&&!$export)return false;$user=require_user();sva_gate();
    if($event&&$method==='POST'){sv_require_permission($user,'SAFETY_VOTE_VIEW');$id=(int)$event['id'];$body=json_body();$type=sva_event_type($body['eventType']??null);if($id<=0||!$type)json_response(['success'=>false,'code'=>'VALIDATION_FAILED'],400);$promotion=db_row("SELECT p.id,p.CampaignID,c.CurrentVersionID FROM SafetyVote_Promotions p JOIN SafetyVote_Campaigns c ON c.id=p.CampaignID WHERE p.id=? AND p.Status='Published' AND p.StartAt<=NOW() AND p.EndAt>NOW() AND c.Status IN ('Scheduled','Open','Closed','Certified','Published')",[$id]);if(!$promotion)json_response(['success'=>false,'code'=>'PROMOTION_NOT_AVAILABLE'],404);$eligible=db_row("SELECT 1 ok FROM SafetyVote_EligibilitySnapshots s JOIN SafetyVote_EligibleVoters ev ON ev.SnapshotID=s.id WHERE s.CampaignVersionID=? AND s.Status='frozen' AND ev.EmployeeID=? LIMIT 1",[$promotion['CurrentVersionID'],sv_actor($user)]);if(!$eligible)json_response(['success'=>false,'code'=>'CAMPAIGN_NOT_ELIGIBLE'],403);db_execute('INSERT INTO SafetyVote_EngagementCounters(CampaignID,PromotionID,MetricDay,MetricKey,MetricCount) VALUES(?,?,CURRENT_DATE,?,1) ON DUPLICATE KEY UPDATE MetricCount=MetricCount+1',[$promotion['CampaignID'],$id,$type]);json_response(['success'=>true,'data'=>['accepted'=>true,'aggregateOnly'=>true,'identityStored'=>false]],202);}
    if($dashboard&&$method==='GET'){sv_require_permission($user,'SAFETY_VOTE_RESULT_VIEW');json_response(['success'=>true,'data'=>sva_model()]);}
    if($export&&$method==='GET'){sv_require_permission($user,'SAFETY_VOTE_EXPORT');$model=sva_model();$csv=sva_csv($model);header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="safety-vote-engagement-'.$model['range']['from'].'-'.$model['range']['to'].'.csv"');header('Cache-Control: private, no-store');header('X-Safety-Vote-Privacy-Class: authorized_aggregate_only');echo$csv;exit;}
    return false;
}
