<?php
declare(strict_types=1);
require_once __DIR__.'/../lib/safety_vote_planning.php';

function svpl_gate():void {
    $tables=db_rows("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('SafetyVote_AdminSavedViews','SafetyVote_CampaignTemplates')");
    if(count($tables)!==2)json_response(['success'=>false,'code'=>'SAFETY_VOTE_PLANNING_SETUP_REQUIRED','message'=>'Safety Vote planning migration is required.'],503);
    $setting=db_row("SELECT SettingValue FROM SafetyVote_Settings WHERE SettingKey='engagement_enabled'");
    if(($setting['SettingValue']??'0')!=='1')json_response(['success'=>false,'code'=>'SAFETY_VOTE_ENGAGEMENT_DISABLED','message'=>'Safety Vote engagement features are disabled.'],503);
}
function svpl_campaign_config(int$id):?array {
    $v=db_row("SELECT c.id campaignId,c.CampaignCode campaignCode,c.OwnerEmployeeID ownerEmployeeId,c.DiscoveryMode discoveryMode,c.CurrentVersionID currentVersionId,v.CampaignType campaignType,v.PrivacyMode privacyMode,v.TitleTh titleTh,v.TitleEn titleEn,v.Summary summary,v.Description description,v.RulesText rulesText,v.TimeZone timeZone,v.ResultVisibility resultVisibility,v.EditPolicy editPolicy,v.ScoringMethod scoringMethod,v.PrivacyThreshold privacyThreshold,v.AllowAbstain allowAbstain,v.RandomizeOptions randomizeOptions FROM SafetyVote_Campaigns c JOIN SafetyVote_CampaignVersions v ON v.id=c.CurrentVersionID WHERE c.id=? AND c.Status<>'Voided'",[$id]);
    if(!$v)return null;
    $questions=sv3_questions_db((int)$v['currentVersionId']);
    $rules=db_rows("SELECT RuleGroup ruleGroup,RuleOrder ruleOrder,Effect effect,AttributeKey attributeKey,Operator operator,ValuesJson valuesJson,Reason reason FROM SafetyVote_EligibilityRules WHERE CampaignVersionID=? AND IsActive=1 ORDER BY RuleGroup,RuleOrder,id",[$v['currentVersionId']]);
    foreach($rules as&$rule){$rule['values']=json_decode((string)$rule['valuesJson'],true)?:[];unset($rule['valuesJson']);}unset($rule);
    return['campaignId'=>(int)$v['campaignId'],'campaignCode'=>$v['campaignCode'],'version'=>$v,'questions'=>$questions,'rules'=>$rules];
}
function svpl_recipients(int$campaignId,string$audience):?array {
    $c=db_row("SELECT CurrentVersionID FROM SafetyVote_Campaigns WHERE id=? AND Status<>'Voided'",[$campaignId]);
    if(!$c||!in_array($audience,['eligible','nonparticipants'],true))return null;
    $sql="SELECT ev.EmployeeID,e.CompanyEmail FROM SafetyVote_EligibleVoters ev JOIN SafetyVote_EligibilitySnapshots es ON es.id=ev.SnapshotID LEFT JOIN Employees e ON BINARY e.EmployeeID=BINARY ev.EmployeeID WHERE es.CampaignVersionID=? AND es.Status='frozen'";
    if($audience==='nonparticipants')$sql.=" AND NOT EXISTS(SELECT 1 FROM SafetyVote_Participation p WHERE p.CampaignVersionID=es.CampaignVersionID AND p.EmployeeID=ev.EmployeeID AND p.State='submitted')";
    return db_rows($sql,[$c['CurrentVersionID']]);
}
function svpl_remove_file(?string$name):void {if(!$name)return;$file=sv_private_dir().DIRECTORY_SEPARATOR.basename($name);if(is_file($file))@unlink($file);}

function handle_safety_vote_planning_routes(string$method,string$path):bool {
    if(strpos($path,'/safety-vote/admin/planning')!==0)return false;
    $u=require_user();svpl_gate();sv_require_permission($u,'SAFETY_VOTE_MANAGE');
    $overview=$path==='/safety-vote/admin/planning/overview';
    $saved=$path==='/safety-vote/admin/planning/saved-views';$savedItem=route_params($path,'/safety-vote/admin/planning/saved-views/:id');
    $copy=route_params($path,'/safety-vote/admin/planning/campaigns/:id/config-copy');$templateFrom=route_params($path,'/safety-vote/admin/planning/templates/from-campaign/:id');$templateArchive=route_params($path,'/safety-vote/admin/planning/templates/:id/archive');$template=route_params($path,'/safety-vote/admin/planning/templates/:id');
    $assets=route_params($path,'/safety-vote/admin/planning/campaigns/:id/assets');$attach=route_params($path,'/safety-vote/admin/planning/promotions/:promotionId/assets/:fileId');
    $notification=$path==='/safety-vote/admin/planning/notifications/preview';
    $reviewQueue=$path==='/safety-vote/admin/planning/review-queue';$governance=route_params($path,'/safety-vote/admin/planning/campaigns/:id/governance');$reviewNotes=route_params($path,'/safety-vote/admin/planning/campaigns/:id/review-notes');

    if(($reviewQueue||$governance||$reviewNotes))sv_require_permission($u,'SAFETY_VOTE_AUDIT_VIEW');
    $loadReviewRows=function():array{
        $campaigns=db_rows("SELECT c.id,c.CampaignCode,c.Status,c.OwnerEmployeeID,c.ScheduledOpenAt,c.ScheduledCloseAt,c.UpdatedAt,c.CurrentVersionID,v.TitleTh,v.CampaignType,v.PrivacyMode,(SELECT COUNT(*) FROM SafetyVote_Questions q WHERE q.CampaignVersionID=c.CurrentVersionID AND q.Status='Active') QuestionCount,(SELECT COUNT(*) FROM SafetyVote_EligibilityRules er WHERE er.CampaignVersionID=c.CurrentVersionID AND er.IsActive=1) EligibilityRuleCount,e.EmployeeName OwnerName FROM SafetyVote_Campaigns c JOIN SafetyVote_CampaignVersions v ON v.id=c.CurrentVersionID LEFT JOIN Employees e ON BINARY e.EmployeeID=BINARY c.OwnerEmployeeID WHERE c.Status<>'Voided' ORDER BY c.UpdatedAt DESC,c.id DESC LIMIT 500");
        $roles=db_rows("SELECT cr.CampaignVersionID,cr.EmployeeID,cr.CampaignRole,e.EmployeeName FROM SafetyVote_CampaignRoles cr LEFT JOIN Employees e ON BINARY e.EmployeeID=BINARY cr.EmployeeID WHERE cr.IsActive=1 ORDER BY cr.AssignedAt,cr.id");
        $conflicts=svpl_schedule_conflicts(db_rows("SELECT CampaignID,Channel,ScheduledAt FROM SafetyVote_Notifications WHERE Status IN ('Queued','Pending','Scheduled') ORDER BY ScheduledAt,id"));$rows=[];
        foreach($campaigns as$row){$readiness=svpl_review_readiness($row);$assigned=[];foreach($roles as$roleRow)if((int)$roleRow['CampaignVersionID']===(int)$row['CurrentVersionID'])$assigned[]=['employeeId'=>$roleRow['EmployeeID'],'name'=>$roleRow['EmployeeName']?:null,'role'=>$roleRow['CampaignRole']];$state=$row['Status']==='Draft'?(count($readiness['blockers'])?'needs_attention':'ready_for_authoritative_check'):'monitoring';$rows[]=['id'=>(int)$row['id'],'campaignCode'=>$row['CampaignCode'],'title'=>$row['TitleTh'],'status'=>$row['Status'],'campaignType'=>$row['CampaignType'],'privacyMode'=>$row['PrivacyMode'],'updatedAt'=>$row['UpdatedAt'],'scheduledOpenAt'=>$row['ScheduledOpenAt'],'scheduledCloseAt'=>$row['ScheduledCloseAt'],'owner'=>['employeeId'=>$row['OwnerEmployeeID'],'name'=>$row['OwnerName']?:null],'assignees'=>$assigned,'readiness'=>$readiness,'scheduleConflictCount'=>(int)($conflicts[(int)$row['id']]??0),'derivedQueueState'=>$state];}return$rows;
    };
    if($reviewQueue&&$method==='GET'){$rows=$loadReviewRows();json_response(['success'=>true,'data'=>['contract'=>SVPL_REVIEW_CONTRACT,'rows'=>$rows,'summary'=>['total'=>count($rows),'needsAttention'=>count(array_filter($rows,fn($r)=>$r['derivedQueueState']==='needs_attention')),'readyForCheck'=>count(array_filter($rows,fn($r)=>$r['derivedQueueState']==='ready_for_authoritative_check')),'scheduleConflicts'=>array_sum(array_column($rows,'scheduleConflictCount'))],'derivedOnly'=>true,'approvalState'=>false,'containsBallotData'=>false]]);}
    if($governance&&$method==='GET'){$id=svpl_int($governance['id']);$campaign=null;foreach($loadReviewRows()as$row)if($row['id']===$id){$campaign=$row;break;}if(!$campaign)json_response(['success'=>false,'code'=>'CAMPAIGN_NOT_FOUND'],404);$audit=db_rows('SELECT id,ActorEmployeeID,ActorRole,Action,TargetType,TargetID,BoundedDetail,OccurredAt FROM SafetyVote_AuditLogs WHERE CampaignID=? ORDER BY OccurredAt DESC,id DESC LIMIT 100',[$id]);$timeline=[];foreach($audit as$row){if(preg_match('/BALLOT|ANSWER|RESPONSE|VOTER|RECEIPT|JURY_SCORE|CANDIDATE/i',(string)$row['Action'].' '.(string)$row['TargetType']))continue;$timeline[]=['id'=>(int)$row['id'],'actorEmployeeId'=>$row['ActorEmployeeID'],'actorRole'=>$row['ActorRole'],'action'=>$row['Action'],'targetType'=>$row['TargetType'],'targetId'=>$row['TargetID'],'detail'=>$row['BoundedDetail'],'occurredAt'=>$row['OccurredAt']];}json_response(['success'=>true,'data'=>['campaign'=>$campaign,'timeline'=>$timeline,'reviewNotes'=>array_values(array_filter($timeline,fn($r)=>$r['action']==='SAFETY_VOTE_ADMIN_REVIEW_NOTE')),'classification'=>'restricted_governance','approvalState'=>false,'containsBallotData'=>false]]);}
    if($reviewNotes&&$method==='POST'){$id=svpl_int($reviewNotes['id']);$parsed=svpl_review_note(json_body());if(!$id||!$parsed['ok'])json_response(['success'=>false,'code'=>'VALIDATION_FAILED','details'=>$parsed['errors']],400);if(!db_row("SELECT id FROM SafetyVote_Campaigns WHERE id=? AND Status<>'Voided'",[$id]))json_response(['success'=>false,'code'=>'CAMPAIGN_NOT_FOUND'],404);$x=$parsed['value'];sv_audit($u,'SAFETY_VOTE_ADMIN_REVIEW_NOTE','SafetyVote_Campaign',(string)$id,$x['note'],['category'=>$x['category'],'privacyClass'=>'governance_note_no_ballot_data'],$id);json_response(['success'=>true,'data'=>['campaignId'=>$id,'note'=>$x['note'],'category'=>$x['category'],'approvalState'=>false]],201);}

    if($overview&&$method==='GET'){
        $campaigns=db_rows("SELECT c.id,c.CampaignCode,c.Status,c.OwnerEmployeeID,c.ScheduledOpenAt,c.ScheduledCloseAt,c.UpdatedAt,v.TitleTh,v.CampaignType,v.PrivacyMode FROM SafetyVote_Campaigns c JOIN SafetyVote_CampaignVersions v ON v.id=c.CurrentVersionID WHERE c.Status<>'Voided' ORDER BY COALESCE(c.ScheduledOpenAt,c.UpdatedAt),c.id LIMIT 500");
        $views=db_rows('SELECT id,ViewName,FiltersJson,IsDefault,UpdatedAt FROM SafetyVote_AdminSavedViews WHERE EmployeeID=? ORDER BY IsDefault DESC,UpdatedAt DESC,id DESC LIMIT 20',[sv_actor($u)]);
        foreach($views as&$view){$view=['id'=>(int)$view['id'],'name'=>$view['ViewName'],'filters'=>json_decode((string)$view['FiltersJson'],true)?:[],'isDefault'=>(bool)$view['IsDefault'],'updatedAt'=>$view['UpdatedAt']];}unset($view);
        $templates=db_rows("SELECT id,TemplateName,CampaignType,SourceCampaignID,ConfigSha256,Status,RowVersion,UpdatedAt FROM SafetyVote_CampaignTemplates WHERE Status='Active' ORDER BY UpdatedAt DESC,id DESC LIMIT 100");
        foreach($templates as&$row)$row=['id'=>(int)$row['id'],'name'=>$row['TemplateName'],'campaignType'=>$row['CampaignType'],'sourceCampaignId'=>$row['SourceCampaignID']?(int)$row['SourceCampaignID']:null,'configSha256'=>$row['ConfigSha256'],'status'=>$row['Status'],'rowVersion'=>(int)$row['RowVersion'],'updatedAt'=>$row['UpdatedAt']];unset($row);
        json_response(['success'=>true,'data'=>['contract'=>SVPL_CONTRACT,'campaigns'=>$campaigns,'savedViews'=>$views,'templates'=>$templates]]);
    }
    if($saved&&$method==='POST'){
        $parsed=svpl_saved_view(json_body());if(!$parsed['ok'])json_response(['success'=>false,'code'=>'VALIDATION_FAILED','details'=>$parsed['errors']],400);$count=db_row('SELECT COUNT(*) total FROM SafetyVote_AdminSavedViews WHERE EmployeeID=?',[sv_actor($u)]);if((int)$count['total']>=20)json_response(['success'=>false,'code'=>'SAVED_VIEW_LIMIT'],409);$x=$parsed['value'];if($x['isDefault'])db_execute('UPDATE SafetyVote_AdminSavedViews SET IsDefault=0 WHERE EmployeeID=?',[sv_actor($u)]);
        try{db_execute('INSERT INTO SafetyVote_AdminSavedViews(EmployeeID,ViewName,FiltersJson,IsDefault) VALUES(?,?,?,?)',[sv_actor($u),$x['name'],json_encode($x['filters']),$x['isDefault']?1:0]);$id=(int)db()->lastInsertId();sv_audit($u,'SAFETY_VOTE_SAVED_VIEW_CREATE','SafetyVote_AdminSavedView',(string)$id,'name='.$x['name']);json_response(['success'=>true,'data'=>['id'=>$id,'name'=>$x['name'],'filters'=>$x['filters'],'isDefault'=>$x['isDefault']]],201);}catch(Throwable$e){json_response(['success'=>false,'code'=>'SAVED_VIEW_CREATE_FAILED'],500);}
    }
    if($savedItem&&$method==='DELETE'){$id=svpl_int($savedItem['id']);if(!$id)json_response(['success'=>false,'code'=>'VALIDATION_FAILED'],400);$deleted=db_execute('DELETE FROM SafetyVote_AdminSavedViews WHERE id=? AND EmployeeID=?',[$id,sv_actor($u)]);if(!$deleted)json_response(['success'=>false,'code'=>'SAVED_VIEW_NOT_FOUND'],404);sv_audit($u,'SAFETY_VOTE_SAVED_VIEW_DELETE','SafetyVote_AdminSavedView',(string)$id,'owner-delete');json_response(['success'=>true,'data'=>['id'=>$id,'deleted'=>true]]);}
    if($copy&&$method==='GET'){$id=svpl_int($copy['id']);$source=$id?svpl_campaign_config($id):null;if(!$source)json_response(['success'=>false,'code'=>'CAMPAIGN_NOT_FOUND'],404);$config=svpl_safe_template($source);json_response(['success'=>true,'data'=>['sourceCampaignId'=>$id,'sourceCampaignCode'=>$source['campaignCode'],'config'=>$config,'configSha256'=>svpl_hash($config),'excluded'=>['files','media','frozenEligibility','eligibleVoters','roles','participation','ballots','answers','jury','results','certifications','notifications']]]);}
    if($templateFrom&&$method==='POST'){$id=svpl_int($templateFrom['id']);$parsed=svpl_template_name(json_body());$source=$id?svpl_campaign_config($id):null;if(!$parsed['ok'])json_response(['success'=>false,'code'=>'VALIDATION_FAILED','details'=>$parsed['errors']],400);if(!$source)json_response(['success'=>false,'code'=>'CAMPAIGN_NOT_FOUND'],404);$config=svpl_safe_template($source);$hash=svpl_hash($config);db_execute('INSERT INTO SafetyVote_CampaignTemplates(TemplateName,CampaignType,SourceCampaignID,ConfigJson,ConfigSha256,CreatedBy,UpdatedBy) VALUES(?,?,?,?,?,?,?)',[$parsed['value']['name'],$config['version']['campaignType'],$id,json_encode($config,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$hash,sv_actor($u),sv_actor($u)]);$templateId=(int)db()->lastInsertId();sv_audit($u,'SAFETY_VOTE_TEMPLATE_CREATE','SafetyVote_CampaignTemplate',(string)$templateId,'source='.$id.'; hash='.$hash,[],$id);json_response(['success'=>true,'data'=>['id'=>$templateId,'name'=>$parsed['value']['name'],'campaignType'=>$config['version']['campaignType'],'configSha256'=>$hash]],201);}
    if($template&&$method==='GET'){$id=svpl_int($template['id']);$row=$id?db_row("SELECT * FROM SafetyVote_CampaignTemplates WHERE id=? AND Status='Active'",[$id]):null;if(!$row)json_response(['success'=>false,'code'=>'TEMPLATE_NOT_FOUND'],404);$config=json_decode((string)$row['ConfigJson'],true);if(!is_array($config)||svpl_hash($config)!==$row['ConfigSha256'])json_response(['success'=>false,'code'=>'TEMPLATE_INTEGRITY_FAILED'],409);json_response(['success'=>true,'data'=>['id'=>$id,'name'=>$row['TemplateName'],'campaignType'=>$row['CampaignType'],'config'=>$config,'configSha256'=>$row['ConfigSha256'],'rowVersion'=>(int)$row['RowVersion']]]);}
    if($templateArchive&&$method==='POST'){$id=svpl_int($templateArchive['id']);$body=json_body();$version=svpl_int($body['rowVersion']??null);if(!$id||!$version)json_response(['success'=>false,'code'=>'VALIDATION_FAILED'],400);$updated=db_execute("UPDATE SafetyVote_CampaignTemplates SET Status='Archived',UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=? AND RowVersion=? AND Status='Active'",[sv_actor($u),$id,$version]);if(!$updated)json_response(['success'=>false,'code'=>'VERSION_CONFLICT'],409);sv_audit($u,'SAFETY_VOTE_TEMPLATE_ARCHIVE','SafetyVote_CampaignTemplate',(string)$id,'archived');json_response(['success'=>true,'data'=>['id'=>$id,'archived'=>true]]);}
    if($template&&$method==='DELETE'){$id=svpl_int($template['id']);$body=json_body();$version=svpl_int($body['rowVersion']??null);if(!$id||!$version)json_response(['success'=>false,'code'=>'VALIDATION_FAILED'],400);$updated=db_execute("UPDATE SafetyVote_CampaignTemplates SET Status='Archived',UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=? AND RowVersion=? AND Status='Active'",[sv_actor($u),$id,$version]);if(!$updated)json_response(['success'=>false,'code'=>'VERSION_CONFLICT'],409);sv_audit($u,'SAFETY_VOTE_TEMPLATE_ARCHIVE','SafetyVote_CampaignTemplate',(string)$id,'archived');json_response(['success'=>true,'data'=>['id'=>$id,'archived'=>true]]);}
    if($assets&&$method==='GET'){$id=svpl_int($assets['id']);if(!$id)json_response(['success'=>false,'code'=>'VALIDATION_FAILED'],400);$rows=db_rows("SELECT f.id,f.FilePurpose,f.OriginalName,f.MimeType,f.FileSize,f.ContentSha256,f.UploadedAt FROM SafetyVote_Files f JOIN SafetyVote_Campaigns c ON c.id=f.CampaignID WHERE f.CampaignID=? AND f.CampaignVersionID=c.CurrentVersionID AND f.Status='Active' AND f.MimeType IN ('image/jpeg','image/png','image/webp') AND f.FilePurpose IN ('promotion_library','promotion_desktop','promotion_mobile') ORDER BY f.UploadedAt DESC,f.id DESC LIMIT 100",[$id]);foreach($rows as&$row)$row=['id'=>(int)$row['id'],'purpose'=>$row['FilePurpose'],'originalName'=>$row['OriginalName'],'mimeType'=>$row['MimeType'],'fileSize'=>(int)$row['FileSize'],'contentSha256'=>$row['ContentSha256'],'uploadedAt'=>$row['UploadedAt']];unset($row);json_response(['success'=>true,'data'=>['rows'=>$rows]]);}
    if($assets&&$method==='POST'){$id=svpl_int($assets['id']);$file=$_FILES['file']??null;if(!$id||!$file||(int)$file['error']!==UPLOAD_ERR_OK||(int)$file['size']>10*1024*1024)json_response(['success'=>false,'code'=>'FILE_UPLOAD_REJECTED'],400);$mime=sv_file_mime((string)$file['tmp_name']);if(!in_array($mime,['image/jpeg','image/png','image/webp'],true))json_response(['success'=>false,'code'=>'FILE_UPLOAD_REJECTED'],400);$campaign=db_row("SELECT id,CurrentVersionID FROM SafetyVote_Campaigns WHERE id=? AND Status<>'Voided'",[$id]);if(!$campaign)json_response(['success'=>false,'code'=>'CAMPAIGN_NOT_FOUND'],404);$ext=['image/jpeg'=>'.jpg','image/png'=>'.png','image/webp'=>'.webp'][$mime];$stored=time().'-'.bin2hex(random_bytes(18)).$ext;$target=sv_private_dir().DIRECTORY_SEPARATOR.$stored;if(!move_uploaded_file((string)$file['tmp_name'],$target))json_response(['success'=>false,'code'=>'FILE_UPLOAD_REJECTED'],500);try{db_execute("INSERT INTO SafetyVote_Files(CampaignID,CampaignVersionID,FilePurpose,StoredName,OriginalName,MimeType,FileSize,ContentSha256,UploadedBy) VALUES(?,?,'promotion_library',?,?,?,?,?,?)",[$id,$campaign['CurrentVersionID'],$stored,svpl_clean($file['name']??'',255),$mime,(int)$file['size'],hash_file('sha256',$target),sv_actor($u)]);$fileId=(int)db()->lastInsertId();sv_audit($u,'SAFETY_VOTE_ASSET_LIBRARY_UPLOAD','SafetyVote_File',(string)$fileId,'size='.(int)$file['size'].'; mime='.$mime,['sha256'=>hash_file('sha256',$target)],$id);json_response(['success'=>true,'data'=>['id'=>$fileId,'campaignId'=>$id,'originalName'=>svpl_clean($file['name']??'',255),'mimeType'=>$mime,'fileSize'=>(int)$file['size'],'contentSha256'=>hash_file('sha256',$target)]],201);}catch(Throwable$e){svpl_remove_file($stored);json_response(['success'=>false,'code'=>'ASSET_UPLOAD_FAILED'],500);}}
    if($attach&&$method==='POST'){$promotionId=svpl_int($attach['promotionId']);$fileId=svpl_int($attach['fileId']);$body=json_body();$slot=$body['slot']??'';$column=$slot==='mobile'?'MobileFileID':($slot==='desktop'?'DesktopFileID':null);if(!$promotionId||!$fileId||!$column)json_response(['success'=>false,'code'=>'VALIDATION_FAILED'],400);$owned=db_row("SELECT p.id,p.CampaignID,p.AltText FROM SafetyVote_Promotions p JOIN SafetyVote_Campaigns c ON c.id=p.CampaignID JOIN SafetyVote_Files f ON f.id=? AND f.CampaignID=p.CampaignID AND f.CampaignVersionID=c.CurrentVersionID AND f.Status='Active' AND f.MimeType IN ('image/jpeg','image/png','image/webp') WHERE p.id=?",[$fileId,$promotionId]);if(!$owned)json_response(['success'=>false,'code'=>'ASSET_OWNERSHIP_CONFLICT'],409);if(trim((string)($owned['AltText']??''))==='')json_response(['success'=>false,'code'=>'ASSET_ALT_TEXT_REQUIRED'],409);db_execute("UPDATE SafetyVote_Promotions SET $column=?,UpdatedBy=?,RowVersion=RowVersion+1 WHERE id=?",[$fileId,sv_actor($u),$promotionId]);sv_audit($u,'SAFETY_VOTE_ASSET_LIBRARY_ATTACH','SafetyVote_Promotion',(string)$promotionId,'slot='.$column.'; file='.$fileId,[],$owned['CampaignID']);json_response(['success'=>true,'data'=>['promotionId'=>$promotionId,'fileId'=>$fileId,'slot'=>$slot]]);}
    if($notification&&$method==='POST'){$parsed=svpl_notification_preview(json_body());if(!$parsed['ok'])json_response(['success'=>false,'code'=>'VALIDATION_FAILED','details'=>$parsed['errors']],400);$x=$parsed['value'];$rows=svpl_recipients($x['campaignId'],$x['audience']);if($rows===null)json_response(['success'=>false,'code'=>'CAMPAIGN_NOT_FOUND'],404);$emailReady=count(array_filter($rows,fn($row)=>!empty($row['CompanyEmail'])));$existing=db_row('SELECT COUNT(*) total FROM SafetyVote_Notifications WHERE CampaignID=? AND EventType=? AND Channel=? AND DATE(ScheduledAt)=?',[$x['campaignId'],$x['eventType'],$x['channel'],$x['windowKey']]);json_response(['success'=>true,'data'=>$x+['total'=>count($rows),'channelReady'=>$x['channel']==='email'?$emailReady:count($rows),'channelUnavailable'=>$x['channel']==='email'?count($rows)-$emailReady:0,'possibleDuplicates'=>(int)($existing['total']??0),'externalDelivery'=>false,'queueOnly'=>true,'timeZone'=>'Asia/Bangkok','confirmation'=>'QUEUE '.$x['campaignId'].' '.count($rows)]]);}
    return false;
}
