<?php
// Upload this file as api/config.local.php and set a strong JWT secret.
// config.local.php is intentionally excluded from Git.
return [
    'db_host' => 'localhost',
    'db_port' => 3306,
    'db_user' => 'uattshpc_safetytsh',
    'db_pass' => 'SET_PRODUCTION_DB_PASSWORD',
    'db_name' => 'uattshpc_safetytsh',
    'db_ssl' => false,
    'jwt_secret' => 'SET_A_LONG_RANDOM_SECRET',
    'email_enabled' => true,
    'smtp_host' => 'smtp.gmail.com',
    'smtp_port' => 587,
    'smtp_secure' => false,
    'smtp_starttls' => true,
    'smtp_user' => 'safetytsh@gmail.com',
    'smtp_pass' => 'SET_GMAIL_APP_PASSWORD',
    'smtp_from' => 'safetytsh@gmail.com',
    'smtp_from_name' => 'TSH Safety Core',
    'admin_email' => 'sattaya_w@thaisummit-harness.co.th',
    'fourm_admin_email' => 'sattaya_w@thaisummit-harness.co.th',
    'gemini_api_key' => 'SET_GEMINI_API_KEY',
    'gemini_model' => 'gemini-3.5-flash',
    'gemini_models' => 'gemini-3.5-flash,gemini-2.5-flash,gemini-2.5-flash-lite',
    'gemini_embedding_model' => 'gemini-embedding-2',
    'gemini_api_base' => 'https://generativelanguage.googleapis.com/v1beta',
    'gemini_timeout_ms' => 30000,
    'gemini_max_output_tokens' => 4096,
    'johnny_refine_transient_retries' => 1,
    'johnny_refine_retry_delay_ms' => 1200,
    'gemini_embedding_dimension' => 768,
    'johnny_max_context_chunks' => 6,
    'johnny_max_chunks_per_doc' => 30,
    'johnny_chunk_chars' => 3200,
    'johnny_chunk_overlap_chars' => 350,
    'johnny_reindex_min_char_ratio' => 0.65,
    'johnny_reindex_min_chunk_ratio' => 0.5,
    'johnny_operational_log_retention_days' => 30,
    'johnny_pdf_min_local_text_chars' => 1000,
    'johnny_pdf_min_size_for_short_text_bytes' => 122880,
    'johnny_pdf_max_bytes_per_text_char' => 180,
    'johnny_pdf_ai_max_expected_chars' => 12000,
    'johnny_kb_min_score' => 0.68,
    'johnny_kb_max_upload_mb' => 30,
    'johnny_avatar_max_upload_mb' => 5,
    'johnny_risk_image_max_upload_mb' => 8,
    'johnny_web_research_enabled' => true,
    'johnny_web_allowed_domains' => 'ilo.org,who.int,osha.gov,cdc.gov,niosh.cdc.gov,iso.org,epa.gov,hse.gov.uk,ratchakitcha.soc.go.th,mol.go.th,labour.go.th,osh.labour.go.th,diw.go.th,tisi.go.th,shawpat.or.th',
    'johnny_system_data_enabled' => true,
];
